// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.1
// - protoc             v4.25.1
// source: google/internal/cloud/code/v1internal/cloudcode.proto

package v1internal

import (
	context "context"
	longrunning "github.com/router-for-me/CLIProxyAPI/v6/internal/proto/stubs/longrunning"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	CloudCode_GenerateCode_FullMethodName                   = "/google.internal.cloud.code.v1internal.CloudCode/GenerateCode"
	CloudCode_CompleteCode_FullMethodName                   = "/google.internal.cloud.code.v1internal.CloudCode/CompleteCode"
	CloudCode_TransformCode_FullMethodName                  = "/google.internal.cloud.code.v1internal.CloudCode/TransformCode"
	CloudCode_SearchSnippets_FullMethodName                 = "/google.internal.cloud.code.v1internal.CloudCode/SearchSnippets"
	CloudCode_FetchCodeCustomizationState_FullMethodName    = "/google.internal.cloud.code.v1internal.CloudCode/FetchCodeCustomizationState"
	CloudCode_GenerateChat_FullMethodName                   = "/google.internal.cloud.code.v1internal.CloudCode/GenerateChat"
	CloudCode_StreamGenerateChat_FullMethodName             = "/google.internal.cloud.code.v1internal.CloudCode/StreamGenerateChat"
	CloudCode_InternalAtomicAgenticChat_FullMethodName      = "/google.internal.cloud.code.v1internal.CloudCode/InternalAtomicAgenticChat"
	CloudCode_MigrateDatabaseCode_FullMethodName            = "/google.internal.cloud.code.v1internal.CloudCode/MigrateDatabaseCode"
	CloudCode_ListExperiments_FullMethodName                = "/google.internal.cloud.code.v1internal.CloudCode/ListExperiments"
	CloudCode_LoadCodeAssist_FullMethodName                 = "/google.internal.cloud.code.v1internal.CloudCode/LoadCodeAssist"
	CloudCode_ListCloudAICompanionProjects_FullMethodName   = "/google.internal.cloud.code.v1internal.CloudCode/ListCloudAICompanionProjects"
	CloudCode_ListAgents_FullMethodName                     = "/google.internal.cloud.code.v1internal.CloudCode/ListAgents"
	CloudCode_ListRemoteRepositories_FullMethodName         = "/google.internal.cloud.code.v1internal.CloudCode/ListRemoteRepositories"
	CloudCode_ListModelConfigs_FullMethodName               = "/google.internal.cloud.code.v1internal.CloudCode/ListModelConfigs"
	CloudCode_OnboardUser_FullMethodName                    = "/google.internal.cloud.code.v1internal.CloudCode/OnboardUser"
	CloudCode_OnboardUserBackgroundTasks_FullMethodName     = "/google.internal.cloud.code.v1internal.CloudCode/OnboardUserBackgroundTasks"
	CloudCode_RecordSmartchoicesFeedback_FullMethodName     = "/google.internal.cloud.code.v1internal.CloudCode/RecordSmartchoicesFeedback"
	CloudCode_RecordCodeAssistMetrics_FullMethodName        = "/google.internal.cloud.code.v1internal.CloudCode/RecordCodeAssistMetrics"
	CloudCode_RecordClientEvent_FullMethodName              = "/google.internal.cloud.code.v1internal.CloudCode/RecordClientEvent"
	CloudCode_GetCodeAssistGlobalUserSetting_FullMethodName = "/google.internal.cloud.code.v1internal.CloudCode/GetCodeAssistGlobalUserSetting"
	CloudCode_SetCodeAssistGlobalUserSetting_FullMethodName = "/google.internal.cloud.code.v1internal.CloudCode/SetCodeAssistGlobalUserSetting"
	CloudCode_FetchAdminControls_FullMethodName             = "/google.internal.cloud.code.v1internal.CloudCode/FetchAdminControls"
)

// CloudCodeClient is the client API for CloudCode service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type CloudCodeClient interface {
	GenerateCode(ctx context.Context, in *GenerateCodeRequest, opts ...grpc.CallOption) (*GenerateCodeResponse, error)
	CompleteCode(ctx context.Context, in *CompleteCodeRequest, opts ...grpc.CallOption) (*CompleteCodeResponse, error)
	TransformCode(ctx context.Context, in *TransformCodeRequest, opts ...grpc.CallOption) (*TransformCodeResponse, error)
	SearchSnippets(ctx context.Context, in *SearchSnippetsRequest, opts ...grpc.CallOption) (*SearchSnippetsResponse, error)
	FetchCodeCustomizationState(ctx context.Context, in *FetchCodeCustomizationStateRequest, opts ...grpc.CallOption) (*FetchCodeCustomizationStateResponse, error)
	GenerateChat(ctx context.Context, in *GenerateChatRequest, opts ...grpc.CallOption) (*GenerateChatResponse, error)
	StreamGenerateChat(ctx context.Context, in *GenerateChatRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[GenerateChatResponse], error)
	InternalAtomicAgenticChat(ctx context.Context, in *InternalAtomicAgenticChatRequest, opts ...grpc.CallOption) (*InternalAtomicAgenticChatResponse, error)
	MigrateDatabaseCode(ctx context.Context, in *MigrateDatabaseCodeRequest, opts ...grpc.CallOption) (*MigrateDatabaseCodeResponse, error)
	ListExperiments(ctx context.Context, in *ListExperimentsRequest, opts ...grpc.CallOption) (*ListExperimentsResponse, error)
	LoadCodeAssist(ctx context.Context, in *LoadCodeAssistRequest, opts ...grpc.CallOption) (*LoadCodeAssistResponse, error)
	ListCloudAICompanionProjects(ctx context.Context, in *ListCloudAICompanionProjectsRequest, opts ...grpc.CallOption) (*ListCloudAICompanionProjectsResponse, error)
	ListAgents(ctx context.Context, in *ListAgentsRequest, opts ...grpc.CallOption) (*ListAgentsResponse, error)
	ListRemoteRepositories(ctx context.Context, in *ListRemoteRepositoriesRequest, opts ...grpc.CallOption) (*ListRemoteRepositoriesResponse, error)
	ListModelConfigs(ctx context.Context, in *ListModelConfigsRequest, opts ...grpc.CallOption) (*ListModelConfigsResponse, error)
	OnboardUser(ctx context.Context, in *OnboardUserRequest, opts ...grpc.CallOption) (*longrunning.Operation, error)
	OnboardUserBackgroundTasks(ctx context.Context, in *OnboardUserBackgroundTasksRequest, opts ...grpc.CallOption) (*emptypb.Empty, error)
	RecordSmartchoicesFeedback(ctx context.Context, in *RecordSmartchoicesFeedbackRequest, opts ...grpc.CallOption) (*RecordSmartchoicesFeedbackResponse, error)
	RecordCodeAssistMetrics(ctx context.Context, in *RecordCodeAssistMetricsRequest, opts ...grpc.CallOption) (*emptypb.Empty, error)
	RecordClientEvent(ctx context.Context, in *RecordClientEventRequest, opts ...grpc.CallOption) (*emptypb.Empty, error)
	GetCodeAssistGlobalUserSetting(ctx context.Context, in *GetCodeAssistGlobalUserSettingRequest, opts ...grpc.CallOption) (*CodeAssistGlobalUserSettingResponse, error)
	SetCodeAssistGlobalUserSetting(ctx context.Context, in *SetCodeAssistGlobalUserSettingRequest, opts ...grpc.CallOption) (*CodeAssistGlobalUserSettingResponse, error)
	FetchAdminControls(ctx context.Context, in *FetchAdminControlsRequest, opts ...grpc.CallOption) (*FetchAdminControlsResponse, error)
}

type cloudCodeClient struct {
	cc grpc.ClientConnInterface
}

func NewCloudCodeClient(cc grpc.ClientConnInterface) CloudCodeClient {
	return &cloudCodeClient{cc}
}

func (c *cloudCodeClient) GenerateCode(ctx context.Context, in *GenerateCodeRequest, opts ...grpc.CallOption) (*GenerateCodeResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GenerateCodeResponse)
	err := c.cc.Invoke(ctx, CloudCode_GenerateCode_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *cloudCodeClient) CompleteCode(ctx context.Context, in *CompleteCodeRequest, opts ...grpc.CallOption) (*CompleteCodeResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CompleteCodeResponse)
	err := c.cc.Invoke(ctx, CloudCode_CompleteCode_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *cloudCodeClient) TransformCode(ctx context.Context, in *TransformCodeRequest, opts ...grpc.CallOption) (*TransformCodeResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(TransformCodeResponse)
	err := c.cc.Invoke(ctx, CloudCode_TransformCode_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *cloudCodeClient) SearchSnippets(ctx context.Context, in *SearchSnippetsRequest, opts ...grpc.CallOption) (*SearchSnippetsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(SearchSnippetsResponse)
	err := c.cc.Invoke(ctx, CloudCode_SearchSnippets_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *cloudCodeClient) FetchCodeCustomizationState(ctx context.Context, in *FetchCodeCustomizationStateRequest, opts ...grpc.CallOption) (*FetchCodeCustomizationStateResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(FetchCodeCustomizationStateResponse)
	err := c.cc.Invoke(ctx, CloudCode_FetchCodeCustomizationState_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *cloudCodeClient) GenerateChat(ctx context.Context, in *GenerateChatRequest, opts ...grpc.CallOption) (*GenerateChatResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GenerateChatResponse)
	err := c.cc.Invoke(ctx, CloudCode_GenerateChat_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *cloudCodeClient) StreamGenerateChat(ctx context.Context, in *GenerateChatRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[GenerateChatResponse], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &CloudCode_ServiceDesc.Streams[0], CloudCode_StreamGenerateChat_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[GenerateChatRequest, GenerateChatResponse]{ClientStream: stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type CloudCode_StreamGenerateChatClient = grpc.ServerStreamingClient[GenerateChatResponse]

func (c *cloudCodeClient) InternalAtomicAgenticChat(ctx context.Context, in *InternalAtomicAgenticChatRequest, opts ...grpc.CallOption) (*InternalAtomicAgenticChatResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(InternalAtomicAgenticChatResponse)
	err := c.cc.Invoke(ctx, CloudCode_InternalAtomicAgenticChat_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *cloudCodeClient) MigrateDatabaseCode(ctx context.Context, in *MigrateDatabaseCodeRequest, opts ...grpc.CallOption) (*MigrateDatabaseCodeResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(MigrateDatabaseCodeResponse)
	err := c.cc.Invoke(ctx, CloudCode_MigrateDatabaseCode_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *cloudCodeClient) ListExperiments(ctx context.Context, in *ListExperimentsRequest, opts ...grpc.CallOption) (*ListExperimentsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListExperimentsResponse)
	err := c.cc.Invoke(ctx, CloudCode_ListExperiments_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *cloudCodeClient) LoadCodeAssist(ctx context.Context, in *LoadCodeAssistRequest, opts ...grpc.CallOption) (*LoadCodeAssistResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(LoadCodeAssistResponse)
	err := c.cc.Invoke(ctx, CloudCode_LoadCodeAssist_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *cloudCodeClient) ListCloudAICompanionProjects(ctx context.Context, in *ListCloudAICompanionProjectsRequest, opts ...grpc.CallOption) (*ListCloudAICompanionProjectsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListCloudAICompanionProjectsResponse)
	err := c.cc.Invoke(ctx, CloudCode_ListCloudAICompanionProjects_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *cloudCodeClient) ListAgents(ctx context.Context, in *ListAgentsRequest, opts ...grpc.CallOption) (*ListAgentsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListAgentsResponse)
	err := c.cc.Invoke(ctx, CloudCode_ListAgents_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *cloudCodeClient) ListRemoteRepositories(ctx context.Context, in *ListRemoteRepositoriesRequest, opts ...grpc.CallOption) (*ListRemoteRepositoriesResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListRemoteRepositoriesResponse)
	err := c.cc.Invoke(ctx, CloudCode_ListRemoteRepositories_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *cloudCodeClient) ListModelConfigs(ctx context.Context, in *ListModelConfigsRequest, opts ...grpc.CallOption) (*ListModelConfigsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListModelConfigsResponse)
	err := c.cc.Invoke(ctx, CloudCode_ListModelConfigs_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *cloudCodeClient) OnboardUser(ctx context.Context, in *OnboardUserRequest, opts ...grpc.CallOption) (*longrunning.Operation, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(longrunning.Operation)
	err := c.cc.Invoke(ctx, CloudCode_OnboardUser_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *cloudCodeClient) OnboardUserBackgroundTasks(ctx context.Context, in *OnboardUserBackgroundTasksRequest, opts ...grpc.CallOption) (*emptypb.Empty, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(emptypb.Empty)
	err := c.cc.Invoke(ctx, CloudCode_OnboardUserBackgroundTasks_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *cloudCodeClient) RecordSmartchoicesFeedback(ctx context.Context, in *RecordSmartchoicesFeedbackRequest, opts ...grpc.CallOption) (*RecordSmartchoicesFeedbackResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(RecordSmartchoicesFeedbackResponse)
	err := c.cc.Invoke(ctx, CloudCode_RecordSmartchoicesFeedback_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *cloudCodeClient) RecordCodeAssistMetrics(ctx context.Context, in *RecordCodeAssistMetricsRequest, opts ...grpc.CallOption) (*emptypb.Empty, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(emptypb.Empty)
	err := c.cc.Invoke(ctx, CloudCode_RecordCodeAssistMetrics_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *cloudCodeClient) RecordClientEvent(ctx context.Context, in *RecordClientEventRequest, opts ...grpc.CallOption) (*emptypb.Empty, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(emptypb.Empty)
	err := c.cc.Invoke(ctx, CloudCode_RecordClientEvent_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *cloudCodeClient) GetCodeAssistGlobalUserSetting(ctx context.Context, in *GetCodeAssistGlobalUserSettingRequest, opts ...grpc.CallOption) (*CodeAssistGlobalUserSettingResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CodeAssistGlobalUserSettingResponse)
	err := c.cc.Invoke(ctx, CloudCode_GetCodeAssistGlobalUserSetting_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *cloudCodeClient) SetCodeAssistGlobalUserSetting(ctx context.Context, in *SetCodeAssistGlobalUserSettingRequest, opts ...grpc.CallOption) (*CodeAssistGlobalUserSettingResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CodeAssistGlobalUserSettingResponse)
	err := c.cc.Invoke(ctx, CloudCode_SetCodeAssistGlobalUserSetting_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *cloudCodeClient) FetchAdminControls(ctx context.Context, in *FetchAdminControlsRequest, opts ...grpc.CallOption) (*FetchAdminControlsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(FetchAdminControlsResponse)
	err := c.cc.Invoke(ctx, CloudCode_FetchAdminControls_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// CloudCodeServer is the server API for CloudCode service.
// All implementations must embed UnimplementedCloudCodeServer
// for forward compatibility.
type CloudCodeServer interface {
	GenerateCode(context.Context, *GenerateCodeRequest) (*GenerateCodeResponse, error)
	CompleteCode(context.Context, *CompleteCodeRequest) (*CompleteCodeResponse, error)
	TransformCode(context.Context, *TransformCodeRequest) (*TransformCodeResponse, error)
	SearchSnippets(context.Context, *SearchSnippetsRequest) (*SearchSnippetsResponse, error)
	FetchCodeCustomizationState(context.Context, *FetchCodeCustomizationStateRequest) (*FetchCodeCustomizationStateResponse, error)
	GenerateChat(context.Context, *GenerateChatRequest) (*GenerateChatResponse, error)
	StreamGenerateChat(*GenerateChatRequest, grpc.ServerStreamingServer[GenerateChatResponse]) error
	InternalAtomicAgenticChat(context.Context, *InternalAtomicAgenticChatRequest) (*InternalAtomicAgenticChatResponse, error)
	MigrateDatabaseCode(context.Context, *MigrateDatabaseCodeRequest) (*MigrateDatabaseCodeResponse, error)
	ListExperiments(context.Context, *ListExperimentsRequest) (*ListExperimentsResponse, error)
	LoadCodeAssist(context.Context, *LoadCodeAssistRequest) (*LoadCodeAssistResponse, error)
	ListCloudAICompanionProjects(context.Context, *ListCloudAICompanionProjectsRequest) (*ListCloudAICompanionProjectsResponse, error)
	ListAgents(context.Context, *ListAgentsRequest) (*ListAgentsResponse, error)
	ListRemoteRepositories(context.Context, *ListRemoteRepositoriesRequest) (*ListRemoteRepositoriesResponse, error)
	ListModelConfigs(context.Context, *ListModelConfigsRequest) (*ListModelConfigsResponse, error)
	OnboardUser(context.Context, *OnboardUserRequest) (*longrunning.Operation, error)
	OnboardUserBackgroundTasks(context.Context, *OnboardUserBackgroundTasksRequest) (*emptypb.Empty, error)
	RecordSmartchoicesFeedback(context.Context, *RecordSmartchoicesFeedbackRequest) (*RecordSmartchoicesFeedbackResponse, error)
	RecordCodeAssistMetrics(context.Context, *RecordCodeAssistMetricsRequest) (*emptypb.Empty, error)
	RecordClientEvent(context.Context, *RecordClientEventRequest) (*emptypb.Empty, error)
	GetCodeAssistGlobalUserSetting(context.Context, *GetCodeAssistGlobalUserSettingRequest) (*CodeAssistGlobalUserSettingResponse, error)
	SetCodeAssistGlobalUserSetting(context.Context, *SetCodeAssistGlobalUserSettingRequest) (*CodeAssistGlobalUserSettingResponse, error)
	FetchAdminControls(context.Context, *FetchAdminControlsRequest) (*FetchAdminControlsResponse, error)
	mustEmbedUnimplementedCloudCodeServer()
}

// UnimplementedCloudCodeServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedCloudCodeServer struct{}

func (UnimplementedCloudCodeServer) GenerateCode(context.Context, *GenerateCodeRequest) (*GenerateCodeResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GenerateCode not implemented")
}
func (UnimplementedCloudCodeServer) CompleteCode(context.Context, *CompleteCodeRequest) (*CompleteCodeResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method CompleteCode not implemented")
}
func (UnimplementedCloudCodeServer) TransformCode(context.Context, *TransformCodeRequest) (*TransformCodeResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method TransformCode not implemented")
}
func (UnimplementedCloudCodeServer) SearchSnippets(context.Context, *SearchSnippetsRequest) (*SearchSnippetsResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method SearchSnippets not implemented")
}
func (UnimplementedCloudCodeServer) FetchCodeCustomizationState(context.Context, *FetchCodeCustomizationStateRequest) (*FetchCodeCustomizationStateResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method FetchCodeCustomizationState not implemented")
}
func (UnimplementedCloudCodeServer) GenerateChat(context.Context, *GenerateChatRequest) (*GenerateChatResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GenerateChat not implemented")
}
func (UnimplementedCloudCodeServer) StreamGenerateChat(*GenerateChatRequest, grpc.ServerStreamingServer[GenerateChatResponse]) error {
	return status.Error(codes.Unimplemented, "method StreamGenerateChat not implemented")
}
func (UnimplementedCloudCodeServer) InternalAtomicAgenticChat(context.Context, *InternalAtomicAgenticChatRequest) (*InternalAtomicAgenticChatResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method InternalAtomicAgenticChat not implemented")
}
func (UnimplementedCloudCodeServer) MigrateDatabaseCode(context.Context, *MigrateDatabaseCodeRequest) (*MigrateDatabaseCodeResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method MigrateDatabaseCode not implemented")
}
func (UnimplementedCloudCodeServer) ListExperiments(context.Context, *ListExperimentsRequest) (*ListExperimentsResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ListExperiments not implemented")
}
func (UnimplementedCloudCodeServer) LoadCodeAssist(context.Context, *LoadCodeAssistRequest) (*LoadCodeAssistResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method LoadCodeAssist not implemented")
}
func (UnimplementedCloudCodeServer) ListCloudAICompanionProjects(context.Context, *ListCloudAICompanionProjectsRequest) (*ListCloudAICompanionProjectsResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ListCloudAICompanionProjects not implemented")
}
func (UnimplementedCloudCodeServer) ListAgents(context.Context, *ListAgentsRequest) (*ListAgentsResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ListAgents not implemented")
}
func (UnimplementedCloudCodeServer) ListRemoteRepositories(context.Context, *ListRemoteRepositoriesRequest) (*ListRemoteRepositoriesResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ListRemoteRepositories not implemented")
}
func (UnimplementedCloudCodeServer) ListModelConfigs(context.Context, *ListModelConfigsRequest) (*ListModelConfigsResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ListModelConfigs not implemented")
}
func (UnimplementedCloudCodeServer) OnboardUser(context.Context, *OnboardUserRequest) (*longrunning.Operation, error) {
	return nil, status.Error(codes.Unimplemented, "method OnboardUser not implemented")
}
func (UnimplementedCloudCodeServer) OnboardUserBackgroundTasks(context.Context, *OnboardUserBackgroundTasksRequest) (*emptypb.Empty, error) {
	return nil, status.Error(codes.Unimplemented, "method OnboardUserBackgroundTasks not implemented")
}
func (UnimplementedCloudCodeServer) RecordSmartchoicesFeedback(context.Context, *RecordSmartchoicesFeedbackRequest) (*RecordSmartchoicesFeedbackResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method RecordSmartchoicesFeedback not implemented")
}
func (UnimplementedCloudCodeServer) RecordCodeAssistMetrics(context.Context, *RecordCodeAssistMetricsRequest) (*emptypb.Empty, error) {
	return nil, status.Error(codes.Unimplemented, "method RecordCodeAssistMetrics not implemented")
}
func (UnimplementedCloudCodeServer) RecordClientEvent(context.Context, *RecordClientEventRequest) (*emptypb.Empty, error) {
	return nil, status.Error(codes.Unimplemented, "method RecordClientEvent not implemented")
}
func (UnimplementedCloudCodeServer) GetCodeAssistGlobalUserSetting(context.Context, *GetCodeAssistGlobalUserSettingRequest) (*CodeAssistGlobalUserSettingResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetCodeAssistGlobalUserSetting not implemented")
}
func (UnimplementedCloudCodeServer) SetCodeAssistGlobalUserSetting(context.Context, *SetCodeAssistGlobalUserSettingRequest) (*CodeAssistGlobalUserSettingResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method SetCodeAssistGlobalUserSetting not implemented")
}
func (UnimplementedCloudCodeServer) FetchAdminControls(context.Context, *FetchAdminControlsRequest) (*FetchAdminControlsResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method FetchAdminControls not implemented")
}
func (UnimplementedCloudCodeServer) mustEmbedUnimplementedCloudCodeServer() {}
func (UnimplementedCloudCodeServer) testEmbeddedByValue()                   {}

// UnsafeCloudCodeServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to CloudCodeServer will
// result in compilation errors.
type UnsafeCloudCodeServer interface {
	mustEmbedUnimplementedCloudCodeServer()
}

func RegisterCloudCodeServer(s grpc.ServiceRegistrar, srv CloudCodeServer) {
	// If the following call panics, it indicates UnimplementedCloudCodeServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&CloudCode_ServiceDesc, srv)
}

func _CloudCode_GenerateCode_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GenerateCodeRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CloudCodeServer).GenerateCode(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: CloudCode_GenerateCode_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CloudCodeServer).GenerateCode(ctx, req.(*GenerateCodeRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _CloudCode_CompleteCode_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CompleteCodeRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CloudCodeServer).CompleteCode(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: CloudCode_CompleteCode_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CloudCodeServer).CompleteCode(ctx, req.(*CompleteCodeRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _CloudCode_TransformCode_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(TransformCodeRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CloudCodeServer).TransformCode(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: CloudCode_TransformCode_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CloudCodeServer).TransformCode(ctx, req.(*TransformCodeRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _CloudCode_SearchSnippets_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SearchSnippetsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CloudCodeServer).SearchSnippets(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: CloudCode_SearchSnippets_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CloudCodeServer).SearchSnippets(ctx, req.(*SearchSnippetsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _CloudCode_FetchCodeCustomizationState_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(FetchCodeCustomizationStateRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CloudCodeServer).FetchCodeCustomizationState(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: CloudCode_FetchCodeCustomizationState_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CloudCodeServer).FetchCodeCustomizationState(ctx, req.(*FetchCodeCustomizationStateRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _CloudCode_GenerateChat_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GenerateChatRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CloudCodeServer).GenerateChat(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: CloudCode_GenerateChat_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CloudCodeServer).GenerateChat(ctx, req.(*GenerateChatRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _CloudCode_StreamGenerateChat_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(GenerateChatRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(CloudCodeServer).StreamGenerateChat(m, &grpc.GenericServerStream[GenerateChatRequest, GenerateChatResponse]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type CloudCode_StreamGenerateChatServer = grpc.ServerStreamingServer[GenerateChatResponse]

func _CloudCode_InternalAtomicAgenticChat_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(InternalAtomicAgenticChatRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CloudCodeServer).InternalAtomicAgenticChat(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: CloudCode_InternalAtomicAgenticChat_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CloudCodeServer).InternalAtomicAgenticChat(ctx, req.(*InternalAtomicAgenticChatRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _CloudCode_MigrateDatabaseCode_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(MigrateDatabaseCodeRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CloudCodeServer).MigrateDatabaseCode(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: CloudCode_MigrateDatabaseCode_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CloudCodeServer).MigrateDatabaseCode(ctx, req.(*MigrateDatabaseCodeRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _CloudCode_ListExperiments_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListExperimentsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CloudCodeServer).ListExperiments(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: CloudCode_ListExperiments_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CloudCodeServer).ListExperiments(ctx, req.(*ListExperimentsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _CloudCode_LoadCodeAssist_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(LoadCodeAssistRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CloudCodeServer).LoadCodeAssist(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: CloudCode_LoadCodeAssist_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CloudCodeServer).LoadCodeAssist(ctx, req.(*LoadCodeAssistRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _CloudCode_ListCloudAICompanionProjects_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListCloudAICompanionProjectsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CloudCodeServer).ListCloudAICompanionProjects(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: CloudCode_ListCloudAICompanionProjects_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CloudCodeServer).ListCloudAICompanionProjects(ctx, req.(*ListCloudAICompanionProjectsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _CloudCode_ListAgents_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListAgentsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CloudCodeServer).ListAgents(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: CloudCode_ListAgents_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CloudCodeServer).ListAgents(ctx, req.(*ListAgentsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _CloudCode_ListRemoteRepositories_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListRemoteRepositoriesRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CloudCodeServer).ListRemoteRepositories(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: CloudCode_ListRemoteRepositories_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CloudCodeServer).ListRemoteRepositories(ctx, req.(*ListRemoteRepositoriesRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _CloudCode_ListModelConfigs_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListModelConfigsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CloudCodeServer).ListModelConfigs(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: CloudCode_ListModelConfigs_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CloudCodeServer).ListModelConfigs(ctx, req.(*ListModelConfigsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _CloudCode_OnboardUser_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(OnboardUserRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CloudCodeServer).OnboardUser(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: CloudCode_OnboardUser_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CloudCodeServer).OnboardUser(ctx, req.(*OnboardUserRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _CloudCode_OnboardUserBackgroundTasks_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(OnboardUserBackgroundTasksRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CloudCodeServer).OnboardUserBackgroundTasks(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: CloudCode_OnboardUserBackgroundTasks_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CloudCodeServer).OnboardUserBackgroundTasks(ctx, req.(*OnboardUserBackgroundTasksRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _CloudCode_RecordSmartchoicesFeedback_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RecordSmartchoicesFeedbackRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CloudCodeServer).RecordSmartchoicesFeedback(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: CloudCode_RecordSmartchoicesFeedback_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CloudCodeServer).RecordSmartchoicesFeedback(ctx, req.(*RecordSmartchoicesFeedbackRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _CloudCode_RecordCodeAssistMetrics_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RecordCodeAssistMetricsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CloudCodeServer).RecordCodeAssistMetrics(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: CloudCode_RecordCodeAssistMetrics_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CloudCodeServer).RecordCodeAssistMetrics(ctx, req.(*RecordCodeAssistMetricsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _CloudCode_RecordClientEvent_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RecordClientEventRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CloudCodeServer).RecordClientEvent(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: CloudCode_RecordClientEvent_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CloudCodeServer).RecordClientEvent(ctx, req.(*RecordClientEventRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _CloudCode_GetCodeAssistGlobalUserSetting_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetCodeAssistGlobalUserSettingRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CloudCodeServer).GetCodeAssistGlobalUserSetting(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: CloudCode_GetCodeAssistGlobalUserSetting_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CloudCodeServer).GetCodeAssistGlobalUserSetting(ctx, req.(*GetCodeAssistGlobalUserSettingRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _CloudCode_SetCodeAssistGlobalUserSetting_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SetCodeAssistGlobalUserSettingRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CloudCodeServer).SetCodeAssistGlobalUserSetting(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: CloudCode_SetCodeAssistGlobalUserSetting_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CloudCodeServer).SetCodeAssistGlobalUserSetting(ctx, req.(*SetCodeAssistGlobalUserSettingRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _CloudCode_FetchAdminControls_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(FetchAdminControlsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CloudCodeServer).FetchAdminControls(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: CloudCode_FetchAdminControls_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CloudCodeServer).FetchAdminControls(ctx, req.(*FetchAdminControlsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// CloudCode_ServiceDesc is the grpc.ServiceDesc for CloudCode service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var CloudCode_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "google.internal.cloud.code.v1internal.CloudCode",
	HandlerType: (*CloudCodeServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GenerateCode",
			Handler:    _CloudCode_GenerateCode_Handler,
		},
		{
			MethodName: "CompleteCode",
			Handler:    _CloudCode_CompleteCode_Handler,
		},
		{
			MethodName: "TransformCode",
			Handler:    _CloudCode_TransformCode_Handler,
		},
		{
			MethodName: "SearchSnippets",
			Handler:    _CloudCode_SearchSnippets_Handler,
		},
		{
			MethodName: "FetchCodeCustomizationState",
			Handler:    _CloudCode_FetchCodeCustomizationState_Handler,
		},
		{
			MethodName: "GenerateChat",
			Handler:    _CloudCode_GenerateChat_Handler,
		},
		{
			MethodName: "InternalAtomicAgenticChat",
			Handler:    _CloudCode_InternalAtomicAgenticChat_Handler,
		},
		{
			MethodName: "MigrateDatabaseCode",
			Handler:    _CloudCode_MigrateDatabaseCode_Handler,
		},
		{
			MethodName: "ListExperiments",
			Handler:    _CloudCode_ListExperiments_Handler,
		},
		{
			MethodName: "LoadCodeAssist",
			Handler:    _CloudCode_LoadCodeAssist_Handler,
		},
		{
			MethodName: "ListCloudAICompanionProjects",
			Handler:    _CloudCode_ListCloudAICompanionProjects_Handler,
		},
		{
			MethodName: "ListAgents",
			Handler:    _CloudCode_ListAgents_Handler,
		},
		{
			MethodName: "ListRemoteRepositories",
			Handler:    _CloudCode_ListRemoteRepositories_Handler,
		},
		{
			MethodName: "ListModelConfigs",
			Handler:    _CloudCode_ListModelConfigs_Handler,
		},
		{
			MethodName: "OnboardUser",
			Handler:    _CloudCode_OnboardUser_Handler,
		},
		{
			MethodName: "OnboardUserBackgroundTasks",
			Handler:    _CloudCode_OnboardUserBackgroundTasks_Handler,
		},
		{
			MethodName: "RecordSmartchoicesFeedback",
			Handler:    _CloudCode_RecordSmartchoicesFeedback_Handler,
		},
		{
			MethodName: "RecordCodeAssistMetrics",
			Handler:    _CloudCode_RecordCodeAssistMetrics_Handler,
		},
		{
			MethodName: "RecordClientEvent",
			Handler:    _CloudCode_RecordClientEvent_Handler,
		},
		{
			MethodName: "GetCodeAssistGlobalUserSetting",
			Handler:    _CloudCode_GetCodeAssistGlobalUserSetting_Handler,
		},
		{
			MethodName: "SetCodeAssistGlobalUserSetting",
			Handler:    _CloudCode_SetCodeAssistGlobalUserSetting_Handler,
		},
		{
			MethodName: "FetchAdminControls",
			Handler:    _CloudCode_FetchAdminControls_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "StreamGenerateChat",
			Handler:       _CloudCode_StreamGenerateChat_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "google/internal/cloud/code/v1internal/cloudcode.proto",
}
