// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v4.25.1
// source: google/internal/cloud/code/v1internal/credits.proto

package v1internal

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Credits_CreditType int32

const (
	Credits_CREDIT_TYPE_UNSPECIFIED Credits_CreditType = 0
	Credits_GOOGLE_ONE_AI           Credits_CreditType = 1
)

// Enum value maps for Credits_CreditType.
var (
	Credits_CreditType_name = map[int32]string{
		0: "CREDIT_TYPE_UNSPECIFIED",
		1: "GOOGLE_ONE_AI",
	}
	Credits_CreditType_value = map[string]int32{
		"CREDIT_TYPE_UNSPECIFIED": 0,
		"GOOGLE_ONE_AI":           1,
	}
)

func (x Credits_CreditType) Enum() *Credits_CreditType {
	p := new(Credits_CreditType)
	*p = x
	return p
}

func (x Credits_CreditType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Credits_CreditType) Descriptor() protoreflect.EnumDescriptor {
	return file_google_internal_cloud_code_v1internal_credits_proto_enumTypes[0].Descriptor()
}

func (Credits_CreditType) Type() protoreflect.EnumType {
	return &file_google_internal_cloud_code_v1internal_credits_proto_enumTypes[0]
}

func (x Credits_CreditType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use Credits_CreditType.Descriptor instead.
func (Credits_CreditType) EnumDescriptor() ([]byte, []int) {
	return file_google_internal_cloud_code_v1internal_credits_proto_rawDescGZIP(), []int{0, 0}
}

type Credits struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	CreditType    Credits_CreditType     `protobuf:"varint,1,opt,name=credit_type,json=creditType,proto3,enum=google.internal.cloud.code.v1internal.Credits_CreditType" json:"credit_type,omitempty"`
	CreditAmount  int64                  `protobuf:"varint,2,opt,name=credit_amount,json=creditAmount,proto3" json:"credit_amount,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Credits) Reset() {
	*x = Credits{}
	mi := &file_google_internal_cloud_code_v1internal_credits_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Credits) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Credits) ProtoMessage() {}

func (x *Credits) ProtoReflect() protoreflect.Message {
	mi := &file_google_internal_cloud_code_v1internal_credits_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Credits.ProtoReflect.Descriptor instead.
func (*Credits) Descriptor() ([]byte, []int) {
	return file_google_internal_cloud_code_v1internal_credits_proto_rawDescGZIP(), []int{0}
}

func (x *Credits) GetCreditType() Credits_CreditType {
	if x != nil {
		return x.CreditType
	}
	return Credits_CREDIT_TYPE_UNSPECIFIED
}

func (x *Credits) GetCreditAmount() int64 {
	if x != nil {
		return x.CreditAmount
	}
	return 0
}

var File_google_internal_cloud_code_v1internal_credits_proto protoreflect.FileDescriptor

const file_google_internal_cloud_code_v1internal_credits_proto_rawDesc = "" +
	"\n" +
	"3google/internal/cloud/code/v1internal/credits.proto\x12%google.internal.cloud.code.v1internal\"\xc8\x01\n" +
	"\aCredits\x12Z\n" +
	"\vcredit_type\x18\x01 \x01(\x0e29.google.internal.cloud.code.v1internal.Credits.CreditTypeR\n" +
	"creditType\x12#\n" +
	"\rcredit_amount\x18\x02 \x01(\x03R\fcreditAmount\"<\n" +
	"\n" +
	"CreditType\x12\x1b\n" +
	"\x17CREDIT_TYPE_UNSPECIFIED\x10\x00\x12\x11\n" +
	"\rGOOGLE_ONE_AI\x10\x01BCZAgithub.com/router-for-me/CLIProxyAPI/v6/internal/proto/v1internalb\x06proto3"

var (
	file_google_internal_cloud_code_v1internal_credits_proto_rawDescOnce sync.Once
	file_google_internal_cloud_code_v1internal_credits_proto_rawDescData []byte
)

func file_google_internal_cloud_code_v1internal_credits_proto_rawDescGZIP() []byte {
	file_google_internal_cloud_code_v1internal_credits_proto_rawDescOnce.Do(func() {
		file_google_internal_cloud_code_v1internal_credits_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_google_internal_cloud_code_v1internal_credits_proto_rawDesc), len(file_google_internal_cloud_code_v1internal_credits_proto_rawDesc)))
	})
	return file_google_internal_cloud_code_v1internal_credits_proto_rawDescData
}

var file_google_internal_cloud_code_v1internal_credits_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_google_internal_cloud_code_v1internal_credits_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_google_internal_cloud_code_v1internal_credits_proto_goTypes = []any{
	(Credits_CreditType)(0), // 0: google.internal.cloud.code.v1internal.Credits.CreditType
	(*Credits)(nil),         // 1: google.internal.cloud.code.v1internal.Credits
}
var file_google_internal_cloud_code_v1internal_credits_proto_depIdxs = []int32{
	0, // 0: google.internal.cloud.code.v1internal.Credits.credit_type:type_name -> google.internal.cloud.code.v1internal.Credits.CreditType
	1, // [1:1] is the sub-list for method output_type
	1, // [1:1] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_google_internal_cloud_code_v1internal_credits_proto_init() }
func file_google_internal_cloud_code_v1internal_credits_proto_init() {
	if File_google_internal_cloud_code_v1internal_credits_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_google_internal_cloud_code_v1internal_credits_proto_rawDesc), len(file_google_internal_cloud_code_v1internal_credits_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_google_internal_cloud_code_v1internal_credits_proto_goTypes,
		DependencyIndexes: file_google_internal_cloud_code_v1internal_credits_proto_depIdxs,
		EnumInfos:         file_google_internal_cloud_code_v1internal_credits_proto_enumTypes,
		MessageInfos:      file_google_internal_cloud_code_v1internal_credits_proto_msgTypes,
	}.Build()
	File_google_internal_cloud_code_v1internal_credits_proto = out.File
	file_google_internal_cloud_code_v1internal_credits_proto_goTypes = nil
	file_google_internal_cloud_code_v1internal_credits_proto_depIdxs = nil
}
