// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v4.25.1
// source: google/internal/cloud/code/v1internal/metrics.proto

package v1internal

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	durationpb "google.golang.org/protobuf/types/known/durationpb"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ActionStatus int32

const (
	ActionStatus_ACTION_STATUS_UNSPECIFIED   ActionStatus = 0
	ActionStatus_ACTION_STATUS_NO_ERROR      ActionStatus = 1
	ActionStatus_ACTION_STATUS_ERROR_UNKNOWN ActionStatus = 2
	ActionStatus_ACTION_STATUS_CANCELLED     ActionStatus = 3
	ActionStatus_ACTION_STATUS_EMPTY         ActionStatus = 4
)

// Enum value maps for ActionStatus.
var (
	ActionStatus_name = map[int32]string{
		0: "ACTION_STATUS_UNSPECIFIED",
		1: "ACTION_STATUS_NO_ERROR",
		2: "ACTION_STATUS_ERROR_UNKNOWN",
		3: "ACTION_STATUS_CANCELLED",
		4: "ACTION_STATUS_EMPTY",
	}
	ActionStatus_value = map[string]int32{
		"ACTION_STATUS_UNSPECIFIED":   0,
		"ACTION_STATUS_NO_ERROR":      1,
		"ACTION_STATUS_ERROR_UNKNOWN": 2,
		"ACTION_STATUS_CANCELLED":     3,
		"ACTION_STATUS_EMPTY":         4,
	}
)

func (x ActionStatus) Enum() *ActionStatus {
	p := new(ActionStatus)
	*p = x
	return p
}

func (x ActionStatus) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (ActionStatus) Descriptor() protoreflect.EnumDescriptor {
	return file_google_internal_cloud_code_v1internal_metrics_proto_enumTypes[0].Descriptor()
}

func (ActionStatus) Type() protoreflect.EnumType {
	return &file_google_internal_cloud_code_v1internal_metrics_proto_enumTypes[0]
}

func (x ActionStatus) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use ActionStatus.Descriptor instead.
func (ActionStatus) EnumDescriptor() ([]byte, []int) {
	return file_google_internal_cloud_code_v1internal_metrics_proto_rawDescGZIP(), []int{0}
}

type InlineCompletionAccepted_CompletionMethod int32

const (
	InlineCompletionAccepted_UNKNOWN              InlineCompletionAccepted_CompletionMethod = 0
	InlineCompletionAccepted_GENERATE_CODE        InlineCompletionAccepted_CompletionMethod = 1
	InlineCompletionAccepted_COMPLETE_CODE        InlineCompletionAccepted_CompletionMethod = 2
	InlineCompletionAccepted_TRANSFORM_CODE       InlineCompletionAccepted_CompletionMethod = 3
	InlineCompletionAccepted_AUTOMATIC_GENERATION InlineCompletionAccepted_CompletionMethod = 4
)

// Enum value maps for InlineCompletionAccepted_CompletionMethod.
var (
	InlineCompletionAccepted_CompletionMethod_name = map[int32]string{
		0: "UNKNOWN",
		1: "GENERATE_CODE",
		2: "COMPLETE_CODE",
		3: "TRANSFORM_CODE",
		4: "AUTOMATIC_GENERATION",
	}
	InlineCompletionAccepted_CompletionMethod_value = map[string]int32{
		"UNKNOWN":              0,
		"GENERATE_CODE":        1,
		"COMPLETE_CODE":        2,
		"TRANSFORM_CODE":       3,
		"AUTOMATIC_GENERATION": 4,
	}
)

func (x InlineCompletionAccepted_CompletionMethod) Enum() *InlineCompletionAccepted_CompletionMethod {
	p := new(InlineCompletionAccepted_CompletionMethod)
	*p = x
	return p
}

func (x InlineCompletionAccepted_CompletionMethod) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (InlineCompletionAccepted_CompletionMethod) Descriptor() protoreflect.EnumDescriptor {
	return file_google_internal_cloud_code_v1internal_metrics_proto_enumTypes[1].Descriptor()
}

func (InlineCompletionAccepted_CompletionMethod) Type() protoreflect.EnumType {
	return &file_google_internal_cloud_code_v1internal_metrics_proto_enumTypes[1]
}

func (x InlineCompletionAccepted_CompletionMethod) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use InlineCompletionAccepted_CompletionMethod.Descriptor instead.
func (InlineCompletionAccepted_CompletionMethod) EnumDescriptor() ([]byte, []int) {
	return file_google_internal_cloud_code_v1internal_metrics_proto_rawDescGZIP(), []int{3, 0}
}

type InlineCompletionOffered_CompletionMode int32

const (
	InlineCompletionOffered_UNKNOWN          InlineCompletionOffered_CompletionMode = 0
	InlineCompletionOffered_LANGUAGE_CLIENT  InlineCompletionOffered_CompletionMode = 1
	InlineCompletionOffered_TYPEOVER         InlineCompletionOffered_CompletionMode = 2
	InlineCompletionOffered_TYPEOVER_NEWLINE InlineCompletionOffered_CompletionMode = 3
	InlineCompletionOffered_TRANSFORM_CODE   InlineCompletionOffered_CompletionMode = 4
)

// Enum value maps for InlineCompletionOffered_CompletionMode.
var (
	InlineCompletionOffered_CompletionMode_name = map[int32]string{
		0: "UNKNOWN",
		1: "LANGUAGE_CLIENT",
		2: "TYPEOVER",
		3: "TYPEOVER_NEWLINE",
		4: "TRANSFORM_CODE",
	}
	InlineCompletionOffered_CompletionMode_value = map[string]int32{
		"UNKNOWN":          0,
		"LANGUAGE_CLIENT":  1,
		"TYPEOVER":         2,
		"TYPEOVER_NEWLINE": 3,
		"TRANSFORM_CODE":   4,
	}
)

func (x InlineCompletionOffered_CompletionMode) Enum() *InlineCompletionOffered_CompletionMode {
	p := new(InlineCompletionOffered_CompletionMode)
	*p = x
	return p
}

func (x InlineCompletionOffered_CompletionMode) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (InlineCompletionOffered_CompletionMode) Descriptor() protoreflect.EnumDescriptor {
	return file_google_internal_cloud_code_v1internal_metrics_proto_enumTypes[2].Descriptor()
}

func (InlineCompletionOffered_CompletionMode) Type() protoreflect.EnumType {
	return &file_google_internal_cloud_code_v1internal_metrics_proto_enumTypes[2]
}

func (x InlineCompletionOffered_CompletionMode) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use InlineCompletionOffered_CompletionMode.Descriptor instead.
func (InlineCompletionOffered_CompletionMode) EnumDescriptor() ([]byte, []int) {
	return file_google_internal_cloud_code_v1internal_metrics_proto_rawDescGZIP(), []int{4, 0}
}

type InlineCompletionOffered_CompletionMethod int32

const (
	InlineCompletionOffered_COMPLETION_METHOD_UNKNOWN              InlineCompletionOffered_CompletionMethod = 0
	InlineCompletionOffered_COMPLETION_METHOD_GENERATE_CODE        InlineCompletionOffered_CompletionMethod = 1
	InlineCompletionOffered_COMPLETION_METHOD_COMPLETE_CODE        InlineCompletionOffered_CompletionMethod = 2
	InlineCompletionOffered_COMPLETION_METHOD_TRANSFORM_CODE       InlineCompletionOffered_CompletionMethod = 3
	InlineCompletionOffered_COMPLETION_METHOD_AUTOMATIC_GENERATION InlineCompletionOffered_CompletionMethod = 4
)

// Enum value maps for InlineCompletionOffered_CompletionMethod.
var (
	InlineCompletionOffered_CompletionMethod_name = map[int32]string{
		0: "COMPLETION_METHOD_UNKNOWN",
		1: "COMPLETION_METHOD_GENERATE_CODE",
		2: "COMPLETION_METHOD_COMPLETE_CODE",
		3: "COMPLETION_METHOD_TRANSFORM_CODE",
		4: "COMPLETION_METHOD_AUTOMATIC_GENERATION",
	}
	InlineCompletionOffered_CompletionMethod_value = map[string]int32{
		"COMPLETION_METHOD_UNKNOWN":              0,
		"COMPLETION_METHOD_GENERATE_CODE":        1,
		"COMPLETION_METHOD_COMPLETE_CODE":        2,
		"COMPLETION_METHOD_TRANSFORM_CODE":       3,
		"COMPLETION_METHOD_AUTOMATIC_GENERATION": 4,
	}
)

func (x InlineCompletionOffered_CompletionMethod) Enum() *InlineCompletionOffered_CompletionMethod {
	p := new(InlineCompletionOffered_CompletionMethod)
	*p = x
	return p
}

func (x InlineCompletionOffered_CompletionMethod) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (InlineCompletionOffered_CompletionMethod) Descriptor() protoreflect.EnumDescriptor {
	return file_google_internal_cloud_code_v1internal_metrics_proto_enumTypes[3].Descriptor()
}

func (InlineCompletionOffered_CompletionMethod) Type() protoreflect.EnumType {
	return &file_google_internal_cloud_code_v1internal_metrics_proto_enumTypes[3]
}

func (x InlineCompletionOffered_CompletionMethod) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use InlineCompletionOffered_CompletionMethod.Descriptor instead.
func (InlineCompletionOffered_CompletionMethod) EnumDescriptor() ([]byte, []int) {
	return file_google_internal_cloud_code_v1internal_metrics_proto_rawDescGZIP(), []int{4, 1}
}

type ConversationOffered_InitiationMethod int32

const (
	ConversationOffered_INITIATION_METHOD_UNSPECIFIED ConversationOffered_InitiationMethod = 0
	ConversationOffered_TAB                           ConversationOffered_InitiationMethod = 1
	ConversationOffered_COMMAND                       ConversationOffered_InitiationMethod = 2
	ConversationOffered_AGENT                         ConversationOffered_InitiationMethod = 3
)

// Enum value maps for ConversationOffered_InitiationMethod.
var (
	ConversationOffered_InitiationMethod_name = map[int32]string{
		0: "INITIATION_METHOD_UNSPECIFIED",
		1: "TAB",
		2: "COMMAND",
		3: "AGENT",
	}
	ConversationOffered_InitiationMethod_value = map[string]int32{
		"INITIATION_METHOD_UNSPECIFIED": 0,
		"TAB":                           1,
		"COMMAND":                       2,
		"AGENT":                         3,
	}
)

func (x ConversationOffered_InitiationMethod) Enum() *ConversationOffered_InitiationMethod {
	p := new(ConversationOffered_InitiationMethod)
	*p = x
	return p
}

func (x ConversationOffered_InitiationMethod) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (ConversationOffered_InitiationMethod) Descriptor() protoreflect.EnumDescriptor {
	return file_google_internal_cloud_code_v1internal_metrics_proto_enumTypes[4].Descriptor()
}

func (ConversationOffered_InitiationMethod) Type() protoreflect.EnumType {
	return &file_google_internal_cloud_code_v1internal_metrics_proto_enumTypes[4]
}

func (x ConversationOffered_InitiationMethod) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use ConversationOffered_InitiationMethod.Descriptor instead.
func (ConversationOffered_InitiationMethod) EnumDescriptor() ([]byte, []int) {
	return file_google_internal_cloud_code_v1internal_metrics_proto_rawDescGZIP(), []int{5, 0}
}

type ConversationInteraction_Interaction int32

const (
	ConversationInteraction_UNKNOWN           ConversationInteraction_Interaction = 0
	ConversationInteraction_THUMBSUP          ConversationInteraction_Interaction = 1
	ConversationInteraction_THUMBSDOWN        ConversationInteraction_Interaction = 2
	ConversationInteraction_COPY              ConversationInteraction_Interaction = 3
	ConversationInteraction_INSERT            ConversationInteraction_Interaction = 4
	ConversationInteraction_ACCEPT_CODE_BLOCK ConversationInteraction_Interaction = 5
	ConversationInteraction_ACCEPT_ALL        ConversationInteraction_Interaction = 6
	ConversationInteraction_ACCEPT_FILE       ConversationInteraction_Interaction = 7
	ConversationInteraction_DIFF              ConversationInteraction_Interaction = 8
	ConversationInteraction_ACCEPT_RANGE      ConversationInteraction_Interaction = 9
)

// Enum value maps for ConversationInteraction_Interaction.
var (
	ConversationInteraction_Interaction_name = map[int32]string{
		0: "UNKNOWN",
		1: "THUMBSUP",
		2: "THUMBSDOWN",
		3: "COPY",
		4: "INSERT",
		5: "ACCEPT_CODE_BLOCK",
		6: "ACCEPT_ALL",
		7: "ACCEPT_FILE",
		8: "DIFF",
		9: "ACCEPT_RANGE",
	}
	ConversationInteraction_Interaction_value = map[string]int32{
		"UNKNOWN":           0,
		"THUMBSUP":          1,
		"THUMBSDOWN":        2,
		"COPY":              3,
		"INSERT":            4,
		"ACCEPT_CODE_BLOCK": 5,
		"ACCEPT_ALL":        6,
		"ACCEPT_FILE":       7,
		"DIFF":              8,
		"ACCEPT_RANGE":      9,
	}
)

func (x ConversationInteraction_Interaction) Enum() *ConversationInteraction_Interaction {
	p := new(ConversationInteraction_Interaction)
	*p = x
	return p
}

func (x ConversationInteraction_Interaction) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (ConversationInteraction_Interaction) Descriptor() protoreflect.EnumDescriptor {
	return file_google_internal_cloud_code_v1internal_metrics_proto_enumTypes[5].Descriptor()
}

func (ConversationInteraction_Interaction) Type() protoreflect.EnumType {
	return &file_google_internal_cloud_code_v1internal_metrics_proto_enumTypes[5]
}

func (x ConversationInteraction_Interaction) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use ConversationInteraction_Interaction.Descriptor instead.
func (ConversationInteraction_Interaction) EnumDescriptor() ([]byte, []int) {
	return file_google_internal_cloud_code_v1internal_metrics_proto_rawDescGZIP(), []int{6, 0}
}

type AiCharactersReport_EditType int32

const (
	AiCharactersReport_EDIT_TYPE_UNSPECIFIED AiCharactersReport_EditType = 0
	AiCharactersReport_USER_ADD              AiCharactersReport_EditType = 1
	AiCharactersReport_PASTE                 AiCharactersReport_EditType = 2
	AiCharactersReport_DELETE                AiCharactersReport_EditType = 3
	AiCharactersReport_OTHER                 AiCharactersReport_EditType = 4
	AiCharactersReport_AI_COMPLETION         AiCharactersReport_EditType = 5
	AiCharactersReport_AI_COMPLETION_PARTIAL AiCharactersReport_EditType = 6
	AiCharactersReport_AI_GENERATION         AiCharactersReport_EditType = 7
	AiCharactersReport_AI_GENERATION_PARTIAL AiCharactersReport_EditType = 8
)

// Enum value maps for AiCharactersReport_EditType.
var (
	AiCharactersReport_EditType_name = map[int32]string{
		0: "EDIT_TYPE_UNSPECIFIED",
		1: "USER_ADD",
		2: "PASTE",
		3: "DELETE",
		4: "OTHER",
		5: "AI_COMPLETION",
		6: "AI_COMPLETION_PARTIAL",
		7: "AI_GENERATION",
		8: "AI_GENERATION_PARTIAL",
	}
	AiCharactersReport_EditType_value = map[string]int32{
		"EDIT_TYPE_UNSPECIFIED": 0,
		"USER_ADD":              1,
		"PASTE":                 2,
		"DELETE":                3,
		"OTHER":                 4,
		"AI_COMPLETION":         5,
		"AI_COMPLETION_PARTIAL": 6,
		"AI_GENERATION":         7,
		"AI_GENERATION_PARTIAL": 8,
	}
)

func (x AiCharactersReport_EditType) Enum() *AiCharactersReport_EditType {
	p := new(AiCharactersReport_EditType)
	*p = x
	return p
}

func (x AiCharactersReport_EditType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (AiCharactersReport_EditType) Descriptor() protoreflect.EnumDescriptor {
	return file_google_internal_cloud_code_v1internal_metrics_proto_enumTypes[6].Descriptor()
}

func (AiCharactersReport_EditType) Type() protoreflect.EnumType {
	return &file_google_internal_cloud_code_v1internal_metrics_proto_enumTypes[6]
}

func (x AiCharactersReport_EditType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use AiCharactersReport_EditType.Descriptor instead.
func (AiCharactersReport_EditType) EnumDescriptor() ([]byte, []int) {
	return file_google_internal_cloud_code_v1internal_metrics_proto_rawDescGZIP(), []int{11, 0}
}

type RecordCodeAssistMetricsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Project       string                 `protobuf:"bytes,1,opt,name=project,proto3" json:"project,omitempty"`
	RequestId     string                 `protobuf:"bytes,2,opt,name=request_id,json=requestId,proto3" json:"request_id,omitempty"`
	Metadata      *ClientMetadata        `protobuf:"bytes,3,opt,name=metadata,proto3" json:"metadata,omitempty"`
	Metrics       []*CodeAssistMetric    `protobuf:"bytes,4,rep,name=metrics,proto3" json:"metrics,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RecordCodeAssistMetricsRequest) Reset() {
	*x = RecordCodeAssistMetricsRequest{}
	mi := &file_google_internal_cloud_code_v1internal_metrics_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RecordCodeAssistMetricsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RecordCodeAssistMetricsRequest) ProtoMessage() {}

func (x *RecordCodeAssistMetricsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_google_internal_cloud_code_v1internal_metrics_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RecordCodeAssistMetricsRequest.ProtoReflect.Descriptor instead.
func (*RecordCodeAssistMetricsRequest) Descriptor() ([]byte, []int) {
	return file_google_internal_cloud_code_v1internal_metrics_proto_rawDescGZIP(), []int{0}
}

func (x *RecordCodeAssistMetricsRequest) GetProject() string {
	if x != nil {
		return x.Project
	}
	return ""
}

func (x *RecordCodeAssistMetricsRequest) GetRequestId() string {
	if x != nil {
		return x.RequestId
	}
	return ""
}

func (x *RecordCodeAssistMetricsRequest) GetMetadata() *ClientMetadata {
	if x != nil {
		return x.Metadata
	}
	return nil
}

func (x *RecordCodeAssistMetricsRequest) GetMetrics() []*CodeAssistMetric {
	if x != nil {
		return x.Metrics
	}
	return nil
}

type RecordClientEventRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Project       string                 `protobuf:"bytes,1,opt,name=project,proto3" json:"project,omitempty"`
	IdeType       ClientMetadata_IdeType `protobuf:"varint,2,opt,name=ide_type,json=ideType,proto3,enum=google.internal.cloud.code.v1internal.ClientMetadata_IdeType" json:"ide_type,omitempty"`
	Metric        *CodeAssistMetric      `protobuf:"bytes,3,opt,name=metric,proto3" json:"metric,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RecordClientEventRequest) Reset() {
	*x = RecordClientEventRequest{}
	mi := &file_google_internal_cloud_code_v1internal_metrics_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RecordClientEventRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RecordClientEventRequest) ProtoMessage() {}

func (x *RecordClientEventRequest) ProtoReflect() protoreflect.Message {
	mi := &file_google_internal_cloud_code_v1internal_metrics_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RecordClientEventRequest.ProtoReflect.Descriptor instead.
func (*RecordClientEventRequest) Descriptor() ([]byte, []int) {
	return file_google_internal_cloud_code_v1internal_metrics_proto_rawDescGZIP(), []int{1}
}

func (x *RecordClientEventRequest) GetProject() string {
	if x != nil {
		return x.Project
	}
	return ""
}

func (x *RecordClientEventRequest) GetIdeType() ClientMetadata_IdeType {
	if x != nil {
		return x.IdeType
	}
	return ClientMetadata_IDE_UNSPECIFIED
}

func (x *RecordClientEventRequest) GetMetric() *CodeAssistMetric {
	if x != nil {
		return x.Metric
	}
	return nil
}

type CodeAssistMetric struct {
	state     protoimpl.MessageState `protogen:"open.v1"`
	Timestamp *timestamppb.Timestamp `protobuf:"bytes,1,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	// Types that are valid to be assigned to Event:
	//
	//	*CodeAssistMetric_InlineCompletionAccepted
	//	*CodeAssistMetric_InlineCompletionOffered
	//	*CodeAssistMetric_ConversationOffered
	//	*CodeAssistMetric_GenerateCodeUi
	//	*CodeAssistMetric_ConversationExplainUi
	//	*CodeAssistMetric_ConversationGenerateTestUi
	//	*CodeAssistMetric_ConversationInteraction
	//	*CodeAssistMetric_AiCharactersReports
	Event          isCodeAssistMetric_Event `protobuf_oneof:"event"`
	MetricMetadata map[string]string        `protobuf:"bytes,10,rep,name=metric_metadata,json=metricMetadata,proto3" json:"metric_metadata,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *CodeAssistMetric) Reset() {
	*x = CodeAssistMetric{}
	mi := &file_google_internal_cloud_code_v1internal_metrics_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CodeAssistMetric) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CodeAssistMetric) ProtoMessage() {}

func (x *CodeAssistMetric) ProtoReflect() protoreflect.Message {
	mi := &file_google_internal_cloud_code_v1internal_metrics_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CodeAssistMetric.ProtoReflect.Descriptor instead.
func (*CodeAssistMetric) Descriptor() ([]byte, []int) {
	return file_google_internal_cloud_code_v1internal_metrics_proto_rawDescGZIP(), []int{2}
}

func (x *CodeAssistMetric) GetTimestamp() *timestamppb.Timestamp {
	if x != nil {
		return x.Timestamp
	}
	return nil
}

func (x *CodeAssistMetric) GetEvent() isCodeAssistMetric_Event {
	if x != nil {
		return x.Event
	}
	return nil
}

func (x *CodeAssistMetric) GetInlineCompletionAccepted() *InlineCompletionAccepted {
	if x != nil {
		if x, ok := x.Event.(*CodeAssistMetric_InlineCompletionAccepted); ok {
			return x.InlineCompletionAccepted
		}
	}
	return nil
}

func (x *CodeAssistMetric) GetInlineCompletionOffered() *InlineCompletionOffered {
	if x != nil {
		if x, ok := x.Event.(*CodeAssistMetric_InlineCompletionOffered); ok {
			return x.InlineCompletionOffered
		}
	}
	return nil
}

func (x *CodeAssistMetric) GetConversationOffered() *ConversationOffered {
	if x != nil {
		if x, ok := x.Event.(*CodeAssistMetric_ConversationOffered); ok {
			return x.ConversationOffered
		}
	}
	return nil
}

func (x *CodeAssistMetric) GetGenerateCodeUi() *GenerateCodeUI {
	if x != nil {
		if x, ok := x.Event.(*CodeAssistMetric_GenerateCodeUi); ok {
			return x.GenerateCodeUi
		}
	}
	return nil
}

func (x *CodeAssistMetric) GetConversationExplainUi() *ConversationExplainUI {
	if x != nil {
		if x, ok := x.Event.(*CodeAssistMetric_ConversationExplainUi); ok {
			return x.ConversationExplainUi
		}
	}
	return nil
}

func (x *CodeAssistMetric) GetConversationGenerateTestUi() *ConversationGenerateTestUI {
	if x != nil {
		if x, ok := x.Event.(*CodeAssistMetric_ConversationGenerateTestUi); ok {
			return x.ConversationGenerateTestUi
		}
	}
	return nil
}

func (x *CodeAssistMetric) GetConversationInteraction() *ConversationInteraction {
	if x != nil {
		if x, ok := x.Event.(*CodeAssistMetric_ConversationInteraction); ok {
			return x.ConversationInteraction
		}
	}
	return nil
}

func (x *CodeAssistMetric) GetAiCharactersReports() *AiCharactersReports {
	if x != nil {
		if x, ok := x.Event.(*CodeAssistMetric_AiCharactersReports); ok {
			return x.AiCharactersReports
		}
	}
	return nil
}

func (x *CodeAssistMetric) GetMetricMetadata() map[string]string {
	if x != nil {
		return x.MetricMetadata
	}
	return nil
}

type isCodeAssistMetric_Event interface {
	isCodeAssistMetric_Event()
}

type CodeAssistMetric_InlineCompletionAccepted struct {
	InlineCompletionAccepted *InlineCompletionAccepted `protobuf:"bytes,2,opt,name=inline_completion_accepted,json=inlineCompletionAccepted,proto3,oneof"`
}

type CodeAssistMetric_InlineCompletionOffered struct {
	InlineCompletionOffered *InlineCompletionOffered `protobuf:"bytes,3,opt,name=inline_completion_offered,json=inlineCompletionOffered,proto3,oneof"`
}

type CodeAssistMetric_ConversationOffered struct {
	ConversationOffered *ConversationOffered `protobuf:"bytes,4,opt,name=conversation_offered,json=conversationOffered,proto3,oneof"`
}

type CodeAssistMetric_GenerateCodeUi struct {
	GenerateCodeUi *GenerateCodeUI `protobuf:"bytes,5,opt,name=generate_code_ui,json=generateCodeUi,proto3,oneof"`
}

type CodeAssistMetric_ConversationExplainUi struct {
	ConversationExplainUi *ConversationExplainUI `protobuf:"bytes,6,opt,name=conversation_explain_ui,json=conversationExplainUi,proto3,oneof"`
}

type CodeAssistMetric_ConversationGenerateTestUi struct {
	ConversationGenerateTestUi *ConversationGenerateTestUI `protobuf:"bytes,7,opt,name=conversation_generate_test_ui,json=conversationGenerateTestUi,proto3,oneof"`
}

type CodeAssistMetric_ConversationInteraction struct {
	ConversationInteraction *ConversationInteraction `protobuf:"bytes,8,opt,name=conversation_interaction,json=conversationInteraction,proto3,oneof"`
}

type CodeAssistMetric_AiCharactersReports struct {
	AiCharactersReports *AiCharactersReports `protobuf:"bytes,9,opt,name=ai_characters_reports,json=aiCharactersReports,proto3,oneof"`
}

func (*CodeAssistMetric_InlineCompletionAccepted) isCodeAssistMetric_Event() {}

func (*CodeAssistMetric_InlineCompletionOffered) isCodeAssistMetric_Event() {}

func (*CodeAssistMetric_ConversationOffered) isCodeAssistMetric_Event() {}

func (*CodeAssistMetric_GenerateCodeUi) isCodeAssistMetric_Event() {}

func (*CodeAssistMetric_ConversationExplainUi) isCodeAssistMetric_Event() {}

func (*CodeAssistMetric_ConversationGenerateTestUi) isCodeAssistMetric_Event() {}

func (*CodeAssistMetric_ConversationInteraction) isCodeAssistMetric_Event() {}

func (*CodeAssistMetric_AiCharactersReports) isCodeAssistMetric_Event() {}

type InlineCompletionAccepted struct {
	state                     protoimpl.MessageState                    `protogen:"open.v1"`
	TraceId                   string                                    `protobuf:"bytes,1,opt,name=trace_id,json=traceId,proto3" json:"trace_id,omitempty"`
	Score                     float32                                   `protobuf:"fixed32,2,opt,name=score,proto3" json:"score,omitempty"`
	ResponseSize              int64                                     `protobuf:"varint,3,opt,name=response_size,json=responseSize,proto3" json:"response_size,omitempty"`
	ResponseLines             int64                                     `protobuf:"varint,4,opt,name=response_lines,json=responseLines,proto3" json:"response_lines,omitempty"`
	Language                  string                                    `protobuf:"bytes,5,opt,name=language,proto3" json:"language,omitempty"`
	CompletionMethod          InlineCompletionAccepted_CompletionMethod `protobuf:"varint,6,opt,name=completion_method,json=completionMethod,proto3,enum=google.internal.cloud.code.v1internal.InlineCompletionAccepted_CompletionMethod" json:"completion_method,omitempty"`
	PartialAcceptedCharacters *int64                                    `protobuf:"varint,7,opt,name=partial_accepted_characters,json=partialAcceptedCharacters,proto3,oneof" json:"partial_accepted_characters,omitempty"`
	PartialAcceptedLines      *int64                                    `protobuf:"varint,8,opt,name=partial_accepted_lines,json=partialAcceptedLines,proto3,oneof" json:"partial_accepted_lines,omitempty"`
	Status                    ActionStatus                              `protobuf:"varint,9,opt,name=status,proto3,enum=google.internal.cloud.code.v1internal.ActionStatus" json:"status,omitempty"`
	AcceptedCommentLines      *int64                                    `protobuf:"varint,10,opt,name=accepted_comment_lines,json=acceptedCommentLines,proto3,oneof" json:"accepted_comment_lines,omitempty"`
	ResponseAcceptedIndex     int64                                     `protobuf:"varint,11,opt,name=response_accepted_index,json=responseAcceptedIndex,proto3" json:"response_accepted_index,omitempty"`
	unknownFields             protoimpl.UnknownFields
	sizeCache                 protoimpl.SizeCache
}

func (x *InlineCompletionAccepted) Reset() {
	*x = InlineCompletionAccepted{}
	mi := &file_google_internal_cloud_code_v1internal_metrics_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *InlineCompletionAccepted) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*InlineCompletionAccepted) ProtoMessage() {}

func (x *InlineCompletionAccepted) ProtoReflect() protoreflect.Message {
	mi := &file_google_internal_cloud_code_v1internal_metrics_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use InlineCompletionAccepted.ProtoReflect.Descriptor instead.
func (*InlineCompletionAccepted) Descriptor() ([]byte, []int) {
	return file_google_internal_cloud_code_v1internal_metrics_proto_rawDescGZIP(), []int{3}
}

func (x *InlineCompletionAccepted) GetTraceId() string {
	if x != nil {
		return x.TraceId
	}
	return ""
}

func (x *InlineCompletionAccepted) GetScore() float32 {
	if x != nil {
		return x.Score
	}
	return 0
}

func (x *InlineCompletionAccepted) GetResponseSize() int64 {
	if x != nil {
		return x.ResponseSize
	}
	return 0
}

func (x *InlineCompletionAccepted) GetResponseLines() int64 {
	if x != nil {
		return x.ResponseLines
	}
	return 0
}

func (x *InlineCompletionAccepted) GetLanguage() string {
	if x != nil {
		return x.Language
	}
	return ""
}

func (x *InlineCompletionAccepted) GetCompletionMethod() InlineCompletionAccepted_CompletionMethod {
	if x != nil {
		return x.CompletionMethod
	}
	return InlineCompletionAccepted_UNKNOWN
}

func (x *InlineCompletionAccepted) GetPartialAcceptedCharacters() int64 {
	if x != nil && x.PartialAcceptedCharacters != nil {
		return *x.PartialAcceptedCharacters
	}
	return 0
}

func (x *InlineCompletionAccepted) GetPartialAcceptedLines() int64 {
	if x != nil && x.PartialAcceptedLines != nil {
		return *x.PartialAcceptedLines
	}
	return 0
}

func (x *InlineCompletionAccepted) GetStatus() ActionStatus {
	if x != nil {
		return x.Status
	}
	return ActionStatus_ACTION_STATUS_UNSPECIFIED
}

func (x *InlineCompletionAccepted) GetAcceptedCommentLines() int64 {
	if x != nil && x.AcceptedCommentLines != nil {
		return *x.AcceptedCommentLines
	}
	return 0
}

func (x *InlineCompletionAccepted) GetResponseAcceptedIndex() int64 {
	if x != nil {
		return x.ResponseAcceptedIndex
	}
	return 0
}

type InlineCompletionOffered struct {
	state                 protoimpl.MessageState                   `protogen:"open.v1"`
	TraceId               string                                   `protobuf:"bytes,1,opt,name=trace_id,json=traceId,proto3" json:"trace_id,omitempty"`
	ResultCount           int64                                    `protobuf:"varint,2,opt,name=result_count,json=resultCount,proto3" json:"result_count,omitempty"`
	Language              string                                   `protobuf:"bytes,3,opt,name=language,proto3" json:"language,omitempty"`
	CompletionMode        InlineCompletionOffered_CompletionMode   `protobuf:"varint,4,opt,name=completion_mode,json=completionMode,proto3,enum=google.internal.cloud.code.v1internal.InlineCompletionOffered_CompletionMode" json:"completion_mode,omitempty"`
	DisplayLength         *durationpb.Duration                     `protobuf:"bytes,5,opt,name=display_length,json=displayLength,proto3" json:"display_length,omitempty"`
	Status                ActionStatus                             `protobuf:"varint,6,opt,name=status,proto3,enum=google.internal.cloud.code.v1internal.ActionStatus" json:"status,omitempty"`
	CompletionMethod      InlineCompletionOffered_CompletionMethod `protobuf:"varint,7,opt,name=completion_method,json=completionMethod,proto3,enum=google.internal.cloud.code.v1internal.InlineCompletionOffered_CompletionMethod" json:"completion_method,omitempty"`
	ResponseLatency       *durationpb.Duration                     `protobuf:"bytes,8,opt,name=response_latency,json=responseLatency,proto3" json:"response_latency,omitempty"`
	ResponseReceivedIndex int64                                    `protobuf:"varint,9,opt,name=response_received_index,json=responseReceivedIndex,proto3" json:"response_received_index,omitempty"`
	unknownFields         protoimpl.UnknownFields
	sizeCache             protoimpl.SizeCache
}

func (x *InlineCompletionOffered) Reset() {
	*x = InlineCompletionOffered{}
	mi := &file_google_internal_cloud_code_v1internal_metrics_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *InlineCompletionOffered) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*InlineCompletionOffered) ProtoMessage() {}

func (x *InlineCompletionOffered) ProtoReflect() protoreflect.Message {
	mi := &file_google_internal_cloud_code_v1internal_metrics_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use InlineCompletionOffered.ProtoReflect.Descriptor instead.
func (*InlineCompletionOffered) Descriptor() ([]byte, []int) {
	return file_google_internal_cloud_code_v1internal_metrics_proto_rawDescGZIP(), []int{4}
}

func (x *InlineCompletionOffered) GetTraceId() string {
	if x != nil {
		return x.TraceId
	}
	return ""
}

func (x *InlineCompletionOffered) GetResultCount() int64 {
	if x != nil {
		return x.ResultCount
	}
	return 0
}

func (x *InlineCompletionOffered) GetLanguage() string {
	if x != nil {
		return x.Language
	}
	return ""
}

func (x *InlineCompletionOffered) GetCompletionMode() InlineCompletionOffered_CompletionMode {
	if x != nil {
		return x.CompletionMode
	}
	return InlineCompletionOffered_UNKNOWN
}

func (x *InlineCompletionOffered) GetDisplayLength() *durationpb.Duration {
	if x != nil {
		return x.DisplayLength
	}
	return nil
}

func (x *InlineCompletionOffered) GetStatus() ActionStatus {
	if x != nil {
		return x.Status
	}
	return ActionStatus_ACTION_STATUS_UNSPECIFIED
}

func (x *InlineCompletionOffered) GetCompletionMethod() InlineCompletionOffered_CompletionMethod {
	if x != nil {
		return x.CompletionMethod
	}
	return InlineCompletionOffered_COMPLETION_METHOD_UNKNOWN
}

func (x *InlineCompletionOffered) GetResponseLatency() *durationpb.Duration {
	if x != nil {
		return x.ResponseLatency
	}
	return nil
}

func (x *InlineCompletionOffered) GetResponseReceivedIndex() int64 {
	if x != nil {
		return x.ResponseReceivedIndex
	}
	return 0
}

type ConversationOffered struct {
	state            protoimpl.MessageState                `protogen:"open.v1"`
	CitationCount    int64                                 `protobuf:"varint,1,opt,name=citation_count,json=citationCount,proto3" json:"citation_count,omitempty"`
	IncludedCode     bool                                  `protobuf:"varint,2,opt,name=included_code,json=includedCode,proto3" json:"included_code,omitempty"`
	Status           ActionStatus                          `protobuf:"varint,3,opt,name=status,proto3,enum=google.internal.cloud.code.v1internal.ActionStatus" json:"status,omitempty"`
	TraceId          string                                `protobuf:"bytes,4,opt,name=trace_id,json=traceId,proto3" json:"trace_id,omitempty"`
	StreamingLatency *ConversationOffered_StreamingLatency `protobuf:"bytes,5,opt,name=streaming_latency,json=streamingLatency,proto3" json:"streaming_latency,omitempty"`
	IsAgentic        bool                                  `protobuf:"varint,6,opt,name=is_agentic,json=isAgentic,proto3" json:"is_agentic,omitempty"`
	InitiationMethod ConversationOffered_InitiationMethod  `protobuf:"varint,7,opt,name=initiation_method,json=initiationMethod,proto3,enum=google.internal.cloud.code.v1internal.ConversationOffered_InitiationMethod" json:"initiation_method,omitempty"`
	TrajectoryId     string                                `protobuf:"bytes,8,opt,name=trajectory_id,json=trajectoryId,proto3" json:"trajectory_id,omitempty"`
	Language         *string                               `protobuf:"bytes,9,opt,name=language,proto3,oneof" json:"language,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *ConversationOffered) Reset() {
	*x = ConversationOffered{}
	mi := &file_google_internal_cloud_code_v1internal_metrics_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ConversationOffered) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ConversationOffered) ProtoMessage() {}

func (x *ConversationOffered) ProtoReflect() protoreflect.Message {
	mi := &file_google_internal_cloud_code_v1internal_metrics_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ConversationOffered.ProtoReflect.Descriptor instead.
func (*ConversationOffered) Descriptor() ([]byte, []int) {
	return file_google_internal_cloud_code_v1internal_metrics_proto_rawDescGZIP(), []int{5}
}

func (x *ConversationOffered) GetCitationCount() int64 {
	if x != nil {
		return x.CitationCount
	}
	return 0
}

func (x *ConversationOffered) GetIncludedCode() bool {
	if x != nil {
		return x.IncludedCode
	}
	return false
}

func (x *ConversationOffered) GetStatus() ActionStatus {
	if x != nil {
		return x.Status
	}
	return ActionStatus_ACTION_STATUS_UNSPECIFIED
}

func (x *ConversationOffered) GetTraceId() string {
	if x != nil {
		return x.TraceId
	}
	return ""
}

func (x *ConversationOffered) GetStreamingLatency() *ConversationOffered_StreamingLatency {
	if x != nil {
		return x.StreamingLatency
	}
	return nil
}

func (x *ConversationOffered) GetIsAgentic() bool {
	if x != nil {
		return x.IsAgentic
	}
	return false
}

func (x *ConversationOffered) GetInitiationMethod() ConversationOffered_InitiationMethod {
	if x != nil {
		return x.InitiationMethod
	}
	return ConversationOffered_INITIATION_METHOD_UNSPECIFIED
}

func (x *ConversationOffered) GetTrajectoryId() string {
	if x != nil {
		return x.TrajectoryId
	}
	return ""
}

func (x *ConversationOffered) GetLanguage() string {
	if x != nil && x.Language != nil {
		return *x.Language
	}
	return ""
}

type ConversationInteraction struct {
	state            protoimpl.MessageState               `protogen:"open.v1"`
	TraceId          string                               `protobuf:"bytes,1,opt,name=trace_id,json=traceId,proto3" json:"trace_id,omitempty"`
	Status           ActionStatus                         `protobuf:"varint,2,opt,name=status,proto3,enum=google.internal.cloud.code.v1internal.ActionStatus" json:"status,omitempty"`
	Interaction      ConversationInteraction_Interaction  `protobuf:"varint,3,opt,name=interaction,proto3,enum=google.internal.cloud.code.v1internal.ConversationInteraction_Interaction" json:"interaction,omitempty"`
	AcceptedLines    *int64                               `protobuf:"varint,4,opt,name=accepted_lines,json=acceptedLines,proto3,oneof" json:"accepted_lines,omitempty"`
	Language         *string                              `protobuf:"bytes,5,opt,name=language,proto3,oneof" json:"language,omitempty"`
	IsAgentic        bool                                 `protobuf:"varint,6,opt,name=is_agentic,json=isAgentic,proto3" json:"is_agentic,omitempty"`
	RemovedLines     *int64                               `protobuf:"varint,7,opt,name=removed_lines,json=removedLines,proto3,oneof" json:"removed_lines,omitempty"`
	InitiationMethod ConversationOffered_InitiationMethod `protobuf:"varint,8,opt,name=initiation_method,json=initiationMethod,proto3,enum=google.internal.cloud.code.v1internal.ConversationOffered_InitiationMethod" json:"initiation_method,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *ConversationInteraction) Reset() {
	*x = ConversationInteraction{}
	mi := &file_google_internal_cloud_code_v1internal_metrics_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ConversationInteraction) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ConversationInteraction) ProtoMessage() {}

func (x *ConversationInteraction) ProtoReflect() protoreflect.Message {
	mi := &file_google_internal_cloud_code_v1internal_metrics_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ConversationInteraction.ProtoReflect.Descriptor instead.
func (*ConversationInteraction) Descriptor() ([]byte, []int) {
	return file_google_internal_cloud_code_v1internal_metrics_proto_rawDescGZIP(), []int{6}
}

func (x *ConversationInteraction) GetTraceId() string {
	if x != nil {
		return x.TraceId
	}
	return ""
}

func (x *ConversationInteraction) GetStatus() ActionStatus {
	if x != nil {
		return x.Status
	}
	return ActionStatus_ACTION_STATUS_UNSPECIFIED
}

func (x *ConversationInteraction) GetInteraction() ConversationInteraction_Interaction {
	if x != nil {
		return x.Interaction
	}
	return ConversationInteraction_UNKNOWN
}

func (x *ConversationInteraction) GetAcceptedLines() int64 {
	if x != nil && x.AcceptedLines != nil {
		return *x.AcceptedLines
	}
	return 0
}

func (x *ConversationInteraction) GetLanguage() string {
	if x != nil && x.Language != nil {
		return *x.Language
	}
	return ""
}

func (x *ConversationInteraction) GetIsAgentic() bool {
	if x != nil {
		return x.IsAgentic
	}
	return false
}

func (x *ConversationInteraction) GetRemovedLines() int64 {
	if x != nil && x.RemovedLines != nil {
		return *x.RemovedLines
	}
	return 0
}

func (x *ConversationInteraction) GetInitiationMethod() ConversationOffered_InitiationMethod {
	if x != nil {
		return x.InitiationMethod
	}
	return ConversationOffered_INITIATION_METHOD_UNSPECIFIED
}

type GenerateCodeUI struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GenerateCodeUI) Reset() {
	*x = GenerateCodeUI{}
	mi := &file_google_internal_cloud_code_v1internal_metrics_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GenerateCodeUI) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GenerateCodeUI) ProtoMessage() {}

func (x *GenerateCodeUI) ProtoReflect() protoreflect.Message {
	mi := &file_google_internal_cloud_code_v1internal_metrics_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GenerateCodeUI.ProtoReflect.Descriptor instead.
func (*GenerateCodeUI) Descriptor() ([]byte, []int) {
	return file_google_internal_cloud_code_v1internal_metrics_proto_rawDescGZIP(), []int{7}
}

type ConversationExplainUI struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ConversationExplainUI) Reset() {
	*x = ConversationExplainUI{}
	mi := &file_google_internal_cloud_code_v1internal_metrics_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ConversationExplainUI) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ConversationExplainUI) ProtoMessage() {}

func (x *ConversationExplainUI) ProtoReflect() protoreflect.Message {
	mi := &file_google_internal_cloud_code_v1internal_metrics_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ConversationExplainUI.ProtoReflect.Descriptor instead.
func (*ConversationExplainUI) Descriptor() ([]byte, []int) {
	return file_google_internal_cloud_code_v1internal_metrics_proto_rawDescGZIP(), []int{8}
}

type ConversationGenerateTestUI struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ConversationGenerateTestUI) Reset() {
	*x = ConversationGenerateTestUI{}
	mi := &file_google_internal_cloud_code_v1internal_metrics_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ConversationGenerateTestUI) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ConversationGenerateTestUI) ProtoMessage() {}

func (x *ConversationGenerateTestUI) ProtoReflect() protoreflect.Message {
	mi := &file_google_internal_cloud_code_v1internal_metrics_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ConversationGenerateTestUI.ProtoReflect.Descriptor instead.
func (*ConversationGenerateTestUI) Descriptor() ([]byte, []int) {
	return file_google_internal_cloud_code_v1internal_metrics_proto_rawDescGZIP(), []int{9}
}

type AiCharactersReports struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Reports       []*AiCharactersReport  `protobuf:"bytes,1,rep,name=reports,proto3" json:"reports,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AiCharactersReports) Reset() {
	*x = AiCharactersReports{}
	mi := &file_google_internal_cloud_code_v1internal_metrics_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AiCharactersReports) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AiCharactersReports) ProtoMessage() {}

func (x *AiCharactersReports) ProtoReflect() protoreflect.Message {
	mi := &file_google_internal_cloud_code_v1internal_metrics_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AiCharactersReports.ProtoReflect.Descriptor instead.
func (*AiCharactersReports) Descriptor() ([]byte, []int) {
	return file_google_internal_cloud_code_v1internal_metrics_proto_rawDescGZIP(), []int{10}
}

func (x *AiCharactersReports) GetReports() []*AiCharactersReport {
	if x != nil {
		return x.Reports
	}
	return nil
}

type AiCharactersReport struct {
	state             protoimpl.MessageState      `protogen:"open.v1"`
	Language          string                      `protobuf:"bytes,1,opt,name=language,proto3" json:"language,omitempty"`
	EditType          AiCharactersReport_EditType `protobuf:"varint,2,opt,name=edit_type,json=editType,proto3,enum=google.internal.cloud.code.v1internal.AiCharactersReport_EditType" json:"edit_type,omitempty"`
	TotalChars        int64                       `protobuf:"varint,3,opt,name=total_chars,json=totalChars,proto3" json:"total_chars,omitempty"`
	WhitespaceChars   int64                       `protobuf:"varint,4,opt,name=whitespace_chars,json=whitespaceChars,proto3" json:"whitespace_chars,omitempty"`
	TimeIntervalIndex int64                       `protobuf:"varint,5,opt,name=time_interval_index,json=timeIntervalIndex,proto3" json:"time_interval_index,omitempty"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *AiCharactersReport) Reset() {
	*x = AiCharactersReport{}
	mi := &file_google_internal_cloud_code_v1internal_metrics_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AiCharactersReport) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AiCharactersReport) ProtoMessage() {}

func (x *AiCharactersReport) ProtoReflect() protoreflect.Message {
	mi := &file_google_internal_cloud_code_v1internal_metrics_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AiCharactersReport.ProtoReflect.Descriptor instead.
func (*AiCharactersReport) Descriptor() ([]byte, []int) {
	return file_google_internal_cloud_code_v1internal_metrics_proto_rawDescGZIP(), []int{11}
}

func (x *AiCharactersReport) GetLanguage() string {
	if x != nil {
		return x.Language
	}
	return ""
}

func (x *AiCharactersReport) GetEditType() AiCharactersReport_EditType {
	if x != nil {
		return x.EditType
	}
	return AiCharactersReport_EDIT_TYPE_UNSPECIFIED
}

func (x *AiCharactersReport) GetTotalChars() int64 {
	if x != nil {
		return x.TotalChars
	}
	return 0
}

func (x *AiCharactersReport) GetWhitespaceChars() int64 {
	if x != nil {
		return x.WhitespaceChars
	}
	return 0
}

func (x *AiCharactersReport) GetTimeIntervalIndex() int64 {
	if x != nil {
		return x.TimeIntervalIndex
	}
	return 0
}

type ConversationOffered_StreamingLatency struct {
	state               protoimpl.MessageState `protogen:"open.v1"`
	FirstMessageLatency *durationpb.Duration   `protobuf:"bytes,1,opt,name=first_message_latency,json=firstMessageLatency,proto3,oneof" json:"first_message_latency,omitempty"`
	TotalLatency        *durationpb.Duration   `protobuf:"bytes,2,opt,name=total_latency,json=totalLatency,proto3,oneof" json:"total_latency,omitempty"`
	unknownFields       protoimpl.UnknownFields
	sizeCache           protoimpl.SizeCache
}

func (x *ConversationOffered_StreamingLatency) Reset() {
	*x = ConversationOffered_StreamingLatency{}
	mi := &file_google_internal_cloud_code_v1internal_metrics_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ConversationOffered_StreamingLatency) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ConversationOffered_StreamingLatency) ProtoMessage() {}

func (x *ConversationOffered_StreamingLatency) ProtoReflect() protoreflect.Message {
	mi := &file_google_internal_cloud_code_v1internal_metrics_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ConversationOffered_StreamingLatency.ProtoReflect.Descriptor instead.
func (*ConversationOffered_StreamingLatency) Descriptor() ([]byte, []int) {
	return file_google_internal_cloud_code_v1internal_metrics_proto_rawDescGZIP(), []int{5, 0}
}

func (x *ConversationOffered_StreamingLatency) GetFirstMessageLatency() *durationpb.Duration {
	if x != nil {
		return x.FirstMessageLatency
	}
	return nil
}

func (x *ConversationOffered_StreamingLatency) GetTotalLatency() *durationpb.Duration {
	if x != nil {
		return x.TotalLatency
	}
	return nil
}

var File_google_internal_cloud_code_v1internal_metrics_proto protoreflect.FileDescriptor

const file_google_internal_cloud_code_v1internal_metrics_proto_rawDesc = "" +
	"\n" +
	"3google/internal/cloud/code/v1internal/metrics.proto\x12%google.internal.cloud.code.v1internal\x1a6google/internal/cloud/code/v1internal/onboarding.proto\x1a\x1egoogle/protobuf/duration.proto\x1a\x1fgoogle/protobuf/timestamp.proto\"\xff\x01\n" +
	"\x1eRecordCodeAssistMetricsRequest\x12\x18\n" +
	"\aproject\x18\x01 \x01(\tR\aproject\x12\x1d\n" +
	"\n" +
	"request_id\x18\x02 \x01(\tR\trequestId\x12Q\n" +
	"\bmetadata\x18\x03 \x01(\v25.google.internal.cloud.code.v1internal.ClientMetadataR\bmetadata\x12Q\n" +
	"\ametrics\x18\x04 \x03(\v27.google.internal.cloud.code.v1internal.CodeAssistMetricR\ametrics\"\xdf\x01\n" +
	"\x18RecordClientEventRequest\x12\x18\n" +
	"\aproject\x18\x01 \x01(\tR\aproject\x12X\n" +
	"\bide_type\x18\x02 \x01(\x0e2=.google.internal.cloud.code.v1internal.ClientMetadata.IdeTypeR\aideType\x12O\n" +
	"\x06metric\x18\x03 \x01(\v27.google.internal.cloud.code.v1internal.CodeAssistMetricR\x06metric\"\xd1\t\n" +
	"\x10CodeAssistMetric\x128\n" +
	"\ttimestamp\x18\x01 \x01(\v2\x1a.google.protobuf.TimestampR\ttimestamp\x12\x7f\n" +
	"\x1ainline_completion_accepted\x18\x02 \x01(\v2?.google.internal.cloud.code.v1internal.InlineCompletionAcceptedH\x00R\x18inlineCompletionAccepted\x12|\n" +
	"\x19inline_completion_offered\x18\x03 \x01(\v2>.google.internal.cloud.code.v1internal.InlineCompletionOfferedH\x00R\x17inlineCompletionOffered\x12o\n" +
	"\x14conversation_offered\x18\x04 \x01(\v2:.google.internal.cloud.code.v1internal.ConversationOfferedH\x00R\x13conversationOffered\x12a\n" +
	"\x10generate_code_ui\x18\x05 \x01(\v25.google.internal.cloud.code.v1internal.GenerateCodeUIH\x00R\x0egenerateCodeUi\x12v\n" +
	"\x17conversation_explain_ui\x18\x06 \x01(\v2<.google.internal.cloud.code.v1internal.ConversationExplainUIH\x00R\x15conversationExplainUi\x12\x86\x01\n" +
	"\x1dconversation_generate_test_ui\x18\a \x01(\v2A.google.internal.cloud.code.v1internal.ConversationGenerateTestUIH\x00R\x1aconversationGenerateTestUi\x12{\n" +
	"\x18conversation_interaction\x18\b \x01(\v2>.google.internal.cloud.code.v1internal.ConversationInteractionH\x00R\x17conversationInteraction\x12p\n" +
	"\x15ai_characters_reports\x18\t \x01(\v2:.google.internal.cloud.code.v1internal.AiCharactersReportsH\x00R\x13aiCharactersReports\x12t\n" +
	"\x0fmetric_metadata\x18\n" +
	" \x03(\v2K.google.internal.cloud.code.v1internal.CodeAssistMetric.MetricMetadataEntryR\x0emetricMetadata\x1aA\n" +
	"\x13MetricMetadataEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01B\a\n" +
	"\x05event\"\xbd\x06\n" +
	"\x18InlineCompletionAccepted\x12\x19\n" +
	"\btrace_id\x18\x01 \x01(\tR\atraceId\x12\x14\n" +
	"\x05score\x18\x02 \x01(\x02R\x05score\x12#\n" +
	"\rresponse_size\x18\x03 \x01(\x03R\fresponseSize\x12%\n" +
	"\x0eresponse_lines\x18\x04 \x01(\x03R\rresponseLines\x12\x1a\n" +
	"\blanguage\x18\x05 \x01(\tR\blanguage\x12}\n" +
	"\x11completion_method\x18\x06 \x01(\x0e2P.google.internal.cloud.code.v1internal.InlineCompletionAccepted.CompletionMethodR\x10completionMethod\x12C\n" +
	"\x1bpartial_accepted_characters\x18\a \x01(\x03H\x00R\x19partialAcceptedCharacters\x88\x01\x01\x129\n" +
	"\x16partial_accepted_lines\x18\b \x01(\x03H\x01R\x14partialAcceptedLines\x88\x01\x01\x12K\n" +
	"\x06status\x18\t \x01(\x0e23.google.internal.cloud.code.v1internal.ActionStatusR\x06status\x129\n" +
	"\x16accepted_comment_lines\x18\n" +
	" \x01(\x03H\x02R\x14acceptedCommentLines\x88\x01\x01\x126\n" +
	"\x17response_accepted_index\x18\v \x01(\x03R\x15responseAcceptedIndex\"s\n" +
	"\x10CompletionMethod\x12\v\n" +
	"\aUNKNOWN\x10\x00\x12\x11\n" +
	"\rGENERATE_CODE\x10\x01\x12\x11\n" +
	"\rCOMPLETE_CODE\x10\x02\x12\x12\n" +
	"\x0eTRANSFORM_CODE\x10\x03\x12\x18\n" +
	"\x14AUTOMATIC_GENERATION\x10\x04B\x1e\n" +
	"\x1c_partial_accepted_charactersB\x19\n" +
	"\x17_partial_accepted_linesB\x19\n" +
	"\x17_accepted_comment_lines\"\xb2\a\n" +
	"\x17InlineCompletionOffered\x12\x19\n" +
	"\btrace_id\x18\x01 \x01(\tR\atraceId\x12!\n" +
	"\fresult_count\x18\x02 \x01(\x03R\vresultCount\x12\x1a\n" +
	"\blanguage\x18\x03 \x01(\tR\blanguage\x12v\n" +
	"\x0fcompletion_mode\x18\x04 \x01(\x0e2M.google.internal.cloud.code.v1internal.InlineCompletionOffered.CompletionModeR\x0ecompletionMode\x12@\n" +
	"\x0edisplay_length\x18\x05 \x01(\v2\x19.google.protobuf.DurationR\rdisplayLength\x12K\n" +
	"\x06status\x18\x06 \x01(\x0e23.google.internal.cloud.code.v1internal.ActionStatusR\x06status\x12|\n" +
	"\x11completion_method\x18\a \x01(\x0e2O.google.internal.cloud.code.v1internal.InlineCompletionOffered.CompletionMethodR\x10completionMethod\x12D\n" +
	"\x10response_latency\x18\b \x01(\v2\x19.google.protobuf.DurationR\x0fresponseLatency\x126\n" +
	"\x17response_received_index\x18\t \x01(\x03R\x15responseReceivedIndex\"j\n" +
	"\x0eCompletionMode\x12\v\n" +
	"\aUNKNOWN\x10\x00\x12\x13\n" +
	"\x0fLANGUAGE_CLIENT\x10\x01\x12\f\n" +
	"\bTYPEOVER\x10\x02\x12\x14\n" +
	"\x10TYPEOVER_NEWLINE\x10\x03\x12\x12\n" +
	"\x0eTRANSFORM_CODE\x10\x04\"\xcd\x01\n" +
	"\x10CompletionMethod\x12\x1d\n" +
	"\x19COMPLETION_METHOD_UNKNOWN\x10\x00\x12#\n" +
	"\x1fCOMPLETION_METHOD_GENERATE_CODE\x10\x01\x12#\n" +
	"\x1fCOMPLETION_METHOD_COMPLETE_CODE\x10\x02\x12$\n" +
	" COMPLETION_METHOD_TRANSFORM_CODE\x10\x03\x12*\n" +
	"&COMPLETION_METHOD_AUTOMATIC_GENERATION\x10\x04\"\xe1\x06\n" +
	"\x13ConversationOffered\x12%\n" +
	"\x0ecitation_count\x18\x01 \x01(\x03R\rcitationCount\x12#\n" +
	"\rincluded_code\x18\x02 \x01(\bR\fincludedCode\x12K\n" +
	"\x06status\x18\x03 \x01(\x0e23.google.internal.cloud.code.v1internal.ActionStatusR\x06status\x12\x19\n" +
	"\btrace_id\x18\x04 \x01(\tR\atraceId\x12x\n" +
	"\x11streaming_latency\x18\x05 \x01(\v2K.google.internal.cloud.code.v1internal.ConversationOffered.StreamingLatencyR\x10streamingLatency\x12\x1d\n" +
	"\n" +
	"is_agentic\x18\x06 \x01(\bR\tisAgentic\x12x\n" +
	"\x11initiation_method\x18\a \x01(\x0e2K.google.internal.cloud.code.v1internal.ConversationOffered.InitiationMethodR\x10initiationMethod\x12#\n" +
	"\rtrajectory_id\x18\b \x01(\tR\ftrajectoryId\x12\x1f\n" +
	"\blanguage\x18\t \x01(\tH\x00R\blanguage\x88\x01\x01\x1a\xd7\x01\n" +
	"\x10StreamingLatency\x12R\n" +
	"\x15first_message_latency\x18\x01 \x01(\v2\x19.google.protobuf.DurationH\x00R\x13firstMessageLatency\x88\x01\x01\x12C\n" +
	"\rtotal_latency\x18\x02 \x01(\v2\x19.google.protobuf.DurationH\x01R\ftotalLatency\x88\x01\x01B\x18\n" +
	"\x16_first_message_latencyB\x10\n" +
	"\x0e_total_latency\"V\n" +
	"\x10InitiationMethod\x12!\n" +
	"\x1dINITIATION_METHOD_UNSPECIFIED\x10\x00\x12\a\n" +
	"\x03TAB\x10\x01\x12\v\n" +
	"\aCOMMAND\x10\x02\x12\t\n" +
	"\x05AGENT\x10\x03B\v\n" +
	"\t_language\"\xd6\x05\n" +
	"\x17ConversationInteraction\x12\x19\n" +
	"\btrace_id\x18\x01 \x01(\tR\atraceId\x12K\n" +
	"\x06status\x18\x02 \x01(\x0e23.google.internal.cloud.code.v1internal.ActionStatusR\x06status\x12l\n" +
	"\vinteraction\x18\x03 \x01(\x0e2J.google.internal.cloud.code.v1internal.ConversationInteraction.InteractionR\vinteraction\x12*\n" +
	"\x0eaccepted_lines\x18\x04 \x01(\x03H\x00R\racceptedLines\x88\x01\x01\x12\x1f\n" +
	"\blanguage\x18\x05 \x01(\tH\x01R\blanguage\x88\x01\x01\x12\x1d\n" +
	"\n" +
	"is_agentic\x18\x06 \x01(\bR\tisAgentic\x12(\n" +
	"\rremoved_lines\x18\a \x01(\x03H\x02R\fremovedLines\x88\x01\x01\x12x\n" +
	"\x11initiation_method\x18\b \x01(\x0e2K.google.internal.cloud.code.v1internal.ConversationOffered.InitiationMethodR\x10initiationMethod\"\xa2\x01\n" +
	"\vInteraction\x12\v\n" +
	"\aUNKNOWN\x10\x00\x12\f\n" +
	"\bTHUMBSUP\x10\x01\x12\x0e\n" +
	"\n" +
	"THUMBSDOWN\x10\x02\x12\b\n" +
	"\x04COPY\x10\x03\x12\n" +
	"\n" +
	"\x06INSERT\x10\x04\x12\x15\n" +
	"\x11ACCEPT_CODE_BLOCK\x10\x05\x12\x0e\n" +
	"\n" +
	"ACCEPT_ALL\x10\x06\x12\x0f\n" +
	"\vACCEPT_FILE\x10\a\x12\b\n" +
	"\x04DIFF\x10\b\x12\x10\n" +
	"\fACCEPT_RANGE\x10\tB\x11\n" +
	"\x0f_accepted_linesB\v\n" +
	"\t_languageB\x10\n" +
	"\x0e_removed_lines\"\x10\n" +
	"\x0eGenerateCodeUI\"\x17\n" +
	"\x15ConversationExplainUI\"\x1c\n" +
	"\x1aConversationGenerateTestUI\"j\n" +
	"\x13AiCharactersReports\x12S\n" +
	"\areports\x18\x01 \x03(\v29.google.internal.cloud.code.v1internal.AiCharactersReportR\areports\"\xc1\x03\n" +
	"\x12AiCharactersReport\x12\x1a\n" +
	"\blanguage\x18\x01 \x01(\tR\blanguage\x12_\n" +
	"\tedit_type\x18\x02 \x01(\x0e2B.google.internal.cloud.code.v1internal.AiCharactersReport.EditTypeR\beditType\x12\x1f\n" +
	"\vtotal_chars\x18\x03 \x01(\x03R\n" +
	"totalChars\x12)\n" +
	"\x10whitespace_chars\x18\x04 \x01(\x03R\x0fwhitespaceChars\x12.\n" +
	"\x13time_interval_index\x18\x05 \x01(\x03R\x11timeIntervalIndex\"\xb1\x01\n" +
	"\bEditType\x12\x19\n" +
	"\x15EDIT_TYPE_UNSPECIFIED\x10\x00\x12\f\n" +
	"\bUSER_ADD\x10\x01\x12\t\n" +
	"\x05PASTE\x10\x02\x12\n" +
	"\n" +
	"\x06DELETE\x10\x03\x12\t\n" +
	"\x05OTHER\x10\x04\x12\x11\n" +
	"\rAI_COMPLETION\x10\x05\x12\x19\n" +
	"\x15AI_COMPLETION_PARTIAL\x10\x06\x12\x11\n" +
	"\rAI_GENERATION\x10\a\x12\x19\n" +
	"\x15AI_GENERATION_PARTIAL\x10\b*\xa0\x01\n" +
	"\fActionStatus\x12\x1d\n" +
	"\x19ACTION_STATUS_UNSPECIFIED\x10\x00\x12\x1a\n" +
	"\x16ACTION_STATUS_NO_ERROR\x10\x01\x12\x1f\n" +
	"\x1bACTION_STATUS_ERROR_UNKNOWN\x10\x02\x12\x1b\n" +
	"\x17ACTION_STATUS_CANCELLED\x10\x03\x12\x17\n" +
	"\x13ACTION_STATUS_EMPTY\x10\x04BCZAgithub.com/router-for-me/CLIProxyAPI/v6/internal/proto/v1internalb\x06proto3"

var (
	file_google_internal_cloud_code_v1internal_metrics_proto_rawDescOnce sync.Once
	file_google_internal_cloud_code_v1internal_metrics_proto_rawDescData []byte
)

func file_google_internal_cloud_code_v1internal_metrics_proto_rawDescGZIP() []byte {
	file_google_internal_cloud_code_v1internal_metrics_proto_rawDescOnce.Do(func() {
		file_google_internal_cloud_code_v1internal_metrics_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_google_internal_cloud_code_v1internal_metrics_proto_rawDesc), len(file_google_internal_cloud_code_v1internal_metrics_proto_rawDesc)))
	})
	return file_google_internal_cloud_code_v1internal_metrics_proto_rawDescData
}

var file_google_internal_cloud_code_v1internal_metrics_proto_enumTypes = make([]protoimpl.EnumInfo, 7)
var file_google_internal_cloud_code_v1internal_metrics_proto_msgTypes = make([]protoimpl.MessageInfo, 14)
var file_google_internal_cloud_code_v1internal_metrics_proto_goTypes = []any{
	(ActionStatus)(0), // 0: google.internal.cloud.code.v1internal.ActionStatus
	(InlineCompletionAccepted_CompletionMethod)(0), // 1: google.internal.cloud.code.v1internal.InlineCompletionAccepted.CompletionMethod
	(InlineCompletionOffered_CompletionMode)(0),    // 2: google.internal.cloud.code.v1internal.InlineCompletionOffered.CompletionMode
	(InlineCompletionOffered_CompletionMethod)(0),  // 3: google.internal.cloud.code.v1internal.InlineCompletionOffered.CompletionMethod
	(ConversationOffered_InitiationMethod)(0),      // 4: google.internal.cloud.code.v1internal.ConversationOffered.InitiationMethod
	(ConversationInteraction_Interaction)(0),       // 5: google.internal.cloud.code.v1internal.ConversationInteraction.Interaction
	(AiCharactersReport_EditType)(0),               // 6: google.internal.cloud.code.v1internal.AiCharactersReport.EditType
	(*RecordCodeAssistMetricsRequest)(nil),         // 7: google.internal.cloud.code.v1internal.RecordCodeAssistMetricsRequest
	(*RecordClientEventRequest)(nil),               // 8: google.internal.cloud.code.v1internal.RecordClientEventRequest
	(*CodeAssistMetric)(nil),                       // 9: google.internal.cloud.code.v1internal.CodeAssistMetric
	(*InlineCompletionAccepted)(nil),               // 10: google.internal.cloud.code.v1internal.InlineCompletionAccepted
	(*InlineCompletionOffered)(nil),                // 11: google.internal.cloud.code.v1internal.InlineCompletionOffered
	(*ConversationOffered)(nil),                    // 12: google.internal.cloud.code.v1internal.ConversationOffered
	(*ConversationInteraction)(nil),                // 13: google.internal.cloud.code.v1internal.ConversationInteraction
	(*GenerateCodeUI)(nil),                         // 14: google.internal.cloud.code.v1internal.GenerateCodeUI
	(*ConversationExplainUI)(nil),                  // 15: google.internal.cloud.code.v1internal.ConversationExplainUI
	(*ConversationGenerateTestUI)(nil),             // 16: google.internal.cloud.code.v1internal.ConversationGenerateTestUI
	(*AiCharactersReports)(nil),                    // 17: google.internal.cloud.code.v1internal.AiCharactersReports
	(*AiCharactersReport)(nil),                     // 18: google.internal.cloud.code.v1internal.AiCharactersReport
	nil,                                            // 19: google.internal.cloud.code.v1internal.CodeAssistMetric.MetricMetadataEntry
	(*ConversationOffered_StreamingLatency)(nil),   // 20: google.internal.cloud.code.v1internal.ConversationOffered.StreamingLatency
	(*ClientMetadata)(nil),                         // 21: google.internal.cloud.code.v1internal.ClientMetadata
	(ClientMetadata_IdeType)(0),                    // 22: google.internal.cloud.code.v1internal.ClientMetadata.IdeType
	(*timestamppb.Timestamp)(nil),                  // 23: google.protobuf.Timestamp
	(*durationpb.Duration)(nil),                    // 24: google.protobuf.Duration
}
var file_google_internal_cloud_code_v1internal_metrics_proto_depIdxs = []int32{
	21, // 0: google.internal.cloud.code.v1internal.RecordCodeAssistMetricsRequest.metadata:type_name -> google.internal.cloud.code.v1internal.ClientMetadata
	9,  // 1: google.internal.cloud.code.v1internal.RecordCodeAssistMetricsRequest.metrics:type_name -> google.internal.cloud.code.v1internal.CodeAssistMetric
	22, // 2: google.internal.cloud.code.v1internal.RecordClientEventRequest.ide_type:type_name -> google.internal.cloud.code.v1internal.ClientMetadata.IdeType
	9,  // 3: google.internal.cloud.code.v1internal.RecordClientEventRequest.metric:type_name -> google.internal.cloud.code.v1internal.CodeAssistMetric
	23, // 4: google.internal.cloud.code.v1internal.CodeAssistMetric.timestamp:type_name -> google.protobuf.Timestamp
	10, // 5: google.internal.cloud.code.v1internal.CodeAssistMetric.inline_completion_accepted:type_name -> google.internal.cloud.code.v1internal.InlineCompletionAccepted
	11, // 6: google.internal.cloud.code.v1internal.CodeAssistMetric.inline_completion_offered:type_name -> google.internal.cloud.code.v1internal.InlineCompletionOffered
	12, // 7: google.internal.cloud.code.v1internal.CodeAssistMetric.conversation_offered:type_name -> google.internal.cloud.code.v1internal.ConversationOffered
	14, // 8: google.internal.cloud.code.v1internal.CodeAssistMetric.generate_code_ui:type_name -> google.internal.cloud.code.v1internal.GenerateCodeUI
	15, // 9: google.internal.cloud.code.v1internal.CodeAssistMetric.conversation_explain_ui:type_name -> google.internal.cloud.code.v1internal.ConversationExplainUI
	16, // 10: google.internal.cloud.code.v1internal.CodeAssistMetric.conversation_generate_test_ui:type_name -> google.internal.cloud.code.v1internal.ConversationGenerateTestUI
	13, // 11: google.internal.cloud.code.v1internal.CodeAssistMetric.conversation_interaction:type_name -> google.internal.cloud.code.v1internal.ConversationInteraction
	17, // 12: google.internal.cloud.code.v1internal.CodeAssistMetric.ai_characters_reports:type_name -> google.internal.cloud.code.v1internal.AiCharactersReports
	19, // 13: google.internal.cloud.code.v1internal.CodeAssistMetric.metric_metadata:type_name -> google.internal.cloud.code.v1internal.CodeAssistMetric.MetricMetadataEntry
	1,  // 14: google.internal.cloud.code.v1internal.InlineCompletionAccepted.completion_method:type_name -> google.internal.cloud.code.v1internal.InlineCompletionAccepted.CompletionMethod
	0,  // 15: google.internal.cloud.code.v1internal.InlineCompletionAccepted.status:type_name -> google.internal.cloud.code.v1internal.ActionStatus
	2,  // 16: google.internal.cloud.code.v1internal.InlineCompletionOffered.completion_mode:type_name -> google.internal.cloud.code.v1internal.InlineCompletionOffered.CompletionMode
	24, // 17: google.internal.cloud.code.v1internal.InlineCompletionOffered.display_length:type_name -> google.protobuf.Duration
	0,  // 18: google.internal.cloud.code.v1internal.InlineCompletionOffered.status:type_name -> google.internal.cloud.code.v1internal.ActionStatus
	3,  // 19: google.internal.cloud.code.v1internal.InlineCompletionOffered.completion_method:type_name -> google.internal.cloud.code.v1internal.InlineCompletionOffered.CompletionMethod
	24, // 20: google.internal.cloud.code.v1internal.InlineCompletionOffered.response_latency:type_name -> google.protobuf.Duration
	0,  // 21: google.internal.cloud.code.v1internal.ConversationOffered.status:type_name -> google.internal.cloud.code.v1internal.ActionStatus
	20, // 22: google.internal.cloud.code.v1internal.ConversationOffered.streaming_latency:type_name -> google.internal.cloud.code.v1internal.ConversationOffered.StreamingLatency
	4,  // 23: google.internal.cloud.code.v1internal.ConversationOffered.initiation_method:type_name -> google.internal.cloud.code.v1internal.ConversationOffered.InitiationMethod
	0,  // 24: google.internal.cloud.code.v1internal.ConversationInteraction.status:type_name -> google.internal.cloud.code.v1internal.ActionStatus
	5,  // 25: google.internal.cloud.code.v1internal.ConversationInteraction.interaction:type_name -> google.internal.cloud.code.v1internal.ConversationInteraction.Interaction
	4,  // 26: google.internal.cloud.code.v1internal.ConversationInteraction.initiation_method:type_name -> google.internal.cloud.code.v1internal.ConversationOffered.InitiationMethod
	18, // 27: google.internal.cloud.code.v1internal.AiCharactersReports.reports:type_name -> google.internal.cloud.code.v1internal.AiCharactersReport
	6,  // 28: google.internal.cloud.code.v1internal.AiCharactersReport.edit_type:type_name -> google.internal.cloud.code.v1internal.AiCharactersReport.EditType
	24, // 29: google.internal.cloud.code.v1internal.ConversationOffered.StreamingLatency.first_message_latency:type_name -> google.protobuf.Duration
	24, // 30: google.internal.cloud.code.v1internal.ConversationOffered.StreamingLatency.total_latency:type_name -> google.protobuf.Duration
	31, // [31:31] is the sub-list for method output_type
	31, // [31:31] is the sub-list for method input_type
	31, // [31:31] is the sub-list for extension type_name
	31, // [31:31] is the sub-list for extension extendee
	0,  // [0:31] is the sub-list for field type_name
}

func init() { file_google_internal_cloud_code_v1internal_metrics_proto_init() }
func file_google_internal_cloud_code_v1internal_metrics_proto_init() {
	if File_google_internal_cloud_code_v1internal_metrics_proto != nil {
		return
	}
	file_google_internal_cloud_code_v1internal_onboarding_proto_init()
	file_google_internal_cloud_code_v1internal_metrics_proto_msgTypes[2].OneofWrappers = []any{
		(*CodeAssistMetric_InlineCompletionAccepted)(nil),
		(*CodeAssistMetric_InlineCompletionOffered)(nil),
		(*CodeAssistMetric_ConversationOffered)(nil),
		(*CodeAssistMetric_GenerateCodeUi)(nil),
		(*CodeAssistMetric_ConversationExplainUi)(nil),
		(*CodeAssistMetric_ConversationGenerateTestUi)(nil),
		(*CodeAssistMetric_ConversationInteraction)(nil),
		(*CodeAssistMetric_AiCharactersReports)(nil),
	}
	file_google_internal_cloud_code_v1internal_metrics_proto_msgTypes[3].OneofWrappers = []any{}
	file_google_internal_cloud_code_v1internal_metrics_proto_msgTypes[5].OneofWrappers = []any{}
	file_google_internal_cloud_code_v1internal_metrics_proto_msgTypes[6].OneofWrappers = []any{}
	file_google_internal_cloud_code_v1internal_metrics_proto_msgTypes[13].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_google_internal_cloud_code_v1internal_metrics_proto_rawDesc), len(file_google_internal_cloud_code_v1internal_metrics_proto_rawDesc)),
			NumEnums:      7,
			NumMessages:   14,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_google_internal_cloud_code_v1internal_metrics_proto_goTypes,
		DependencyIndexes: file_google_internal_cloud_code_v1internal_metrics_proto_depIdxs,
		EnumInfos:         file_google_internal_cloud_code_v1internal_metrics_proto_enumTypes,
		MessageInfos:      file_google_internal_cloud_code_v1internal_metrics_proto_msgTypes,
	}.Build()
	File_google_internal_cloud_code_v1internal_metrics_proto = out.File
	file_google_internal_cloud_code_v1internal_metrics_proto_goTypes = nil
	file_google_internal_cloud_code_v1internal_metrics_proto_depIdxs = nil
}
