// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v4.25.1
// source: google/internal/cloud/code/v1internal/model_configs.proto

package v1internal

import (
	codeium "github.com/router-for-me/CLIProxyAPI/v6/internal/proto/stubs/codeium"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type FetchAvailableModelsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Project       string                 `protobuf:"bytes,1,opt,name=project,proto3" json:"project,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FetchAvailableModelsRequest) Reset() {
	*x = FetchAvailableModelsRequest{}
	mi := &file_google_internal_cloud_code_v1internal_model_configs_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FetchAvailableModelsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FetchAvailableModelsRequest) ProtoMessage() {}

func (x *FetchAvailableModelsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_google_internal_cloud_code_v1internal_model_configs_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FetchAvailableModelsRequest.ProtoReflect.Descriptor instead.
func (*FetchAvailableModelsRequest) Descriptor() ([]byte, []int) {
	return file_google_internal_cloud_code_v1internal_model_configs_proto_rawDescGZIP(), []int{0}
}

func (x *FetchAvailableModelsRequest) GetProject() string {
	if x != nil {
		return x.Project
	}
	return ""
}

type QuotaInfo struct {
	state             protoimpl.MessageState `protogen:"open.v1"`
	RemainingFraction float32                `protobuf:"fixed32,1,opt,name=remaining_fraction,json=remainingFraction,proto3" json:"remaining_fraction,omitempty"`
	ResetTime         *timestamppb.Timestamp `protobuf:"bytes,2,opt,name=reset_time,json=resetTime,proto3" json:"reset_time,omitempty"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *QuotaInfo) Reset() {
	*x = QuotaInfo{}
	mi := &file_google_internal_cloud_code_v1internal_model_configs_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *QuotaInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*QuotaInfo) ProtoMessage() {}

func (x *QuotaInfo) ProtoReflect() protoreflect.Message {
	mi := &file_google_internal_cloud_code_v1internal_model_configs_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use QuotaInfo.ProtoReflect.Descriptor instead.
func (*QuotaInfo) Descriptor() ([]byte, []int) {
	return file_google_internal_cloud_code_v1internal_model_configs_proto_rawDescGZIP(), []int{1}
}

func (x *QuotaInfo) GetRemainingFraction() float32 {
	if x != nil {
		return x.RemainingFraction
	}
	return 0
}

func (x *QuotaInfo) GetResetTime() *timestamppb.Timestamp {
	if x != nil {
		return x.ResetTime
	}
	return nil
}

type ModelDetails struct {
	state                                       protoimpl.MessageState      `protogen:"open.v1"`
	DisplayName                                 string                      `protobuf:"bytes,1,opt,name=display_name,json=displayName,proto3" json:"display_name,omitempty"`
	SupportsImages                              bool                        `protobuf:"varint,2,opt,name=supports_images,json=supportsImages,proto3" json:"supports_images,omitempty"`
	SupportsThinking                            bool                        `protobuf:"varint,3,opt,name=supports_thinking,json=supportsThinking,proto3" json:"supports_thinking,omitempty"`
	ThinkingBudget                              int32                       `protobuf:"varint,4,opt,name=thinking_budget,json=thinkingBudget,proto3" json:"thinking_budget,omitempty"`
	MinThinkingBudget                           int32                       `protobuf:"varint,5,opt,name=min_thinking_budget,json=minThinkingBudget,proto3" json:"min_thinking_budget,omitempty"`
	Recommended                                 bool                        `protobuf:"varint,6,opt,name=recommended,proto3" json:"recommended,omitempty"`
	MaxTokens                                   int32                       `protobuf:"varint,7,opt,name=max_tokens,json=maxTokens,proto3" json:"max_tokens,omitempty"`
	MaxOutputTokens                             int32                       `protobuf:"varint,8,opt,name=max_output_tokens,json=maxOutputTokens,proto3" json:"max_output_tokens,omitempty"`
	TokenizerType                               string                      `protobuf:"bytes,9,opt,name=tokenizer_type,json=tokenizerType,proto3" json:"tokenizer_type,omitempty"`
	QuotaInfo                                   *QuotaInfo                  `protobuf:"bytes,10,opt,name=quota_info,json=quotaInfo,proto3" json:"quota_info,omitempty"`
	BetaWarningMessage                          string                      `protobuf:"bytes,11,opt,name=beta_warning_message,json=betaWarningMessage,proto3" json:"beta_warning_message,omitempty"`
	Beta                                        bool                        `protobuf:"varint,12,opt,name=beta,proto3" json:"beta,omitempty"`
	Disabled                                    bool                        `protobuf:"varint,13,opt,name=disabled,proto3" json:"disabled,omitempty"`
	Description                                 string                      `protobuf:"bytes,14,opt,name=description,proto3" json:"description,omitempty"`
	Model                                       codeium.Model               `protobuf:"varint,15,opt,name=model,proto3,enum=exa.codeium_common_pb.Model" json:"model,omitempty"`
	ApiProvider                                 codeium.APIProvider         `protobuf:"varint,16,opt,name=api_provider,json=apiProvider,proto3,enum=exa.codeium_common_pb.APIProvider" json:"api_provider,omitempty"`
	ModelProvider                               codeium.ModelProvider       `protobuf:"varint,17,opt,name=model_provider,json=modelProvider,proto3,enum=exa.codeium_common_pb.ModelProvider" json:"model_provider,omitempty"`
	SupportsCumulativeContext                   bool                        `protobuf:"varint,18,opt,name=supports_cumulative_context,json=supportsCumulativeContext,proto3" json:"supports_cumulative_context,omitempty"`
	TabJumpPrintLineRange                       bool                        `protobuf:"varint,19,opt,name=tab_jump_print_line_range,json=tabJumpPrintLineRange,proto3" json:"tab_jump_print_line_range,omitempty"`
	SupportsEstimateTokenCounter                bool                        `protobuf:"varint,20,opt,name=supports_estimate_token_counter,json=supportsEstimateTokenCounter,proto3" json:"supports_estimate_token_counter,omitempty"`
	IsInternal                                  bool                        `protobuf:"varint,21,opt,name=is_internal,json=isInternal,proto3" json:"is_internal,omitempty"`
	AddCursorToFindReplaceTarget                bool                        `protobuf:"varint,22,opt,name=add_cursor_to_find_replace_target,json=addCursorToFindReplaceTarget,proto3" json:"add_cursor_to_find_replace_target,omitempty"`
	PromptTemplaterType                         codeium.PromptTemplaterType `protobuf:"varint,23,opt,name=prompt_templater_type,json=promptTemplaterType,proto3,enum=exa.codeium_common_pb.PromptTemplaterType" json:"prompt_templater_type,omitempty"`
	ToolFormatterType                           codeium.ToolFormatterType   `protobuf:"varint,24,opt,name=tool_formatter_type,json=toolFormatterType,proto3,enum=exa.codeium_common_pb.ToolFormatterType" json:"tool_formatter_type,omitempty"`
	SupportsRawThinking                         bool                        `protobuf:"varint,25,opt,name=supports_raw_thinking,json=supportsRawThinking,proto3" json:"supports_raw_thinking,omitempty"`
	SupportsVideo                               bool                        `protobuf:"varint,26,opt,name=supports_video,json=supportsVideo,proto3" json:"supports_video,omitempty"`
	SupportsPdf                                 bool                        `protobuf:"varint,27,opt,name=supports_pdf,json=supportsPdf,proto3" json:"supports_pdf,omitempty"`
	RequiresLeadInGeneration                    bool                        `protobuf:"varint,28,opt,name=requires_lead_in_generation,json=requiresLeadInGeneration,proto3" json:"requires_lead_in_generation,omitempty"`
	TagTitle                                    string                      `protobuf:"bytes,29,opt,name=tag_title,json=tagTitle,proto3" json:"tag_title,omitempty"`
	TagDescription                              string                      `protobuf:"bytes,30,opt,name=tag_description,json=tagDescription,proto3" json:"tag_description,omitempty"`
	RequiresNoXmlToolExamples                   bool                        `protobuf:"varint,31,opt,name=requires_no_xml_tool_examples,json=requiresNoXmlToolExamples,proto3" json:"requires_no_xml_tool_examples,omitempty"`
	SupportedMimeTypes                          map[string]bool             `protobuf:"bytes,32,rep,name=supported_mime_types,json=supportedMimeTypes,proto3" json:"supported_mime_types,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"varint,2,opt,name=value"`
	RequiresImageOutputOutsideFunctionResponses bool                        `protobuf:"varint,33,opt,name=requires_image_output_outside_function_responses,json=requiresImageOutputOutsideFunctionResponses,proto3" json:"requires_image_output_outside_function_responses,omitempty"`
	Preview                                     bool                        `protobuf:"varint,34,opt,name=preview,proto3" json:"preview,omitempty"`
	ThinkingLevel                               int32                       `protobuf:"varint,35,opt,name=thinking_level,json=thinkingLevel,proto3" json:"thinking_level,omitempty"`
	unknownFields                               protoimpl.UnknownFields
	sizeCache                                   protoimpl.SizeCache
}

func (x *ModelDetails) Reset() {
	*x = ModelDetails{}
	mi := &file_google_internal_cloud_code_v1internal_model_configs_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ModelDetails) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ModelDetails) ProtoMessage() {}

func (x *ModelDetails) ProtoReflect() protoreflect.Message {
	mi := &file_google_internal_cloud_code_v1internal_model_configs_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ModelDetails.ProtoReflect.Descriptor instead.
func (*ModelDetails) Descriptor() ([]byte, []int) {
	return file_google_internal_cloud_code_v1internal_model_configs_proto_rawDescGZIP(), []int{2}
}

func (x *ModelDetails) GetDisplayName() string {
	if x != nil {
		return x.DisplayName
	}
	return ""
}

func (x *ModelDetails) GetSupportsImages() bool {
	if x != nil {
		return x.SupportsImages
	}
	return false
}

func (x *ModelDetails) GetSupportsThinking() bool {
	if x != nil {
		return x.SupportsThinking
	}
	return false
}

func (x *ModelDetails) GetThinkingBudget() int32 {
	if x != nil {
		return x.ThinkingBudget
	}
	return 0
}

func (x *ModelDetails) GetMinThinkingBudget() int32 {
	if x != nil {
		return x.MinThinkingBudget
	}
	return 0
}

func (x *ModelDetails) GetRecommended() bool {
	if x != nil {
		return x.Recommended
	}
	return false
}

func (x *ModelDetails) GetMaxTokens() int32 {
	if x != nil {
		return x.MaxTokens
	}
	return 0
}

func (x *ModelDetails) GetMaxOutputTokens() int32 {
	if x != nil {
		return x.MaxOutputTokens
	}
	return 0
}

func (x *ModelDetails) GetTokenizerType() string {
	if x != nil {
		return x.TokenizerType
	}
	return ""
}

func (x *ModelDetails) GetQuotaInfo() *QuotaInfo {
	if x != nil {
		return x.QuotaInfo
	}
	return nil
}

func (x *ModelDetails) GetBetaWarningMessage() string {
	if x != nil {
		return x.BetaWarningMessage
	}
	return ""
}

func (x *ModelDetails) GetBeta() bool {
	if x != nil {
		return x.Beta
	}
	return false
}

func (x *ModelDetails) GetDisabled() bool {
	if x != nil {
		return x.Disabled
	}
	return false
}

func (x *ModelDetails) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *ModelDetails) GetModel() codeium.Model {
	if x != nil {
		return x.Model
	}
	return codeium.Model(0)
}

func (x *ModelDetails) GetApiProvider() codeium.APIProvider {
	if x != nil {
		return x.ApiProvider
	}
	return codeium.APIProvider(0)
}

func (x *ModelDetails) GetModelProvider() codeium.ModelProvider {
	if x != nil {
		return x.ModelProvider
	}
	return codeium.ModelProvider(0)
}

func (x *ModelDetails) GetSupportsCumulativeContext() bool {
	if x != nil {
		return x.SupportsCumulativeContext
	}
	return false
}

func (x *ModelDetails) GetTabJumpPrintLineRange() bool {
	if x != nil {
		return x.TabJumpPrintLineRange
	}
	return false
}

func (x *ModelDetails) GetSupportsEstimateTokenCounter() bool {
	if x != nil {
		return x.SupportsEstimateTokenCounter
	}
	return false
}

func (x *ModelDetails) GetIsInternal() bool {
	if x != nil {
		return x.IsInternal
	}
	return false
}

func (x *ModelDetails) GetAddCursorToFindReplaceTarget() bool {
	if x != nil {
		return x.AddCursorToFindReplaceTarget
	}
	return false
}

func (x *ModelDetails) GetPromptTemplaterType() codeium.PromptTemplaterType {
	if x != nil {
		return x.PromptTemplaterType
	}
	return codeium.PromptTemplaterType(0)
}

func (x *ModelDetails) GetToolFormatterType() codeium.ToolFormatterType {
	if x != nil {
		return x.ToolFormatterType
	}
	return codeium.ToolFormatterType(0)
}

func (x *ModelDetails) GetSupportsRawThinking() bool {
	if x != nil {
		return x.SupportsRawThinking
	}
	return false
}

func (x *ModelDetails) GetSupportsVideo() bool {
	if x != nil {
		return x.SupportsVideo
	}
	return false
}

func (x *ModelDetails) GetSupportsPdf() bool {
	if x != nil {
		return x.SupportsPdf
	}
	return false
}

func (x *ModelDetails) GetRequiresLeadInGeneration() bool {
	if x != nil {
		return x.RequiresLeadInGeneration
	}
	return false
}

func (x *ModelDetails) GetTagTitle() string {
	if x != nil {
		return x.TagTitle
	}
	return ""
}

func (x *ModelDetails) GetTagDescription() string {
	if x != nil {
		return x.TagDescription
	}
	return ""
}

func (x *ModelDetails) GetRequiresNoXmlToolExamples() bool {
	if x != nil {
		return x.RequiresNoXmlToolExamples
	}
	return false
}

func (x *ModelDetails) GetSupportedMimeTypes() map[string]bool {
	if x != nil {
		return x.SupportedMimeTypes
	}
	return nil
}

func (x *ModelDetails) GetRequiresImageOutputOutsideFunctionResponses() bool {
	if x != nil {
		return x.RequiresImageOutputOutsideFunctionResponses
	}
	return false
}

func (x *ModelDetails) GetPreview() bool {
	if x != nil {
		return x.Preview
	}
	return false
}

func (x *ModelDetails) GetThinkingLevel() int32 {
	if x != nil {
		return x.ThinkingLevel
	}
	return 0
}

type ModelSort struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	DisplayName   string                 `protobuf:"bytes,1,opt,name=display_name,json=displayName,proto3" json:"display_name,omitempty"`
	Groups        []*ModelGroup          `protobuf:"bytes,2,rep,name=groups,proto3" json:"groups,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ModelSort) Reset() {
	*x = ModelSort{}
	mi := &file_google_internal_cloud_code_v1internal_model_configs_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ModelSort) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ModelSort) ProtoMessage() {}

func (x *ModelSort) ProtoReflect() protoreflect.Message {
	mi := &file_google_internal_cloud_code_v1internal_model_configs_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ModelSort.ProtoReflect.Descriptor instead.
func (*ModelSort) Descriptor() ([]byte, []int) {
	return file_google_internal_cloud_code_v1internal_model_configs_proto_rawDescGZIP(), []int{3}
}

func (x *ModelSort) GetDisplayName() string {
	if x != nil {
		return x.DisplayName
	}
	return ""
}

func (x *ModelSort) GetGroups() []*ModelGroup {
	if x != nil {
		return x.Groups
	}
	return nil
}

type ModelGroup struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	DisplayName   string                 `protobuf:"bytes,1,opt,name=display_name,json=displayName,proto3" json:"display_name,omitempty"`
	ModelIds      []string               `protobuf:"bytes,2,rep,name=model_ids,json=modelIds,proto3" json:"model_ids,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ModelGroup) Reset() {
	*x = ModelGroup{}
	mi := &file_google_internal_cloud_code_v1internal_model_configs_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ModelGroup) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ModelGroup) ProtoMessage() {}

func (x *ModelGroup) ProtoReflect() protoreflect.Message {
	mi := &file_google_internal_cloud_code_v1internal_model_configs_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ModelGroup.ProtoReflect.Descriptor instead.
func (*ModelGroup) Descriptor() ([]byte, []int) {
	return file_google_internal_cloud_code_v1internal_model_configs_proto_rawDescGZIP(), []int{4}
}

func (x *ModelGroup) GetDisplayName() string {
	if x != nil {
		return x.DisplayName
	}
	return ""
}

func (x *ModelGroup) GetModelIds() []string {
	if x != nil {
		return x.ModelIds
	}
	return nil
}

type DeprecatedModelReroutingInfo struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	NewModelId    string                 `protobuf:"bytes,1,opt,name=new_model_id,json=newModelId,proto3" json:"new_model_id,omitempty"`
	OldModelEnum  codeium.Model          `protobuf:"varint,2,opt,name=old_model_enum,json=oldModelEnum,proto3,enum=exa.codeium_common_pb.Model" json:"old_model_enum,omitempty"`
	NewModelEnum  codeium.Model          `protobuf:"varint,3,opt,name=new_model_enum,json=newModelEnum,proto3,enum=exa.codeium_common_pb.Model" json:"new_model_enum,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeprecatedModelReroutingInfo) Reset() {
	*x = DeprecatedModelReroutingInfo{}
	mi := &file_google_internal_cloud_code_v1internal_model_configs_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeprecatedModelReroutingInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeprecatedModelReroutingInfo) ProtoMessage() {}

func (x *DeprecatedModelReroutingInfo) ProtoReflect() protoreflect.Message {
	mi := &file_google_internal_cloud_code_v1internal_model_configs_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeprecatedModelReroutingInfo.ProtoReflect.Descriptor instead.
func (*DeprecatedModelReroutingInfo) Descriptor() ([]byte, []int) {
	return file_google_internal_cloud_code_v1internal_model_configs_proto_rawDescGZIP(), []int{5}
}

func (x *DeprecatedModelReroutingInfo) GetNewModelId() string {
	if x != nil {
		return x.NewModelId
	}
	return ""
}

func (x *DeprecatedModelReroutingInfo) GetOldModelEnum() codeium.Model {
	if x != nil {
		return x.OldModelEnum
	}
	return codeium.Model(0)
}

func (x *DeprecatedModelReroutingInfo) GetNewModelEnum() codeium.Model {
	if x != nil {
		return x.NewModelEnum
	}
	return codeium.Model(0)
}

type FetchAvailableModelsResponse struct {
	state                   protoimpl.MessageState                   `protogen:"open.v1"`
	Models                  map[string]*ModelDetails                 `protobuf:"bytes,1,rep,name=models,proto3" json:"models,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	DefaultAgentModelId     string                                   `protobuf:"bytes,2,opt,name=default_agent_model_id,json=defaultAgentModelId,proto3" json:"default_agent_model_id,omitempty"`
	AgentModelSorts         []*ModelSort                             `protobuf:"bytes,3,rep,name=agent_model_sorts,json=agentModelSorts,proto3" json:"agent_model_sorts,omitempty"`
	CommandModelIds         []string                                 `protobuf:"bytes,4,rep,name=command_model_ids,json=commandModelIds,proto3" json:"command_model_ids,omitempty"`
	TabModelIds             []string                                 `protobuf:"bytes,5,rep,name=tab_model_ids,json=tabModelIds,proto3" json:"tab_model_ids,omitempty"`
	ImageGenerationModelIds []string                                 `protobuf:"bytes,6,rep,name=image_generation_model_ids,json=imageGenerationModelIds,proto3" json:"image_generation_model_ids,omitempty"`
	MqueryModelIds          []string                                 `protobuf:"bytes,7,rep,name=mquery_model_ids,json=mqueryModelIds,proto3" json:"mquery_model_ids,omitempty"`
	WebSearchModelIds       []string                                 `protobuf:"bytes,8,rep,name=web_search_model_ids,json=webSearchModelIds,proto3" json:"web_search_model_ids,omitempty"`
	DeprecatedModelIds      map[string]*DeprecatedModelReroutingInfo `protobuf:"bytes,9,rep,name=deprecated_model_ids,json=deprecatedModelIds,proto3" json:"deprecated_model_ids,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	CommitMessageModelIds   []string                                 `protobuf:"bytes,10,rep,name=commit_message_model_ids,json=commitMessageModelIds,proto3" json:"commit_message_model_ids,omitempty"`
	unknownFields           protoimpl.UnknownFields
	sizeCache               protoimpl.SizeCache
}

func (x *FetchAvailableModelsResponse) Reset() {
	*x = FetchAvailableModelsResponse{}
	mi := &file_google_internal_cloud_code_v1internal_model_configs_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FetchAvailableModelsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FetchAvailableModelsResponse) ProtoMessage() {}

func (x *FetchAvailableModelsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_google_internal_cloud_code_v1internal_model_configs_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FetchAvailableModelsResponse.ProtoReflect.Descriptor instead.
func (*FetchAvailableModelsResponse) Descriptor() ([]byte, []int) {
	return file_google_internal_cloud_code_v1internal_model_configs_proto_rawDescGZIP(), []int{6}
}

func (x *FetchAvailableModelsResponse) GetModels() map[string]*ModelDetails {
	if x != nil {
		return x.Models
	}
	return nil
}

func (x *FetchAvailableModelsResponse) GetDefaultAgentModelId() string {
	if x != nil {
		return x.DefaultAgentModelId
	}
	return ""
}

func (x *FetchAvailableModelsResponse) GetAgentModelSorts() []*ModelSort {
	if x != nil {
		return x.AgentModelSorts
	}
	return nil
}

func (x *FetchAvailableModelsResponse) GetCommandModelIds() []string {
	if x != nil {
		return x.CommandModelIds
	}
	return nil
}

func (x *FetchAvailableModelsResponse) GetTabModelIds() []string {
	if x != nil {
		return x.TabModelIds
	}
	return nil
}

func (x *FetchAvailableModelsResponse) GetImageGenerationModelIds() []string {
	if x != nil {
		return x.ImageGenerationModelIds
	}
	return nil
}

func (x *FetchAvailableModelsResponse) GetMqueryModelIds() []string {
	if x != nil {
		return x.MqueryModelIds
	}
	return nil
}

func (x *FetchAvailableModelsResponse) GetWebSearchModelIds() []string {
	if x != nil {
		return x.WebSearchModelIds
	}
	return nil
}

func (x *FetchAvailableModelsResponse) GetDeprecatedModelIds() map[string]*DeprecatedModelReroutingInfo {
	if x != nil {
		return x.DeprecatedModelIds
	}
	return nil
}

func (x *FetchAvailableModelsResponse) GetCommitMessageModelIds() []string {
	if x != nil {
		return x.CommitMessageModelIds
	}
	return nil
}

var File_google_internal_cloud_code_v1internal_model_configs_proto protoreflect.FileDescriptor

const file_google_internal_cloud_code_v1internal_model_configs_proto_rawDesc = "" +
	"\n" +
	"9google/internal/cloud/code/v1internal/model_configs.proto\x12%google.internal.cloud.code.v1internal\x1a\x1fgoogle/protobuf/timestamp.proto\x1a9third_party/jetski/codeium_common_pb/codeium_common.proto\"7\n" +
	"\x1bFetchAvailableModelsRequest\x12\x18\n" +
	"\aproject\x18\x01 \x01(\tR\aproject\"u\n" +
	"\tQuotaInfo\x12-\n" +
	"\x12remaining_fraction\x18\x01 \x01(\x02R\x11remainingFraction\x129\n" +
	"\n" +
	"reset_time\x18\x02 \x01(\v2\x1a.google.protobuf.TimestampR\tresetTime\"\xa9\x0f\n" +
	"\fModelDetails\x12!\n" +
	"\fdisplay_name\x18\x01 \x01(\tR\vdisplayName\x12'\n" +
	"\x0fsupports_images\x18\x02 \x01(\bR\x0esupportsImages\x12+\n" +
	"\x11supports_thinking\x18\x03 \x01(\bR\x10supportsThinking\x12'\n" +
	"\x0fthinking_budget\x18\x04 \x01(\x05R\x0ethinkingBudget\x12.\n" +
	"\x13min_thinking_budget\x18\x05 \x01(\x05R\x11minThinkingBudget\x12 \n" +
	"\vrecommended\x18\x06 \x01(\bR\vrecommended\x12\x1d\n" +
	"\n" +
	"max_tokens\x18\a \x01(\x05R\tmaxTokens\x12*\n" +
	"\x11max_output_tokens\x18\b \x01(\x05R\x0fmaxOutputTokens\x12%\n" +
	"\x0etokenizer_type\x18\t \x01(\tR\rtokenizerType\x12O\n" +
	"\n" +
	"quota_info\x18\n" +
	" \x01(\v20.google.internal.cloud.code.v1internal.QuotaInfoR\tquotaInfo\x120\n" +
	"\x14beta_warning_message\x18\v \x01(\tR\x12betaWarningMessage\x12\x12\n" +
	"\x04beta\x18\f \x01(\bR\x04beta\x12\x1a\n" +
	"\bdisabled\x18\r \x01(\bR\bdisabled\x12 \n" +
	"\vdescription\x18\x0e \x01(\tR\vdescription\x122\n" +
	"\x05model\x18\x0f \x01(\x0e2\x1c.exa.codeium_common_pb.ModelR\x05model\x12E\n" +
	"\fapi_provider\x18\x10 \x01(\x0e2\".exa.codeium_common_pb.APIProviderR\vapiProvider\x12K\n" +
	"\x0emodel_provider\x18\x11 \x01(\x0e2$.exa.codeium_common_pb.ModelProviderR\rmodelProvider\x12>\n" +
	"\x1bsupports_cumulative_context\x18\x12 \x01(\bR\x19supportsCumulativeContext\x128\n" +
	"\x19tab_jump_print_line_range\x18\x13 \x01(\bR\x15tabJumpPrintLineRange\x12E\n" +
	"\x1fsupports_estimate_token_counter\x18\x14 \x01(\bR\x1csupportsEstimateTokenCounter\x12\x1f\n" +
	"\vis_internal\x18\x15 \x01(\bR\n" +
	"isInternal\x12G\n" +
	"!add_cursor_to_find_replace_target\x18\x16 \x01(\bR\x1caddCursorToFindReplaceTarget\x12^\n" +
	"\x15prompt_templater_type\x18\x17 \x01(\x0e2*.exa.codeium_common_pb.PromptTemplaterTypeR\x13promptTemplaterType\x12X\n" +
	"\x13tool_formatter_type\x18\x18 \x01(\x0e2(.exa.codeium_common_pb.ToolFormatterTypeR\x11toolFormatterType\x122\n" +
	"\x15supports_raw_thinking\x18\x19 \x01(\bR\x13supportsRawThinking\x12%\n" +
	"\x0esupports_video\x18\x1a \x01(\bR\rsupportsVideo\x12!\n" +
	"\fsupports_pdf\x18\x1b \x01(\bR\vsupportsPdf\x12=\n" +
	"\x1brequires_lead_in_generation\x18\x1c \x01(\bR\x18requiresLeadInGeneration\x12\x1b\n" +
	"\ttag_title\x18\x1d \x01(\tR\btagTitle\x12'\n" +
	"\x0ftag_description\x18\x1e \x01(\tR\x0etagDescription\x12@\n" +
	"\x1drequires_no_xml_tool_examples\x18\x1f \x01(\bR\x19requiresNoXmlToolExamples\x12}\n" +
	"\x14supported_mime_types\x18  \x03(\v2K.google.internal.cloud.code.v1internal.ModelDetails.SupportedMimeTypesEntryR\x12supportedMimeTypes\x12e\n" +
	"0requires_image_output_outside_function_responses\x18! \x01(\bR+requiresImageOutputOutsideFunctionResponses\x12\x18\n" +
	"\apreview\x18\" \x01(\bR\apreview\x12%\n" +
	"\x0ethinking_level\x18# \x01(\x05R\rthinkingLevel\x1aE\n" +
	"\x17SupportedMimeTypesEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\bR\x05value:\x028\x01\"y\n" +
	"\tModelSort\x12!\n" +
	"\fdisplay_name\x18\x01 \x01(\tR\vdisplayName\x12I\n" +
	"\x06groups\x18\x02 \x03(\v21.google.internal.cloud.code.v1internal.ModelGroupR\x06groups\"L\n" +
	"\n" +
	"ModelGroup\x12!\n" +
	"\fdisplay_name\x18\x01 \x01(\tR\vdisplayName\x12\x1b\n" +
	"\tmodel_ids\x18\x02 \x03(\tR\bmodelIds\"\xc8\x01\n" +
	"\x1cDeprecatedModelReroutingInfo\x12 \n" +
	"\fnew_model_id\x18\x01 \x01(\tR\n" +
	"newModelId\x12B\n" +
	"\x0eold_model_enum\x18\x02 \x01(\x0e2\x1c.exa.codeium_common_pb.ModelR\foldModelEnum\x12B\n" +
	"\x0enew_model_enum\x18\x03 \x01(\x0e2\x1c.exa.codeium_common_pb.ModelR\fnewModelEnum\"\xc8\a\n" +
	"\x1cFetchAvailableModelsResponse\x12g\n" +
	"\x06models\x18\x01 \x03(\v2O.google.internal.cloud.code.v1internal.FetchAvailableModelsResponse.ModelsEntryR\x06models\x123\n" +
	"\x16default_agent_model_id\x18\x02 \x01(\tR\x13defaultAgentModelId\x12\\\n" +
	"\x11agent_model_sorts\x18\x03 \x03(\v20.google.internal.cloud.code.v1internal.ModelSortR\x0fagentModelSorts\x12*\n" +
	"\x11command_model_ids\x18\x04 \x03(\tR\x0fcommandModelIds\x12\"\n" +
	"\rtab_model_ids\x18\x05 \x03(\tR\vtabModelIds\x12;\n" +
	"\x1aimage_generation_model_ids\x18\x06 \x03(\tR\x17imageGenerationModelIds\x12(\n" +
	"\x10mquery_model_ids\x18\a \x03(\tR\x0emqueryModelIds\x12/\n" +
	"\x14web_search_model_ids\x18\b \x03(\tR\x11webSearchModelIds\x12\x8d\x01\n" +
	"\x14deprecated_model_ids\x18\t \x03(\v2[.google.internal.cloud.code.v1internal.FetchAvailableModelsResponse.DeprecatedModelIdsEntryR\x12deprecatedModelIds\x127\n" +
	"\x18commit_message_model_ids\x18\n" +
	" \x03(\tR\x15commitMessageModelIds\x1an\n" +
	"\vModelsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12I\n" +
	"\x05value\x18\x02 \x01(\v23.google.internal.cloud.code.v1internal.ModelDetailsR\x05value:\x028\x01\x1a\x8a\x01\n" +
	"\x17DeprecatedModelIdsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12Y\n" +
	"\x05value\x18\x02 \x01(\v2C.google.internal.cloud.code.v1internal.DeprecatedModelReroutingInfoR\x05value:\x028\x01BCZAgithub.com/router-for-me/CLIProxyAPI/v6/internal/proto/v1internalb\x06proto3"

var (
	file_google_internal_cloud_code_v1internal_model_configs_proto_rawDescOnce sync.Once
	file_google_internal_cloud_code_v1internal_model_configs_proto_rawDescData []byte
)

func file_google_internal_cloud_code_v1internal_model_configs_proto_rawDescGZIP() []byte {
	file_google_internal_cloud_code_v1internal_model_configs_proto_rawDescOnce.Do(func() {
		file_google_internal_cloud_code_v1internal_model_configs_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_google_internal_cloud_code_v1internal_model_configs_proto_rawDesc), len(file_google_internal_cloud_code_v1internal_model_configs_proto_rawDesc)))
	})
	return file_google_internal_cloud_code_v1internal_model_configs_proto_rawDescData
}

var file_google_internal_cloud_code_v1internal_model_configs_proto_msgTypes = make([]protoimpl.MessageInfo, 10)
var file_google_internal_cloud_code_v1internal_model_configs_proto_goTypes = []any{
	(*FetchAvailableModelsRequest)(nil),  // 0: google.internal.cloud.code.v1internal.FetchAvailableModelsRequest
	(*QuotaInfo)(nil),                    // 1: google.internal.cloud.code.v1internal.QuotaInfo
	(*ModelDetails)(nil),                 // 2: google.internal.cloud.code.v1internal.ModelDetails
	(*ModelSort)(nil),                    // 3: google.internal.cloud.code.v1internal.ModelSort
	(*ModelGroup)(nil),                   // 4: google.internal.cloud.code.v1internal.ModelGroup
	(*DeprecatedModelReroutingInfo)(nil), // 5: google.internal.cloud.code.v1internal.DeprecatedModelReroutingInfo
	(*FetchAvailableModelsResponse)(nil), // 6: google.internal.cloud.code.v1internal.FetchAvailableModelsResponse
	nil,                                  // 7: google.internal.cloud.code.v1internal.ModelDetails.SupportedMimeTypesEntry
	nil,                                  // 8: google.internal.cloud.code.v1internal.FetchAvailableModelsResponse.ModelsEntry
	nil,                                  // 9: google.internal.cloud.code.v1internal.FetchAvailableModelsResponse.DeprecatedModelIdsEntry
	(*timestamppb.Timestamp)(nil),        // 10: google.protobuf.Timestamp
	(codeium.Model)(0),                   // 11: exa.codeium_common_pb.Model
	(codeium.APIProvider)(0),             // 12: exa.codeium_common_pb.APIProvider
	(codeium.ModelProvider)(0),           // 13: exa.codeium_common_pb.ModelProvider
	(codeium.PromptTemplaterType)(0),     // 14: exa.codeium_common_pb.PromptTemplaterType
	(codeium.ToolFormatterType)(0),       // 15: exa.codeium_common_pb.ToolFormatterType
}
var file_google_internal_cloud_code_v1internal_model_configs_proto_depIdxs = []int32{
	10, // 0: google.internal.cloud.code.v1internal.QuotaInfo.reset_time:type_name -> google.protobuf.Timestamp
	1,  // 1: google.internal.cloud.code.v1internal.ModelDetails.quota_info:type_name -> google.internal.cloud.code.v1internal.QuotaInfo
	11, // 2: google.internal.cloud.code.v1internal.ModelDetails.model:type_name -> exa.codeium_common_pb.Model
	12, // 3: google.internal.cloud.code.v1internal.ModelDetails.api_provider:type_name -> exa.codeium_common_pb.APIProvider
	13, // 4: google.internal.cloud.code.v1internal.ModelDetails.model_provider:type_name -> exa.codeium_common_pb.ModelProvider
	14, // 5: google.internal.cloud.code.v1internal.ModelDetails.prompt_templater_type:type_name -> exa.codeium_common_pb.PromptTemplaterType
	15, // 6: google.internal.cloud.code.v1internal.ModelDetails.tool_formatter_type:type_name -> exa.codeium_common_pb.ToolFormatterType
	7,  // 7: google.internal.cloud.code.v1internal.ModelDetails.supported_mime_types:type_name -> google.internal.cloud.code.v1internal.ModelDetails.SupportedMimeTypesEntry
	4,  // 8: google.internal.cloud.code.v1internal.ModelSort.groups:type_name -> google.internal.cloud.code.v1internal.ModelGroup
	11, // 9: google.internal.cloud.code.v1internal.DeprecatedModelReroutingInfo.old_model_enum:type_name -> exa.codeium_common_pb.Model
	11, // 10: google.internal.cloud.code.v1internal.DeprecatedModelReroutingInfo.new_model_enum:type_name -> exa.codeium_common_pb.Model
	8,  // 11: google.internal.cloud.code.v1internal.FetchAvailableModelsResponse.models:type_name -> google.internal.cloud.code.v1internal.FetchAvailableModelsResponse.ModelsEntry
	3,  // 12: google.internal.cloud.code.v1internal.FetchAvailableModelsResponse.agent_model_sorts:type_name -> google.internal.cloud.code.v1internal.ModelSort
	9,  // 13: google.internal.cloud.code.v1internal.FetchAvailableModelsResponse.deprecated_model_ids:type_name -> google.internal.cloud.code.v1internal.FetchAvailableModelsResponse.DeprecatedModelIdsEntry
	2,  // 14: google.internal.cloud.code.v1internal.FetchAvailableModelsResponse.ModelsEntry.value:type_name -> google.internal.cloud.code.v1internal.ModelDetails
	5,  // 15: google.internal.cloud.code.v1internal.FetchAvailableModelsResponse.DeprecatedModelIdsEntry.value:type_name -> google.internal.cloud.code.v1internal.DeprecatedModelReroutingInfo
	16, // [16:16] is the sub-list for method output_type
	16, // [16:16] is the sub-list for method input_type
	16, // [16:16] is the sub-list for extension type_name
	16, // [16:16] is the sub-list for extension extendee
	0,  // [0:16] is the sub-list for field type_name
}

func init() { file_google_internal_cloud_code_v1internal_model_configs_proto_init() }
func file_google_internal_cloud_code_v1internal_model_configs_proto_init() {
	if File_google_internal_cloud_code_v1internal_model_configs_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_google_internal_cloud_code_v1internal_model_configs_proto_rawDesc), len(file_google_internal_cloud_code_v1internal_model_configs_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   10,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_google_internal_cloud_code_v1internal_model_configs_proto_goTypes,
		DependencyIndexes: file_google_internal_cloud_code_v1internal_model_configs_proto_depIdxs,
		MessageInfos:      file_google_internal_cloud_code_v1internal_model_configs_proto_msgTypes,
	}.Build()
	File_google_internal_cloud_code_v1internal_model_configs_proto = out.File
	file_google_internal_cloud_code_v1internal_model_configs_proto_goTypes = nil
	file_google_internal_cloud_code_v1internal_model_configs_proto_depIdxs = nil
}
