// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v4.25.1
// source: google/internal/cloud/code/v1internal/onboarding.proto

package v1internal

import (
	errdetails "google.golang.org/genproto/googleapis/rpc/errdetails"
	status "google.golang.org/genproto/googleapis/rpc/status"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ReleaseChannel_ChannelType int32

const (
	ReleaseChannel_UNKNOWN      ReleaseChannel_ChannelType = 0
	ReleaseChannel_STABLE       ReleaseChannel_ChannelType = 1
	ReleaseChannel_EXPERIMENTAL ReleaseChannel_ChannelType = 2
)

// Enum value maps for ReleaseChannel_ChannelType.
var (
	ReleaseChannel_ChannelType_name = map[int32]string{
		0: "UNKNOWN",
		1: "STABLE",
		2: "EXPERIMENTAL",
	}
	ReleaseChannel_ChannelType_value = map[string]int32{
		"UNKNOWN":      0,
		"STABLE":       1,
		"EXPERIMENTAL": 2,
	}
)

func (x ReleaseChannel_ChannelType) Enum() *ReleaseChannel_ChannelType {
	p := new(ReleaseChannel_ChannelType)
	*p = x
	return p
}

func (x ReleaseChannel_ChannelType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (ReleaseChannel_ChannelType) Descriptor() protoreflect.EnumDescriptor {
	return file_google_internal_cloud_code_v1internal_onboarding_proto_enumTypes[0].Descriptor()
}

func (ReleaseChannel_ChannelType) Type() protoreflect.EnumType {
	return &file_google_internal_cloud_code_v1internal_onboarding_proto_enumTypes[0]
}

func (x ReleaseChannel_ChannelType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use ReleaseChannel_ChannelType.Descriptor instead.
func (ReleaseChannel_ChannelType) EnumDescriptor() ([]byte, []int) {
	return file_google_internal_cloud_code_v1internal_onboarding_proto_rawDescGZIP(), []int{2, 0}
}

type LoadCodeAssistRequest_Mode int32

const (
	LoadCodeAssistRequest_MODE_UNSPECIFIED       LoadCodeAssistRequest_Mode = 0
	LoadCodeAssistRequest_FULL_ELIGIBILITY_CHECK LoadCodeAssistRequest_Mode = 1
	LoadCodeAssistRequest_HEALTH_CHECK           LoadCodeAssistRequest_Mode = 2
)

// Enum value maps for LoadCodeAssistRequest_Mode.
var (
	LoadCodeAssistRequest_Mode_name = map[int32]string{
		0: "MODE_UNSPECIFIED",
		1: "FULL_ELIGIBILITY_CHECK",
		2: "HEALTH_CHECK",
	}
	LoadCodeAssistRequest_Mode_value = map[string]int32{
		"MODE_UNSPECIFIED":       0,
		"FULL_ELIGIBILITY_CHECK": 1,
		"HEALTH_CHECK":           2,
	}
)

func (x LoadCodeAssistRequest_Mode) Enum() *LoadCodeAssistRequest_Mode {
	p := new(LoadCodeAssistRequest_Mode)
	*p = x
	return p
}

func (x LoadCodeAssistRequest_Mode) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (LoadCodeAssistRequest_Mode) Descriptor() protoreflect.EnumDescriptor {
	return file_google_internal_cloud_code_v1internal_onboarding_proto_enumTypes[1].Descriptor()
}

func (LoadCodeAssistRequest_Mode) Type() protoreflect.EnumType {
	return &file_google_internal_cloud_code_v1internal_onboarding_proto_enumTypes[1]
}

func (x LoadCodeAssistRequest_Mode) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use LoadCodeAssistRequest_Mode.Descriptor instead.
func (LoadCodeAssistRequest_Mode) EnumDescriptor() ([]byte, []int) {
	return file_google_internal_cloud_code_v1internal_onboarding_proto_rawDescGZIP(), []int{3, 0}
}

type IneligibleTier_IneligibleTierReasonCodes int32

const (
	IneligibleTier_UNKNOWN                            IneligibleTier_IneligibleTierReasonCodes = 0
	IneligibleTier_INELIGIBLE_ACCOUNT                 IneligibleTier_IneligibleTierReasonCodes = 1
	IneligibleTier_UNKNOWN_LOCATION                   IneligibleTier_IneligibleTierReasonCodes = 2
	IneligibleTier_UNSUPPORTED_LOCATION               IneligibleTier_IneligibleTierReasonCodes = 3
	IneligibleTier_RESTRICTED_NETWORK                 IneligibleTier_IneligibleTierReasonCodes = 4
	IneligibleTier_RESTRICTED_AGE                     IneligibleTier_IneligibleTierReasonCodes = 5
	IneligibleTier_NON_USER_ACCOUNT                   IneligibleTier_IneligibleTierReasonCodes = 6
	IneligibleTier_DASHER_USER                        IneligibleTier_IneligibleTierReasonCodes = 7
	IneligibleTier_BYOID_USER                         IneligibleTier_IneligibleTierReasonCodes = 8
	IneligibleTier_RESTRICTED_DASHER_USER             IneligibleTier_IneligibleTierReasonCodes = 9
	IneligibleTier_VALIDATION_REQUIRED                IneligibleTier_IneligibleTierReasonCodes = 10
	IneligibleTier_GOOGLE_TOS_NOT_SUPPORTED_BY_CLIENT IneligibleTier_IneligibleTierReasonCodes = 11
)

// Enum value maps for IneligibleTier_IneligibleTierReasonCodes.
var (
	IneligibleTier_IneligibleTierReasonCodes_name = map[int32]string{
		0:  "UNKNOWN",
		1:  "INELIGIBLE_ACCOUNT",
		2:  "UNKNOWN_LOCATION",
		3:  "UNSUPPORTED_LOCATION",
		4:  "RESTRICTED_NETWORK",
		5:  "RESTRICTED_AGE",
		6:  "NON_USER_ACCOUNT",
		7:  "DASHER_USER",
		8:  "BYOID_USER",
		9:  "RESTRICTED_DASHER_USER",
		10: "VALIDATION_REQUIRED",
		11: "GOOGLE_TOS_NOT_SUPPORTED_BY_CLIENT",
	}
	IneligibleTier_IneligibleTierReasonCodes_value = map[string]int32{
		"UNKNOWN":                            0,
		"INELIGIBLE_ACCOUNT":                 1,
		"UNKNOWN_LOCATION":                   2,
		"UNSUPPORTED_LOCATION":               3,
		"RESTRICTED_NETWORK":                 4,
		"RESTRICTED_AGE":                     5,
		"NON_USER_ACCOUNT":                   6,
		"DASHER_USER":                        7,
		"BYOID_USER":                         8,
		"RESTRICTED_DASHER_USER":             9,
		"VALIDATION_REQUIRED":                10,
		"GOOGLE_TOS_NOT_SUPPORTED_BY_CLIENT": 11,
	}
)

func (x IneligibleTier_IneligibleTierReasonCodes) Enum() *IneligibleTier_IneligibleTierReasonCodes {
	p := new(IneligibleTier_IneligibleTierReasonCodes)
	*p = x
	return p
}

func (x IneligibleTier_IneligibleTierReasonCodes) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (IneligibleTier_IneligibleTierReasonCodes) Descriptor() protoreflect.EnumDescriptor {
	return file_google_internal_cloud_code_v1internal_onboarding_proto_enumTypes[2].Descriptor()
}

func (IneligibleTier_IneligibleTierReasonCodes) Type() protoreflect.EnumType {
	return &file_google_internal_cloud_code_v1internal_onboarding_proto_enumTypes[2]
}

func (x IneligibleTier_IneligibleTierReasonCodes) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use IneligibleTier_IneligibleTierReasonCodes.Descriptor instead.
func (IneligibleTier_IneligibleTierReasonCodes) EnumDescriptor() ([]byte, []int) {
	return file_google_internal_cloud_code_v1internal_onboarding_proto_rawDescGZIP(), []int{4, 0}
}

type ClientMetadata_IdeType int32

const (
	ClientMetadata_IDE_UNSPECIFIED            ClientMetadata_IdeType = 0
	ClientMetadata_VSCODE                     ClientMetadata_IdeType = 1
	ClientMetadata_INTELLIJ                   ClientMetadata_IdeType = 2
	ClientMetadata_VSCODE_CLOUD_WORKSTATION   ClientMetadata_IdeType = 3
	ClientMetadata_INTELLIJ_CLOUD_WORKSTATION ClientMetadata_IdeType = 4
	ClientMetadata_CLOUD_SHELL                ClientMetadata_IdeType = 5
	ClientMetadata_CIDER                      ClientMetadata_IdeType = 6
	ClientMetadata_CLOUD_RUN                  ClientMetadata_IdeType = 7
	ClientMetadata_ANDROID_STUDIO             ClientMetadata_IdeType = 8
	ClientMetadata_ANTIGRAVITY                ClientMetadata_IdeType = 9
	ClientMetadata_JETSKI                     ClientMetadata_IdeType = 10
	ClientMetadata_COLAB                      ClientMetadata_IdeType = 11
	ClientMetadata_FIREBASE                   ClientMetadata_IdeType = 12
	ClientMetadata_CHROME_DEVTOOLS            ClientMetadata_IdeType = 13
	ClientMetadata_GEMINI_CLI                 ClientMetadata_IdeType = 14
)

// Enum value maps for ClientMetadata_IdeType.
var (
	ClientMetadata_IdeType_name = map[int32]string{
		0:  "IDE_UNSPECIFIED",
		1:  "VSCODE",
		2:  "INTELLIJ",
		3:  "VSCODE_CLOUD_WORKSTATION",
		4:  "INTELLIJ_CLOUD_WORKSTATION",
		5:  "CLOUD_SHELL",
		6:  "CIDER",
		7:  "CLOUD_RUN",
		8:  "ANDROID_STUDIO",
		9:  "ANTIGRAVITY",
		10: "JETSKI",
		11: "COLAB",
		12: "FIREBASE",
		13: "CHROME_DEVTOOLS",
		14: "GEMINI_CLI",
	}
	ClientMetadata_IdeType_value = map[string]int32{
		"IDE_UNSPECIFIED":            0,
		"VSCODE":                     1,
		"INTELLIJ":                   2,
		"VSCODE_CLOUD_WORKSTATION":   3,
		"INTELLIJ_CLOUD_WORKSTATION": 4,
		"CLOUD_SHELL":                5,
		"CIDER":                      6,
		"CLOUD_RUN":                  7,
		"ANDROID_STUDIO":             8,
		"ANTIGRAVITY":                9,
		"JETSKI":                     10,
		"COLAB":                      11,
		"FIREBASE":                   12,
		"CHROME_DEVTOOLS":            13,
		"GEMINI_CLI":                 14,
	}
)

func (x ClientMetadata_IdeType) Enum() *ClientMetadata_IdeType {
	p := new(ClientMetadata_IdeType)
	*p = x
	return p
}

func (x ClientMetadata_IdeType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (ClientMetadata_IdeType) Descriptor() protoreflect.EnumDescriptor {
	return file_google_internal_cloud_code_v1internal_onboarding_proto_enumTypes[3].Descriptor()
}

func (ClientMetadata_IdeType) Type() protoreflect.EnumType {
	return &file_google_internal_cloud_code_v1internal_onboarding_proto_enumTypes[3]
}

func (x ClientMetadata_IdeType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use ClientMetadata_IdeType.Descriptor instead.
func (ClientMetadata_IdeType) EnumDescriptor() ([]byte, []int) {
	return file_google_internal_cloud_code_v1internal_onboarding_proto_rawDescGZIP(), []int{5, 0}
}

type ClientMetadata_Platform int32

const (
	ClientMetadata_PLATFORM_UNSPECIFIED ClientMetadata_Platform = 0
	ClientMetadata_DARWIN_AMD64         ClientMetadata_Platform = 1
	ClientMetadata_DARWIN_ARM64         ClientMetadata_Platform = 2
	ClientMetadata_LINUX_AMD64          ClientMetadata_Platform = 3
	ClientMetadata_LINUX_ARM64          ClientMetadata_Platform = 4
	ClientMetadata_WINDOWS_AMD64        ClientMetadata_Platform = 5
)

// Enum value maps for ClientMetadata_Platform.
var (
	ClientMetadata_Platform_name = map[int32]string{
		0: "PLATFORM_UNSPECIFIED",
		1: "DARWIN_AMD64",
		2: "DARWIN_ARM64",
		3: "LINUX_AMD64",
		4: "LINUX_ARM64",
		5: "WINDOWS_AMD64",
	}
	ClientMetadata_Platform_value = map[string]int32{
		"PLATFORM_UNSPECIFIED": 0,
		"DARWIN_AMD64":         1,
		"DARWIN_ARM64":         2,
		"LINUX_AMD64":          3,
		"LINUX_ARM64":          4,
		"WINDOWS_AMD64":        5,
	}
)

func (x ClientMetadata_Platform) Enum() *ClientMetadata_Platform {
	p := new(ClientMetadata_Platform)
	*p = x
	return p
}

func (x ClientMetadata_Platform) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (ClientMetadata_Platform) Descriptor() protoreflect.EnumDescriptor {
	return file_google_internal_cloud_code_v1internal_onboarding_proto_enumTypes[4].Descriptor()
}

func (ClientMetadata_Platform) Type() protoreflect.EnumType {
	return &file_google_internal_cloud_code_v1internal_onboarding_proto_enumTypes[4]
}

func (x ClientMetadata_Platform) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use ClientMetadata_Platform.Descriptor instead.
func (ClientMetadata_Platform) EnumDescriptor() ([]byte, []int) {
	return file_google_internal_cloud_code_v1internal_onboarding_proto_rawDescGZIP(), []int{5, 1}
}

type ClientMetadata_PluginType int32

const (
	ClientMetadata_PLUGIN_UNSPECIFIED ClientMetadata_PluginType = 0
	ClientMetadata_CLOUD_CODE         ClientMetadata_PluginType = 1
	ClientMetadata_GEMINI             ClientMetadata_PluginType = 2
	ClientMetadata_AIPLUGIN_INTELLIJ  ClientMetadata_PluginType = 3
	ClientMetadata_AIPLUGIN_STUDIO    ClientMetadata_PluginType = 4
	ClientMetadata_PANTHEON           ClientMetadata_PluginType = 6
)

// Enum value maps for ClientMetadata_PluginType.
var (
	ClientMetadata_PluginType_name = map[int32]string{
		0: "PLUGIN_UNSPECIFIED",
		1: "CLOUD_CODE",
		2: "GEMINI",
		3: "AIPLUGIN_INTELLIJ",
		4: "AIPLUGIN_STUDIO",
		6: "PANTHEON",
	}
	ClientMetadata_PluginType_value = map[string]int32{
		"PLUGIN_UNSPECIFIED": 0,
		"CLOUD_CODE":         1,
		"GEMINI":             2,
		"AIPLUGIN_INTELLIJ":  3,
		"AIPLUGIN_STUDIO":    4,
		"PANTHEON":           6,
	}
)

func (x ClientMetadata_PluginType) Enum() *ClientMetadata_PluginType {
	p := new(ClientMetadata_PluginType)
	*p = x
	return p
}

func (x ClientMetadata_PluginType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (ClientMetadata_PluginType) Descriptor() protoreflect.EnumDescriptor {
	return file_google_internal_cloud_code_v1internal_onboarding_proto_enumTypes[5].Descriptor()
}

func (ClientMetadata_PluginType) Type() protoreflect.EnumType {
	return &file_google_internal_cloud_code_v1internal_onboarding_proto_enumTypes[5]
}

func (x ClientMetadata_PluginType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use ClientMetadata_PluginType.Descriptor instead.
func (ClientMetadata_PluginType) EnumDescriptor() ([]byte, []int) {
	return file_google_internal_cloud_code_v1internal_onboarding_proto_rawDescGZIP(), []int{5, 2}
}

type OnboardUserStatus_StatusCode int32

const (
	OnboardUserStatus_DEFAULT OnboardUserStatus_StatusCode = 0
	OnboardUserStatus_NOTICE  OnboardUserStatus_StatusCode = 1
	OnboardUserStatus_WARNING OnboardUserStatus_StatusCode = 2
)

// Enum value maps for OnboardUserStatus_StatusCode.
var (
	OnboardUserStatus_StatusCode_name = map[int32]string{
		0: "DEFAULT",
		1: "NOTICE",
		2: "WARNING",
	}
	OnboardUserStatus_StatusCode_value = map[string]int32{
		"DEFAULT": 0,
		"NOTICE":  1,
		"WARNING": 2,
	}
)

func (x OnboardUserStatus_StatusCode) Enum() *OnboardUserStatus_StatusCode {
	p := new(OnboardUserStatus_StatusCode)
	*p = x
	return p
}

func (x OnboardUserStatus_StatusCode) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (OnboardUserStatus_StatusCode) Descriptor() protoreflect.EnumDescriptor {
	return file_google_internal_cloud_code_v1internal_onboarding_proto_enumTypes[6].Descriptor()
}

func (OnboardUserStatus_StatusCode) Type() protoreflect.EnumType {
	return &file_google_internal_cloud_code_v1internal_onboarding_proto_enumTypes[6]
}

func (x OnboardUserStatus_StatusCode) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use OnboardUserStatus_StatusCode.Descriptor instead.
func (OnboardUserStatus_StatusCode) EnumDescriptor() ([]byte, []int) {
	return file_google_internal_cloud_code_v1internal_onboarding_proto_rawDescGZIP(), []int{7, 0}
}

type UserTier_UpgradeType int32

const (
	UserTier_UPGRADE_TYPE_UNSPECIFIED UserTier_UpgradeType = 0
	UserTier_GDP                      UserTier_UpgradeType = 1
	UserTier_GOOGLE_ONE               UserTier_UpgradeType = 2
	UserTier_GDP_HELIUM               UserTier_UpgradeType = 3
	UserTier_GOOGLE_ONE_HELIUM        UserTier_UpgradeType = 4
)

// Enum value maps for UserTier_UpgradeType.
var (
	UserTier_UpgradeType_name = map[int32]string{
		0: "UPGRADE_TYPE_UNSPECIFIED",
		1: "GDP",
		2: "GOOGLE_ONE",
		3: "GDP_HELIUM",
		4: "GOOGLE_ONE_HELIUM",
	}
	UserTier_UpgradeType_value = map[string]int32{
		"UPGRADE_TYPE_UNSPECIFIED": 0,
		"GDP":                      1,
		"GOOGLE_ONE":               2,
		"GDP_HELIUM":               3,
		"GOOGLE_ONE_HELIUM":        4,
	}
)

func (x UserTier_UpgradeType) Enum() *UserTier_UpgradeType {
	p := new(UserTier_UpgradeType)
	*p = x
	return p
}

func (x UserTier_UpgradeType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (UserTier_UpgradeType) Descriptor() protoreflect.EnumDescriptor {
	return file_google_internal_cloud_code_v1internal_onboarding_proto_enumTypes[7].Descriptor()
}

func (UserTier_UpgradeType) Type() protoreflect.EnumType {
	return &file_google_internal_cloud_code_v1internal_onboarding_proto_enumTypes[7]
}

func (x UserTier_UpgradeType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use UserTier_UpgradeType.Descriptor instead.
func (UserTier_UpgradeType) EnumDescriptor() ([]byte, []int) {
	return file_google_internal_cloud_code_v1internal_onboarding_proto_rawDescGZIP(), []int{9, 0}
}

type FetchAdminControlsResponse_GroundingType int32

const (
	FetchAdminControlsResponse_GROUNDING_TYPE_UNSPECIFIED   FetchAdminControlsResponse_GroundingType = 0
	FetchAdminControlsResponse_GROUNDING_WITH_GOOGLE_SEARCH FetchAdminControlsResponse_GroundingType = 1
	FetchAdminControlsResponse_WEB_GROUNDING_FOR_ENTERPRISE FetchAdminControlsResponse_GroundingType = 2
)

// Enum value maps for FetchAdminControlsResponse_GroundingType.
var (
	FetchAdminControlsResponse_GroundingType_name = map[int32]string{
		0: "GROUNDING_TYPE_UNSPECIFIED",
		1: "GROUNDING_WITH_GOOGLE_SEARCH",
		2: "WEB_GROUNDING_FOR_ENTERPRISE",
	}
	FetchAdminControlsResponse_GroundingType_value = map[string]int32{
		"GROUNDING_TYPE_UNSPECIFIED":   0,
		"GROUNDING_WITH_GOOGLE_SEARCH": 1,
		"WEB_GROUNDING_FOR_ENTERPRISE": 2,
	}
)

func (x FetchAdminControlsResponse_GroundingType) Enum() *FetchAdminControlsResponse_GroundingType {
	p := new(FetchAdminControlsResponse_GroundingType)
	*p = x
	return p
}

func (x FetchAdminControlsResponse_GroundingType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (FetchAdminControlsResponse_GroundingType) Descriptor() protoreflect.EnumDescriptor {
	return file_google_internal_cloud_code_v1internal_onboarding_proto_enumTypes[8].Descriptor()
}

func (FetchAdminControlsResponse_GroundingType) Type() protoreflect.EnumType {
	return &file_google_internal_cloud_code_v1internal_onboarding_proto_enumTypes[8]
}

func (x FetchAdminControlsResponse_GroundingType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use FetchAdminControlsResponse_GroundingType.Descriptor instead.
func (FetchAdminControlsResponse_GroundingType) EnumDescriptor() ([]byte, []int) {
	return file_google_internal_cloud_code_v1internal_onboarding_proto_rawDescGZIP(), []int{19, 0}
}

type OnboardUserRequest struct {
	state                   protoimpl.MessageState `protogen:"open.v1"`
	TierId                  string                 `protobuf:"bytes,1,opt,name=tier_id,json=tierId,proto3" json:"tier_id,omitempty"`
	CloudaicompanionProject *string                `protobuf:"bytes,2,opt,name=cloudaicompanion_project,json=cloudaicompanionProject,proto3,oneof" json:"cloudaicompanion_project,omitempty"`
	Metadata                *ClientMetadata        `protobuf:"bytes,3,opt,name=metadata,proto3" json:"metadata,omitempty"`
	unknownFields           protoimpl.UnknownFields
	sizeCache               protoimpl.SizeCache
}

func (x *OnboardUserRequest) Reset() {
	*x = OnboardUserRequest{}
	mi := &file_google_internal_cloud_code_v1internal_onboarding_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *OnboardUserRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OnboardUserRequest) ProtoMessage() {}

func (x *OnboardUserRequest) ProtoReflect() protoreflect.Message {
	mi := &file_google_internal_cloud_code_v1internal_onboarding_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OnboardUserRequest.ProtoReflect.Descriptor instead.
func (*OnboardUserRequest) Descriptor() ([]byte, []int) {
	return file_google_internal_cloud_code_v1internal_onboarding_proto_rawDescGZIP(), []int{0}
}

func (x *OnboardUserRequest) GetTierId() string {
	if x != nil {
		return x.TierId
	}
	return ""
}

func (x *OnboardUserRequest) GetCloudaicompanionProject() string {
	if x != nil && x.CloudaicompanionProject != nil {
		return *x.CloudaicompanionProject
	}
	return ""
}

func (x *OnboardUserRequest) GetMetadata() *ClientMetadata {
	if x != nil {
		return x.Metadata
	}
	return nil
}

type OnboardUserResponse struct {
	state                   protoimpl.MessageState `protogen:"open.v1"`
	CloudaicompanionProject *Project               `protobuf:"bytes,1,opt,name=cloudaicompanion_project,json=cloudaicompanionProject,proto3" json:"cloudaicompanion_project,omitempty"`
	Status                  *OnboardUserStatus     `protobuf:"bytes,4,opt,name=status,proto3,oneof" json:"status,omitempty"`
	ReleaseChannel          *ReleaseChannel        `protobuf:"bytes,5,opt,name=release_channel,json=releaseChannel,proto3,oneof" json:"release_channel,omitempty"`
	unknownFields           protoimpl.UnknownFields
	sizeCache               protoimpl.SizeCache
}

func (x *OnboardUserResponse) Reset() {
	*x = OnboardUserResponse{}
	mi := &file_google_internal_cloud_code_v1internal_onboarding_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *OnboardUserResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OnboardUserResponse) ProtoMessage() {}

func (x *OnboardUserResponse) ProtoReflect() protoreflect.Message {
	mi := &file_google_internal_cloud_code_v1internal_onboarding_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OnboardUserResponse.ProtoReflect.Descriptor instead.
func (*OnboardUserResponse) Descriptor() ([]byte, []int) {
	return file_google_internal_cloud_code_v1internal_onboarding_proto_rawDescGZIP(), []int{1}
}

func (x *OnboardUserResponse) GetCloudaicompanionProject() *Project {
	if x != nil {
		return x.CloudaicompanionProject
	}
	return nil
}

func (x *OnboardUserResponse) GetStatus() *OnboardUserStatus {
	if x != nil {
		return x.Status
	}
	return nil
}

func (x *OnboardUserResponse) GetReleaseChannel() *ReleaseChannel {
	if x != nil {
		return x.ReleaseChannel
	}
	return nil
}

type ReleaseChannel struct {
	state         protoimpl.MessageState     `protogen:"open.v1"`
	Type          ReleaseChannel_ChannelType `protobuf:"varint,1,opt,name=type,proto3,enum=google.internal.cloud.code.v1internal.ReleaseChannel_ChannelType" json:"type,omitempty"`
	Name          string                     `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Description   string                     `protobuf:"bytes,3,opt,name=description,proto3" json:"description,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ReleaseChannel) Reset() {
	*x = ReleaseChannel{}
	mi := &file_google_internal_cloud_code_v1internal_onboarding_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReleaseChannel) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReleaseChannel) ProtoMessage() {}

func (x *ReleaseChannel) ProtoReflect() protoreflect.Message {
	mi := &file_google_internal_cloud_code_v1internal_onboarding_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReleaseChannel.ProtoReflect.Descriptor instead.
func (*ReleaseChannel) Descriptor() ([]byte, []int) {
	return file_google_internal_cloud_code_v1internal_onboarding_proto_rawDescGZIP(), []int{2}
}

func (x *ReleaseChannel) GetType() ReleaseChannel_ChannelType {
	if x != nil {
		return x.Type
	}
	return ReleaseChannel_UNKNOWN
}

func (x *ReleaseChannel) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *ReleaseChannel) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

type LoadCodeAssistRequest struct {
	state                   protoimpl.MessageState      `protogen:"open.v1"`
	CloudaicompanionProject *string                     `protobuf:"bytes,1,opt,name=cloudaicompanion_project,json=cloudaicompanionProject,proto3,oneof" json:"cloudaicompanion_project,omitempty"`
	Metadata                *ClientMetadata             `protobuf:"bytes,2,opt,name=metadata,proto3" json:"metadata,omitempty"`
	Mode                    *LoadCodeAssistRequest_Mode `protobuf:"varint,3,opt,name=mode,proto3,enum=google.internal.cloud.code.v1internal.LoadCodeAssistRequest_Mode,oneof" json:"mode,omitempty"`
	unknownFields           protoimpl.UnknownFields
	sizeCache               protoimpl.SizeCache
}

func (x *LoadCodeAssistRequest) Reset() {
	*x = LoadCodeAssistRequest{}
	mi := &file_google_internal_cloud_code_v1internal_onboarding_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LoadCodeAssistRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LoadCodeAssistRequest) ProtoMessage() {}

func (x *LoadCodeAssistRequest) ProtoReflect() protoreflect.Message {
	mi := &file_google_internal_cloud_code_v1internal_onboarding_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LoadCodeAssistRequest.ProtoReflect.Descriptor instead.
func (*LoadCodeAssistRequest) Descriptor() ([]byte, []int) {
	return file_google_internal_cloud_code_v1internal_onboarding_proto_rawDescGZIP(), []int{3}
}

func (x *LoadCodeAssistRequest) GetCloudaicompanionProject() string {
	if x != nil && x.CloudaicompanionProject != nil {
		return *x.CloudaicompanionProject
	}
	return ""
}

func (x *LoadCodeAssistRequest) GetMetadata() *ClientMetadata {
	if x != nil {
		return x.Metadata
	}
	return nil
}

func (x *LoadCodeAssistRequest) GetMode() LoadCodeAssistRequest_Mode {
	if x != nil && x.Mode != nil {
		return *x.Mode
	}
	return LoadCodeAssistRequest_MODE_UNSPECIFIED
}

type IneligibleTier struct {
	state                       protoimpl.MessageState                   `protogen:"open.v1"`
	ReasonCode                  IneligibleTier_IneligibleTierReasonCodes `protobuf:"varint,1,opt,name=reason_code,json=reasonCode,proto3,enum=google.internal.cloud.code.v1internal.IneligibleTier_IneligibleTierReasonCodes" json:"reason_code,omitempty"`
	ReasonMessage               string                                   `protobuf:"bytes,2,opt,name=reason_message,json=reasonMessage,proto3" json:"reason_message,omitempty"`
	TierId                      string                                   `protobuf:"bytes,3,opt,name=tier_id,json=tierId,proto3" json:"tier_id,omitempty"`
	TierName                    string                                   `protobuf:"bytes,4,opt,name=tier_name,json=tierName,proto3" json:"tier_name,omitempty"`
	ValidationErrorMessage      string                                   `protobuf:"bytes,5,opt,name=validation_error_message,json=validationErrorMessage,proto3" json:"validation_error_message,omitempty"`
	ValidationUrlLinkText       string                                   `protobuf:"bytes,6,opt,name=validation_url_link_text,json=validationUrlLinkText,proto3" json:"validation_url_link_text,omitempty"`
	ValidationUrl               string                                   `protobuf:"bytes,7,opt,name=validation_url,json=validationUrl,proto3" json:"validation_url,omitempty"`
	ValidationLearnMoreLinkText string                                   `protobuf:"bytes,8,opt,name=validation_learn_more_link_text,json=validationLearnMoreLinkText,proto3" json:"validation_learn_more_link_text,omitempty"`
	ValidationLearnMoreUrl      string                                   `protobuf:"bytes,9,opt,name=validation_learn_more_url,json=validationLearnMoreUrl,proto3" json:"validation_learn_more_url,omitempty"`
	unknownFields               protoimpl.UnknownFields
	sizeCache                   protoimpl.SizeCache
}

func (x *IneligibleTier) Reset() {
	*x = IneligibleTier{}
	mi := &file_google_internal_cloud_code_v1internal_onboarding_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *IneligibleTier) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*IneligibleTier) ProtoMessage() {}

func (x *IneligibleTier) ProtoReflect() protoreflect.Message {
	mi := &file_google_internal_cloud_code_v1internal_onboarding_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use IneligibleTier.ProtoReflect.Descriptor instead.
func (*IneligibleTier) Descriptor() ([]byte, []int) {
	return file_google_internal_cloud_code_v1internal_onboarding_proto_rawDescGZIP(), []int{4}
}

func (x *IneligibleTier) GetReasonCode() IneligibleTier_IneligibleTierReasonCodes {
	if x != nil {
		return x.ReasonCode
	}
	return IneligibleTier_UNKNOWN
}

func (x *IneligibleTier) GetReasonMessage() string {
	if x != nil {
		return x.ReasonMessage
	}
	return ""
}

func (x *IneligibleTier) GetTierId() string {
	if x != nil {
		return x.TierId
	}
	return ""
}

func (x *IneligibleTier) GetTierName() string {
	if x != nil {
		return x.TierName
	}
	return ""
}

func (x *IneligibleTier) GetValidationErrorMessage() string {
	if x != nil {
		return x.ValidationErrorMessage
	}
	return ""
}

func (x *IneligibleTier) GetValidationUrlLinkText() string {
	if x != nil {
		return x.ValidationUrlLinkText
	}
	return ""
}

func (x *IneligibleTier) GetValidationUrl() string {
	if x != nil {
		return x.ValidationUrl
	}
	return ""
}

func (x *IneligibleTier) GetValidationLearnMoreLinkText() string {
	if x != nil {
		return x.ValidationLearnMoreLinkText
	}
	return ""
}

func (x *IneligibleTier) GetValidationLearnMoreUrl() string {
	if x != nil {
		return x.ValidationLearnMoreUrl
	}
	return ""
}

type ClientMetadata struct {
	state         protoimpl.MessageState    `protogen:"open.v1"`
	IdeType       ClientMetadata_IdeType    `protobuf:"varint,1,opt,name=ide_type,json=ideType,proto3,enum=google.internal.cloud.code.v1internal.ClientMetadata_IdeType" json:"ide_type,omitempty"`
	IdeVersion    string                    `protobuf:"bytes,2,opt,name=ide_version,json=ideVersion,proto3" json:"ide_version,omitempty"`
	PluginVersion string                    `protobuf:"bytes,3,opt,name=plugin_version,json=pluginVersion,proto3" json:"plugin_version,omitempty"`
	Platform      ClientMetadata_Platform   `protobuf:"varint,4,opt,name=platform,proto3,enum=google.internal.cloud.code.v1internal.ClientMetadata_Platform" json:"platform,omitempty"`
	UpdateChannel string                    `protobuf:"bytes,5,opt,name=update_channel,json=updateChannel,proto3" json:"update_channel,omitempty"`
	DuetProject   string                    `protobuf:"bytes,6,opt,name=duet_project,json=duetProject,proto3" json:"duet_project,omitempty"`
	PluginType    ClientMetadata_PluginType `protobuf:"varint,7,opt,name=plugin_type,json=pluginType,proto3,enum=google.internal.cloud.code.v1internal.ClientMetadata_PluginType" json:"plugin_type,omitempty"`
	IdeName       string                    `protobuf:"bytes,8,opt,name=ide_name,json=ideName,proto3" json:"ide_name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ClientMetadata) Reset() {
	*x = ClientMetadata{}
	mi := &file_google_internal_cloud_code_v1internal_onboarding_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ClientMetadata) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ClientMetadata) ProtoMessage() {}

func (x *ClientMetadata) ProtoReflect() protoreflect.Message {
	mi := &file_google_internal_cloud_code_v1internal_onboarding_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ClientMetadata.ProtoReflect.Descriptor instead.
func (*ClientMetadata) Descriptor() ([]byte, []int) {
	return file_google_internal_cloud_code_v1internal_onboarding_proto_rawDescGZIP(), []int{5}
}

func (x *ClientMetadata) GetIdeType() ClientMetadata_IdeType {
	if x != nil {
		return x.IdeType
	}
	return ClientMetadata_IDE_UNSPECIFIED
}

func (x *ClientMetadata) GetIdeVersion() string {
	if x != nil {
		return x.IdeVersion
	}
	return ""
}

func (x *ClientMetadata) GetPluginVersion() string {
	if x != nil {
		return x.PluginVersion
	}
	return ""
}

func (x *ClientMetadata) GetPlatform() ClientMetadata_Platform {
	if x != nil {
		return x.Platform
	}
	return ClientMetadata_PLATFORM_UNSPECIFIED
}

func (x *ClientMetadata) GetUpdateChannel() string {
	if x != nil {
		return x.UpdateChannel
	}
	return ""
}

func (x *ClientMetadata) GetDuetProject() string {
	if x != nil {
		return x.DuetProject
	}
	return ""
}

func (x *ClientMetadata) GetPluginType() ClientMetadata_PluginType {
	if x != nil {
		return x.PluginType
	}
	return ClientMetadata_PLUGIN_UNSPECIFIED
}

func (x *ClientMetadata) GetIdeName() string {
	if x != nil {
		return x.IdeName
	}
	return ""
}

type Project struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	ProjectNumber int64                  `protobuf:"varint,3,opt,name=project_number,json=projectNumber,proto3" json:"project_number,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Project) Reset() {
	*x = Project{}
	mi := &file_google_internal_cloud_code_v1internal_onboarding_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Project) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Project) ProtoMessage() {}

func (x *Project) ProtoReflect() protoreflect.Message {
	mi := &file_google_internal_cloud_code_v1internal_onboarding_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Project.ProtoReflect.Descriptor instead.
func (*Project) Descriptor() ([]byte, []int) {
	return file_google_internal_cloud_code_v1internal_onboarding_proto_rawDescGZIP(), []int{6}
}

func (x *Project) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Project) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Project) GetProjectNumber() int64 {
	if x != nil {
		return x.ProjectNumber
	}
	return 0
}

type OnboardUserStatus struct {
	state          protoimpl.MessageState       `protogen:"open.v1"`
	StatusCode     OnboardUserStatus_StatusCode `protobuf:"varint,1,opt,name=status_code,json=statusCode,proto3,enum=google.internal.cloud.code.v1internal.OnboardUserStatus_StatusCode" json:"status_code,omitempty"`
	DisplayMessage string                       `protobuf:"bytes,2,opt,name=display_message,json=displayMessage,proto3" json:"display_message,omitempty"`
	HelpLink       *errdetails.Help_Link        `protobuf:"bytes,3,opt,name=help_link,json=helpLink,proto3,oneof" json:"help_link,omitempty"`
	MessageTitle   string                       `protobuf:"bytes,4,opt,name=message_title,json=messageTitle,proto3" json:"message_title,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *OnboardUserStatus) Reset() {
	*x = OnboardUserStatus{}
	mi := &file_google_internal_cloud_code_v1internal_onboarding_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *OnboardUserStatus) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OnboardUserStatus) ProtoMessage() {}

func (x *OnboardUserStatus) ProtoReflect() protoreflect.Message {
	mi := &file_google_internal_cloud_code_v1internal_onboarding_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OnboardUserStatus.ProtoReflect.Descriptor instead.
func (*OnboardUserStatus) Descriptor() ([]byte, []int) {
	return file_google_internal_cloud_code_v1internal_onboarding_proto_rawDescGZIP(), []int{7}
}

func (x *OnboardUserStatus) GetStatusCode() OnboardUserStatus_StatusCode {
	if x != nil {
		return x.StatusCode
	}
	return OnboardUserStatus_DEFAULT
}

func (x *OnboardUserStatus) GetDisplayMessage() string {
	if x != nil {
		return x.DisplayMessage
	}
	return ""
}

func (x *OnboardUserStatus) GetHelpLink() *errdetails.Help_Link {
	if x != nil {
		return x.HelpLink
	}
	return nil
}

func (x *OnboardUserStatus) GetMessageTitle() string {
	if x != nil {
		return x.MessageTitle
	}
	return ""
}

type LoadCodeAssistResponse struct {
	state                   protoimpl.MessageState `protogen:"open.v1"`
	CurrentTier             *UserTier              `protobuf:"bytes,1,opt,name=current_tier,json=currentTier,proto3" json:"current_tier,omitempty"`
	AllowedTiers            []*UserTier            `protobuf:"bytes,2,rep,name=allowed_tiers,json=allowedTiers,proto3" json:"allowed_tiers,omitempty"`
	CloudaicompanionProject *string                `protobuf:"bytes,3,opt,name=cloudaicompanion_project,json=cloudaicompanionProject,proto3,oneof" json:"cloudaicompanion_project,omitempty"`
	ProjectValidationError  *status.Status         `protobuf:"bytes,4,opt,name=project_validation_error,json=projectValidationError,proto3,oneof" json:"project_validation_error,omitempty"`
	IneligibleTiers         []*IneligibleTier      `protobuf:"bytes,5,rep,name=ineligible_tiers,json=ineligibleTiers,proto3" json:"ineligible_tiers,omitempty"`
	GcpManaged              *bool                  `protobuf:"varint,6,opt,name=gcp_managed,json=gcpManaged,proto3,oneof" json:"gcp_managed,omitempty"`
	ManageSubscriptionUri   *string                `protobuf:"bytes,7,opt,name=manage_subscription_uri,json=manageSubscriptionUri,proto3,oneof" json:"manage_subscription_uri,omitempty"`
	ReleaseChannel          *ReleaseChannel        `protobuf:"bytes,8,opt,name=release_channel,json=releaseChannel,proto3,oneof" json:"release_channel,omitempty"`
	UpgradeSubscriptionUri  *string                `protobuf:"bytes,9,opt,name=upgrade_subscription_uri,json=upgradeSubscriptionUri,proto3,oneof" json:"upgrade_subscription_uri,omitempty"`
	G1Tier                  *string                `protobuf:"bytes,11,opt,name=g1_tier,json=g1Tier,proto3,oneof" json:"g1_tier,omitempty"`
	PaidTier                *UserTier              `protobuf:"bytes,12,opt,name=paid_tier,json=paidTier,proto3" json:"paid_tier,omitempty"`
	unknownFields           protoimpl.UnknownFields
	sizeCache               protoimpl.SizeCache
}

func (x *LoadCodeAssistResponse) Reset() {
	*x = LoadCodeAssistResponse{}
	mi := &file_google_internal_cloud_code_v1internal_onboarding_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LoadCodeAssistResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LoadCodeAssistResponse) ProtoMessage() {}

func (x *LoadCodeAssistResponse) ProtoReflect() protoreflect.Message {
	mi := &file_google_internal_cloud_code_v1internal_onboarding_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LoadCodeAssistResponse.ProtoReflect.Descriptor instead.
func (*LoadCodeAssistResponse) Descriptor() ([]byte, []int) {
	return file_google_internal_cloud_code_v1internal_onboarding_proto_rawDescGZIP(), []int{8}
}

func (x *LoadCodeAssistResponse) GetCurrentTier() *UserTier {
	if x != nil {
		return x.CurrentTier
	}
	return nil
}

func (x *LoadCodeAssistResponse) GetAllowedTiers() []*UserTier {
	if x != nil {
		return x.AllowedTiers
	}
	return nil
}

func (x *LoadCodeAssistResponse) GetCloudaicompanionProject() string {
	if x != nil && x.CloudaicompanionProject != nil {
		return *x.CloudaicompanionProject
	}
	return ""
}

func (x *LoadCodeAssistResponse) GetProjectValidationError() *status.Status {
	if x != nil {
		return x.ProjectValidationError
	}
	return nil
}

func (x *LoadCodeAssistResponse) GetIneligibleTiers() []*IneligibleTier {
	if x != nil {
		return x.IneligibleTiers
	}
	return nil
}

func (x *LoadCodeAssistResponse) GetGcpManaged() bool {
	if x != nil && x.GcpManaged != nil {
		return *x.GcpManaged
	}
	return false
}

func (x *LoadCodeAssistResponse) GetManageSubscriptionUri() string {
	if x != nil && x.ManageSubscriptionUri != nil {
		return *x.ManageSubscriptionUri
	}
	return ""
}

func (x *LoadCodeAssistResponse) GetReleaseChannel() *ReleaseChannel {
	if x != nil {
		return x.ReleaseChannel
	}
	return nil
}

func (x *LoadCodeAssistResponse) GetUpgradeSubscriptionUri() string {
	if x != nil && x.UpgradeSubscriptionUri != nil {
		return *x.UpgradeSubscriptionUri
	}
	return ""
}

func (x *LoadCodeAssistResponse) GetG1Tier() string {
	if x != nil && x.G1Tier != nil {
		return *x.G1Tier
	}
	return ""
}

func (x *LoadCodeAssistResponse) GetPaidTier() *UserTier {
	if x != nil {
		return x.PaidTier
	}
	return nil
}

type UserTier struct {
	state                              protoimpl.MessageState  `protogen:"open.v1"`
	Id                                 string                  `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Name                               string                  `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Description                        string                  `protobuf:"bytes,3,opt,name=description,proto3" json:"description,omitempty"`
	UserDefinedCloudaicompanionProject bool                    `protobuf:"varint,4,opt,name=user_defined_cloudaicompanion_project,json=userDefinedCloudaicompanionProject,proto3" json:"user_defined_cloudaicompanion_project,omitempty"`
	PrivacyNotice                      *UserTier_PrivacyNotice `protobuf:"bytes,5,opt,name=privacy_notice,json=privacyNotice,proto3" json:"privacy_notice,omitempty"`
	IsDefault                          bool                    `protobuf:"varint,6,opt,name=is_default,json=isDefault,proto3" json:"is_default,omitempty"`
	UpgradeSubscriptionUri             *string                 `protobuf:"bytes,7,opt,name=upgrade_subscription_uri,json=upgradeSubscriptionUri,proto3,oneof" json:"upgrade_subscription_uri,omitempty"`
	UpgradeSubscriptionText            *string                 `protobuf:"bytes,8,opt,name=upgrade_subscription_text,json=upgradeSubscriptionText,proto3,oneof" json:"upgrade_subscription_text,omitempty"`
	UpgradeSubscriptionType            *UserTier_UpgradeType   `protobuf:"varint,9,opt,name=upgrade_subscription_type,json=upgradeSubscriptionType,proto3,enum=google.internal.cloud.code.v1internal.UserTier_UpgradeType,oneof" json:"upgrade_subscription_type,omitempty"`
	UpgradeButtonText                  *string                 `protobuf:"bytes,11,opt,name=upgrade_button_text,json=upgradeButtonText,proto3,oneof" json:"upgrade_button_text,omitempty"`
	ClientExperienceTag                *string                 `protobuf:"bytes,12,opt,name=client_experience_tag,json=clientExperienceTag,proto3,oneof" json:"client_experience_tag,omitempty"`
	UsesGcpTos                         bool                    `protobuf:"varint,13,opt,name=uses_gcp_tos,json=usesGcpTos,proto3" json:"uses_gcp_tos,omitempty"`
	AvailableCredits                   []*Credits              `protobuf:"bytes,14,rep,name=available_credits,json=availableCredits,proto3" json:"available_credits,omitempty"`
	unknownFields                      protoimpl.UnknownFields
	sizeCache                          protoimpl.SizeCache
}

func (x *UserTier) Reset() {
	*x = UserTier{}
	mi := &file_google_internal_cloud_code_v1internal_onboarding_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UserTier) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UserTier) ProtoMessage() {}

func (x *UserTier) ProtoReflect() protoreflect.Message {
	mi := &file_google_internal_cloud_code_v1internal_onboarding_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UserTier.ProtoReflect.Descriptor instead.
func (*UserTier) Descriptor() ([]byte, []int) {
	return file_google_internal_cloud_code_v1internal_onboarding_proto_rawDescGZIP(), []int{9}
}

func (x *UserTier) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *UserTier) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *UserTier) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *UserTier) GetUserDefinedCloudaicompanionProject() bool {
	if x != nil {
		return x.UserDefinedCloudaicompanionProject
	}
	return false
}

func (x *UserTier) GetPrivacyNotice() *UserTier_PrivacyNotice {
	if x != nil {
		return x.PrivacyNotice
	}
	return nil
}

func (x *UserTier) GetIsDefault() bool {
	if x != nil {
		return x.IsDefault
	}
	return false
}

func (x *UserTier) GetUpgradeSubscriptionUri() string {
	if x != nil && x.UpgradeSubscriptionUri != nil {
		return *x.UpgradeSubscriptionUri
	}
	return ""
}

func (x *UserTier) GetUpgradeSubscriptionText() string {
	if x != nil && x.UpgradeSubscriptionText != nil {
		return *x.UpgradeSubscriptionText
	}
	return ""
}

func (x *UserTier) GetUpgradeSubscriptionType() UserTier_UpgradeType {
	if x != nil && x.UpgradeSubscriptionType != nil {
		return *x.UpgradeSubscriptionType
	}
	return UserTier_UPGRADE_TYPE_UNSPECIFIED
}

func (x *UserTier) GetUpgradeButtonText() string {
	if x != nil && x.UpgradeButtonText != nil {
		return *x.UpgradeButtonText
	}
	return ""
}

func (x *UserTier) GetClientExperienceTag() string {
	if x != nil && x.ClientExperienceTag != nil {
		return *x.ClientExperienceTag
	}
	return ""
}

func (x *UserTier) GetUsesGcpTos() bool {
	if x != nil {
		return x.UsesGcpTos
	}
	return false
}

func (x *UserTier) GetAvailableCredits() []*Credits {
	if x != nil {
		return x.AvailableCredits
	}
	return nil
}

type AiDevToolsSetting struct {
	state                 protoimpl.MessageState `protogen:"open.v1"`
	StrictModeDisabled    bool                   `protobuf:"varint,1,opt,name=strict_mode_disabled,json=strictModeDisabled,proto3" json:"strict_mode_disabled,omitempty"`
	McpSetting            *McpSetting            `protobuf:"bytes,2,opt,name=mcp_setting,json=mcpSetting,proto3" json:"mcp_setting,omitempty"`
	TurboModeSetting      *TurboModeSetting      `protobuf:"bytes,3,opt,name=turbo_mode_setting,json=turboModeSetting,proto3" json:"turbo_mode_setting,omitempty"`
	BrowserSetting        *BrowserSetting        `protobuf:"bytes,4,opt,name=browser_setting,json=browserSetting,proto3" json:"browser_setting,omitempty"`
	PreviewFeatureSetting *PreviewFeatureSetting `protobuf:"bytes,5,opt,name=preview_feature_setting,json=previewFeatureSetting,proto3" json:"preview_feature_setting,omitempty"`
	AgentSetting          *AgentSetting          `protobuf:"bytes,6,opt,name=agent_setting,json=agentSetting,proto3" json:"agent_setting,omitempty"`
	CliFeatureSetting     *CliFeatureSetting     `protobuf:"bytes,7,opt,name=cli_feature_setting,json=cliFeatureSetting,proto3" json:"cli_feature_setting,omitempty"`
	unknownFields         protoimpl.UnknownFields
	sizeCache             protoimpl.SizeCache
}

func (x *AiDevToolsSetting) Reset() {
	*x = AiDevToolsSetting{}
	mi := &file_google_internal_cloud_code_v1internal_onboarding_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AiDevToolsSetting) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AiDevToolsSetting) ProtoMessage() {}

func (x *AiDevToolsSetting) ProtoReflect() protoreflect.Message {
	mi := &file_google_internal_cloud_code_v1internal_onboarding_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AiDevToolsSetting.ProtoReflect.Descriptor instead.
func (*AiDevToolsSetting) Descriptor() ([]byte, []int) {
	return file_google_internal_cloud_code_v1internal_onboarding_proto_rawDescGZIP(), []int{10}
}

func (x *AiDevToolsSetting) GetStrictModeDisabled() bool {
	if x != nil {
		return x.StrictModeDisabled
	}
	return false
}

func (x *AiDevToolsSetting) GetMcpSetting() *McpSetting {
	if x != nil {
		return x.McpSetting
	}
	return nil
}

func (x *AiDevToolsSetting) GetTurboModeSetting() *TurboModeSetting {
	if x != nil {
		return x.TurboModeSetting
	}
	return nil
}

func (x *AiDevToolsSetting) GetBrowserSetting() *BrowserSetting {
	if x != nil {
		return x.BrowserSetting
	}
	return nil
}

func (x *AiDevToolsSetting) GetPreviewFeatureSetting() *PreviewFeatureSetting {
	if x != nil {
		return x.PreviewFeatureSetting
	}
	return nil
}

func (x *AiDevToolsSetting) GetAgentSetting() *AgentSetting {
	if x != nil {
		return x.AgentSetting
	}
	return nil
}

func (x *AiDevToolsSetting) GetCliFeatureSetting() *CliFeatureSetting {
	if x != nil {
		return x.CliFeatureSetting
	}
	return nil
}

type RecitationPolicy struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	DisableCitations bool                   `protobuf:"varint,1,opt,name=disable_citations,json=disableCitations,proto3" json:"disable_citations,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *RecitationPolicy) Reset() {
	*x = RecitationPolicy{}
	mi := &file_google_internal_cloud_code_v1internal_onboarding_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RecitationPolicy) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RecitationPolicy) ProtoMessage() {}

func (x *RecitationPolicy) ProtoReflect() protoreflect.Message {
	mi := &file_google_internal_cloud_code_v1internal_onboarding_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RecitationPolicy.ProtoReflect.Descriptor instead.
func (*RecitationPolicy) Descriptor() ([]byte, []int) {
	return file_google_internal_cloud_code_v1internal_onboarding_proto_rawDescGZIP(), []int{11}
}

func (x *RecitationPolicy) GetDisableCitations() bool {
	if x != nil {
		return x.DisableCitations
	}
	return false
}

type McpSetting struct {
	state                 protoimpl.MessageState `protogen:"open.v1"`
	McpEnabled            bool                   `protobuf:"varint,1,opt,name=mcp_enabled,json=mcpEnabled,proto3" json:"mcp_enabled,omitempty"`
	OverrideMcpConfigJson string                 `protobuf:"bytes,2,opt,name=override_mcp_config_json,json=overrideMcpConfigJson,proto3" json:"override_mcp_config_json,omitempty"`
	McpConfigJson         string                 `protobuf:"bytes,3,opt,name=mcp_config_json,json=mcpConfigJson,proto3" json:"mcp_config_json,omitempty"`
	unknownFields         protoimpl.UnknownFields
	sizeCache             protoimpl.SizeCache
}

func (x *McpSetting) Reset() {
	*x = McpSetting{}
	mi := &file_google_internal_cloud_code_v1internal_onboarding_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *McpSetting) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*McpSetting) ProtoMessage() {}

func (x *McpSetting) ProtoReflect() protoreflect.Message {
	mi := &file_google_internal_cloud_code_v1internal_onboarding_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use McpSetting.ProtoReflect.Descriptor instead.
func (*McpSetting) Descriptor() ([]byte, []int) {
	return file_google_internal_cloud_code_v1internal_onboarding_proto_rawDescGZIP(), []int{12}
}

func (x *McpSetting) GetMcpEnabled() bool {
	if x != nil {
		return x.McpEnabled
	}
	return false
}

func (x *McpSetting) GetOverrideMcpConfigJson() string {
	if x != nil {
		return x.OverrideMcpConfigJson
	}
	return ""
}

func (x *McpSetting) GetMcpConfigJson() string {
	if x != nil {
		return x.McpConfigJson
	}
	return ""
}

type TurboModeSetting struct {
	state                        protoimpl.MessageState `protogen:"open.v1"`
	TerminalAutoExecutionEnabled bool                   `protobuf:"varint,1,opt,name=terminal_auto_execution_enabled,json=terminalAutoExecutionEnabled,proto3" json:"terminal_auto_execution_enabled,omitempty"`
	BrowserJsExecutionEnabled    bool                   `protobuf:"varint,2,opt,name=browser_js_execution_enabled,json=browserJsExecutionEnabled,proto3" json:"browser_js_execution_enabled,omitempty"`
	unknownFields                protoimpl.UnknownFields
	sizeCache                    protoimpl.SizeCache
}

func (x *TurboModeSetting) Reset() {
	*x = TurboModeSetting{}
	mi := &file_google_internal_cloud_code_v1internal_onboarding_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TurboModeSetting) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TurboModeSetting) ProtoMessage() {}

func (x *TurboModeSetting) ProtoReflect() protoreflect.Message {
	mi := &file_google_internal_cloud_code_v1internal_onboarding_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TurboModeSetting.ProtoReflect.Descriptor instead.
func (*TurboModeSetting) Descriptor() ([]byte, []int) {
	return file_google_internal_cloud_code_v1internal_onboarding_proto_rawDescGZIP(), []int{13}
}

func (x *TurboModeSetting) GetTerminalAutoExecutionEnabled() bool {
	if x != nil {
		return x.TerminalAutoExecutionEnabled
	}
	return false
}

func (x *TurboModeSetting) GetBrowserJsExecutionEnabled() bool {
	if x != nil {
		return x.BrowserJsExecutionEnabled
	}
	return false
}

type BrowserSetting struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	BrowserEnabled  bool                   `protobuf:"varint,1,opt,name=browser_enabled,json=browserEnabled,proto3" json:"browser_enabled,omitempty"`
	AllowedWebsites []string               `protobuf:"bytes,2,rep,name=allowed_websites,json=allowedWebsites,proto3" json:"allowed_websites,omitempty"`
	DeniedWebsites  []string               `protobuf:"bytes,3,rep,name=denied_websites,json=deniedWebsites,proto3" json:"denied_websites,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *BrowserSetting) Reset() {
	*x = BrowserSetting{}
	mi := &file_google_internal_cloud_code_v1internal_onboarding_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BrowserSetting) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BrowserSetting) ProtoMessage() {}

func (x *BrowserSetting) ProtoReflect() protoreflect.Message {
	mi := &file_google_internal_cloud_code_v1internal_onboarding_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BrowserSetting.ProtoReflect.Descriptor instead.
func (*BrowserSetting) Descriptor() ([]byte, []int) {
	return file_google_internal_cloud_code_v1internal_onboarding_proto_rawDescGZIP(), []int{14}
}

func (x *BrowserSetting) GetBrowserEnabled() bool {
	if x != nil {
		return x.BrowserEnabled
	}
	return false
}

func (x *BrowserSetting) GetAllowedWebsites() []string {
	if x != nil {
		return x.AllowedWebsites
	}
	return nil
}

func (x *BrowserSetting) GetDeniedWebsites() []string {
	if x != nil {
		return x.DeniedWebsites
	}
	return nil
}

type PreviewFeatureSetting struct {
	state                protoimpl.MessageState `protogen:"open.v1"`
	PreviewModelsEnabled bool                   `protobuf:"varint,1,opt,name=preview_models_enabled,json=previewModelsEnabled,proto3" json:"preview_models_enabled,omitempty"`
	unknownFields        protoimpl.UnknownFields
	sizeCache            protoimpl.SizeCache
}

func (x *PreviewFeatureSetting) Reset() {
	*x = PreviewFeatureSetting{}
	mi := &file_google_internal_cloud_code_v1internal_onboarding_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PreviewFeatureSetting) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PreviewFeatureSetting) ProtoMessage() {}

func (x *PreviewFeatureSetting) ProtoReflect() protoreflect.Message {
	mi := &file_google_internal_cloud_code_v1internal_onboarding_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PreviewFeatureSetting.ProtoReflect.Descriptor instead.
func (*PreviewFeatureSetting) Descriptor() ([]byte, []int) {
	return file_google_internal_cloud_code_v1internal_onboarding_proto_rawDescGZIP(), []int{15}
}

func (x *PreviewFeatureSetting) GetPreviewModelsEnabled() bool {
	if x != nil {
		return x.PreviewModelsEnabled
	}
	return false
}

type AgentSetting struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	AgyAllowedModels []string               `protobuf:"bytes,1,rep,name=agy_allowed_models,json=agyAllowedModels,proto3" json:"agy_allowed_models,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *AgentSetting) Reset() {
	*x = AgentSetting{}
	mi := &file_google_internal_cloud_code_v1internal_onboarding_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AgentSetting) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AgentSetting) ProtoMessage() {}

func (x *AgentSetting) ProtoReflect() protoreflect.Message {
	mi := &file_google_internal_cloud_code_v1internal_onboarding_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AgentSetting.ProtoReflect.Descriptor instead.
func (*AgentSetting) Descriptor() ([]byte, []int) {
	return file_google_internal_cloud_code_v1internal_onboarding_proto_rawDescGZIP(), []int{16}
}

func (x *AgentSetting) GetAgyAllowedModels() []string {
	if x != nil {
		return x.AgyAllowedModels
	}
	return nil
}

type CliFeatureSetting struct {
	state                        protoimpl.MessageState               `protogen:"open.v1"`
	ExtensionsSetting            *CliFeatureSetting_ExtensionsSetting `protobuf:"bytes,1,opt,name=extensions_setting,json=extensionsSetting,proto3" json:"extensions_setting,omitempty"`
	UnmanagedCapabilitiesEnabled bool                                 `protobuf:"varint,2,opt,name=unmanaged_capabilities_enabled,json=unmanagedCapabilitiesEnabled,proto3" json:"unmanaged_capabilities_enabled,omitempty"`
	unknownFields                protoimpl.UnknownFields
	sizeCache                    protoimpl.SizeCache
}

func (x *CliFeatureSetting) Reset() {
	*x = CliFeatureSetting{}
	mi := &file_google_internal_cloud_code_v1internal_onboarding_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CliFeatureSetting) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CliFeatureSetting) ProtoMessage() {}

func (x *CliFeatureSetting) ProtoReflect() protoreflect.Message {
	mi := &file_google_internal_cloud_code_v1internal_onboarding_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CliFeatureSetting.ProtoReflect.Descriptor instead.
func (*CliFeatureSetting) Descriptor() ([]byte, []int) {
	return file_google_internal_cloud_code_v1internal_onboarding_proto_rawDescGZIP(), []int{17}
}

func (x *CliFeatureSetting) GetExtensionsSetting() *CliFeatureSetting_ExtensionsSetting {
	if x != nil {
		return x.ExtensionsSetting
	}
	return nil
}

func (x *CliFeatureSetting) GetUnmanagedCapabilitiesEnabled() bool {
	if x != nil {
		return x.UnmanagedCapabilitiesEnabled
	}
	return false
}

type FetchAdminControlsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Project       string                 `protobuf:"bytes,1,opt,name=project,proto3" json:"project,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FetchAdminControlsRequest) Reset() {
	*x = FetchAdminControlsRequest{}
	mi := &file_google_internal_cloud_code_v1internal_onboarding_proto_msgTypes[18]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FetchAdminControlsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FetchAdminControlsRequest) ProtoMessage() {}

func (x *FetchAdminControlsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_google_internal_cloud_code_v1internal_onboarding_proto_msgTypes[18]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FetchAdminControlsRequest.ProtoReflect.Descriptor instead.
func (*FetchAdminControlsRequest) Descriptor() ([]byte, []int) {
	return file_google_internal_cloud_code_v1internal_onboarding_proto_rawDescGZIP(), []int{18}
}

func (x *FetchAdminControlsRequest) GetProject() string {
	if x != nil {
		return x.Project
	}
	return ""
}

type FetchAdminControlsResponse struct {
	state                   protoimpl.MessageState                   `protogen:"open.v1"`
	DisableTelemetry        bool                                     `protobuf:"varint,1,opt,name=disable_telemetry,json=disableTelemetry,proto3" json:"disable_telemetry,omitempty"`
	DisableFeedback         bool                                     `protobuf:"varint,2,opt,name=disable_feedback,json=disableFeedback,proto3" json:"disable_feedback,omitempty"`
	RecitationPolicy        *RecitationPolicy                        `protobuf:"bytes,3,opt,name=recitation_policy,json=recitationPolicy,proto3" json:"recitation_policy,omitempty"`
	GroundingType           FetchAdminControlsResponse_GroundingType `protobuf:"varint,4,opt,name=grounding_type,json=groundingType,proto3,enum=google.internal.cloud.code.v1internal.FetchAdminControlsResponse_GroundingType" json:"grounding_type,omitempty"`
	SecureModeEnabled       bool                                     `protobuf:"varint,5,opt,name=secure_mode_enabled,json=secureModeEnabled,proto3" json:"secure_mode_enabled,omitempty"`
	McpSetting              *McpSetting                              `protobuf:"bytes,6,opt,name=mcp_setting,json=mcpSetting,proto3" json:"mcp_setting,omitempty"`
	TurboModeSetting        *TurboModeSetting                        `protobuf:"bytes,7,opt,name=turbo_mode_setting,json=turboModeSetting,proto3" json:"turbo_mode_setting,omitempty"`
	BrowserSetting          *BrowserSetting                          `protobuf:"bytes,8,opt,name=browser_setting,json=browserSetting,proto3" json:"browser_setting,omitempty"`
	PreviewFeatureSetting   *PreviewFeatureSetting                   `protobuf:"bytes,9,opt,name=preview_feature_setting,json=previewFeatureSetting,proto3" json:"preview_feature_setting,omitempty"`
	AgentSetting            *AgentSetting                            `protobuf:"bytes,10,opt,name=agent_setting,json=agentSetting,proto3" json:"agent_setting,omitempty"`
	CliFeatureSetting       *CliFeatureSetting                       `protobuf:"bytes,11,opt,name=cli_feature_setting,json=cliFeatureSetting,proto3" json:"cli_feature_setting,omitempty"`
	StrictModeDisabled      bool                                     `protobuf:"varint,12,opt,name=strict_mode_disabled,json=strictModeDisabled,proto3" json:"strict_mode_disabled,omitempty"`
	AdminControlsApplicable bool                                     `protobuf:"varint,13,opt,name=admin_controls_applicable,json=adminControlsApplicable,proto3" json:"admin_controls_applicable,omitempty"`
	unknownFields           protoimpl.UnknownFields
	sizeCache               protoimpl.SizeCache
}

func (x *FetchAdminControlsResponse) Reset() {
	*x = FetchAdminControlsResponse{}
	mi := &file_google_internal_cloud_code_v1internal_onboarding_proto_msgTypes[19]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FetchAdminControlsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FetchAdminControlsResponse) ProtoMessage() {}

func (x *FetchAdminControlsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_google_internal_cloud_code_v1internal_onboarding_proto_msgTypes[19]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FetchAdminControlsResponse.ProtoReflect.Descriptor instead.
func (*FetchAdminControlsResponse) Descriptor() ([]byte, []int) {
	return file_google_internal_cloud_code_v1internal_onboarding_proto_rawDescGZIP(), []int{19}
}

func (x *FetchAdminControlsResponse) GetDisableTelemetry() bool {
	if x != nil {
		return x.DisableTelemetry
	}
	return false
}

func (x *FetchAdminControlsResponse) GetDisableFeedback() bool {
	if x != nil {
		return x.DisableFeedback
	}
	return false
}

func (x *FetchAdminControlsResponse) GetRecitationPolicy() *RecitationPolicy {
	if x != nil {
		return x.RecitationPolicy
	}
	return nil
}

func (x *FetchAdminControlsResponse) GetGroundingType() FetchAdminControlsResponse_GroundingType {
	if x != nil {
		return x.GroundingType
	}
	return FetchAdminControlsResponse_GROUNDING_TYPE_UNSPECIFIED
}

func (x *FetchAdminControlsResponse) GetSecureModeEnabled() bool {
	if x != nil {
		return x.SecureModeEnabled
	}
	return false
}

func (x *FetchAdminControlsResponse) GetMcpSetting() *McpSetting {
	if x != nil {
		return x.McpSetting
	}
	return nil
}

func (x *FetchAdminControlsResponse) GetTurboModeSetting() *TurboModeSetting {
	if x != nil {
		return x.TurboModeSetting
	}
	return nil
}

func (x *FetchAdminControlsResponse) GetBrowserSetting() *BrowserSetting {
	if x != nil {
		return x.BrowserSetting
	}
	return nil
}

func (x *FetchAdminControlsResponse) GetPreviewFeatureSetting() *PreviewFeatureSetting {
	if x != nil {
		return x.PreviewFeatureSetting
	}
	return nil
}

func (x *FetchAdminControlsResponse) GetAgentSetting() *AgentSetting {
	if x != nil {
		return x.AgentSetting
	}
	return nil
}

func (x *FetchAdminControlsResponse) GetCliFeatureSetting() *CliFeatureSetting {
	if x != nil {
		return x.CliFeatureSetting
	}
	return nil
}

func (x *FetchAdminControlsResponse) GetStrictModeDisabled() bool {
	if x != nil {
		return x.StrictModeDisabled
	}
	return false
}

func (x *FetchAdminControlsResponse) GetAdminControlsApplicable() bool {
	if x != nil {
		return x.AdminControlsApplicable
	}
	return false
}

type UserTier_PrivacyNotice struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ShowNotice    bool                   `protobuf:"varint,1,opt,name=show_notice,json=showNotice,proto3" json:"show_notice,omitempty"`
	NoticeText    *string                `protobuf:"bytes,2,opt,name=notice_text,json=noticeText,proto3,oneof" json:"notice_text,omitempty"`
	MinorNotice   bool                   `protobuf:"varint,4,opt,name=minor_notice,json=minorNotice,proto3" json:"minor_notice,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UserTier_PrivacyNotice) Reset() {
	*x = UserTier_PrivacyNotice{}
	mi := &file_google_internal_cloud_code_v1internal_onboarding_proto_msgTypes[20]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UserTier_PrivacyNotice) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UserTier_PrivacyNotice) ProtoMessage() {}

func (x *UserTier_PrivacyNotice) ProtoReflect() protoreflect.Message {
	mi := &file_google_internal_cloud_code_v1internal_onboarding_proto_msgTypes[20]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UserTier_PrivacyNotice.ProtoReflect.Descriptor instead.
func (*UserTier_PrivacyNotice) Descriptor() ([]byte, []int) {
	return file_google_internal_cloud_code_v1internal_onboarding_proto_rawDescGZIP(), []int{9, 0}
}

func (x *UserTier_PrivacyNotice) GetShowNotice() bool {
	if x != nil {
		return x.ShowNotice
	}
	return false
}

func (x *UserTier_PrivacyNotice) GetNoticeText() string {
	if x != nil && x.NoticeText != nil {
		return *x.NoticeText
	}
	return ""
}

func (x *UserTier_PrivacyNotice) GetMinorNotice() bool {
	if x != nil {
		return x.MinorNotice
	}
	return false
}

type CliFeatureSetting_ExtensionsSetting struct {
	state             protoimpl.MessageState `protogen:"open.v1"`
	ExtensionsEnabled bool                   `protobuf:"varint,1,opt,name=extensions_enabled,json=extensionsEnabled,proto3" json:"extensions_enabled,omitempty"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *CliFeatureSetting_ExtensionsSetting) Reset() {
	*x = CliFeatureSetting_ExtensionsSetting{}
	mi := &file_google_internal_cloud_code_v1internal_onboarding_proto_msgTypes[21]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CliFeatureSetting_ExtensionsSetting) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CliFeatureSetting_ExtensionsSetting) ProtoMessage() {}

func (x *CliFeatureSetting_ExtensionsSetting) ProtoReflect() protoreflect.Message {
	mi := &file_google_internal_cloud_code_v1internal_onboarding_proto_msgTypes[21]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CliFeatureSetting_ExtensionsSetting.ProtoReflect.Descriptor instead.
func (*CliFeatureSetting_ExtensionsSetting) Descriptor() ([]byte, []int) {
	return file_google_internal_cloud_code_v1internal_onboarding_proto_rawDescGZIP(), []int{17, 0}
}

func (x *CliFeatureSetting_ExtensionsSetting) GetExtensionsEnabled() bool {
	if x != nil {
		return x.ExtensionsEnabled
	}
	return false
}

var File_google_internal_cloud_code_v1internal_onboarding_proto protoreflect.FileDescriptor

const file_google_internal_cloud_code_v1internal_onboarding_proto_rawDesc = "" +
	"\n" +
	"6google/internal/cloud/code/v1internal/onboarding.proto\x12%google.internal.cloud.code.v1internal\x1a3google/internal/cloud/code/v1internal/credits.proto\x1a\x1egoogle/rpc/error_details.proto\x1a\x17google/rpc/status.proto\"\xdd\x01\n" +
	"\x12OnboardUserRequest\x12\x17\n" +
	"\atier_id\x18\x01 \x01(\tR\x06tierId\x12>\n" +
	"\x18cloudaicompanion_project\x18\x02 \x01(\tH\x00R\x17cloudaicompanionProject\x88\x01\x01\x12Q\n" +
	"\bmetadata\x18\x03 \x01(\v25.google.internal.cloud.code.v1internal.ClientMetadataR\bmetadataB\x1b\n" +
	"\x19_cloudaicompanion_project\"\xdb\x02\n" +
	"\x13OnboardUserResponse\x12i\n" +
	"\x18cloudaicompanion_project\x18\x01 \x01(\v2..google.internal.cloud.code.v1internal.ProjectR\x17cloudaicompanionProject\x12U\n" +
	"\x06status\x18\x04 \x01(\v28.google.internal.cloud.code.v1internal.OnboardUserStatusH\x00R\x06status\x88\x01\x01\x12c\n" +
	"\x0frelease_channel\x18\x05 \x01(\v25.google.internal.cloud.code.v1internal.ReleaseChannelH\x01R\x0ereleaseChannel\x88\x01\x01B\t\n" +
	"\a_statusB\x12\n" +
	"\x10_release_channel\"\xd7\x01\n" +
	"\x0eReleaseChannel\x12U\n" +
	"\x04type\x18\x01 \x01(\x0e2A.google.internal.cloud.code.v1internal.ReleaseChannel.ChannelTypeR\x04type\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12 \n" +
	"\vdescription\x18\x03 \x01(\tR\vdescription\"8\n" +
	"\vChannelType\x12\v\n" +
	"\aUNKNOWN\x10\x00\x12\n" +
	"\n" +
	"\x06STABLE\x10\x01\x12\x10\n" +
	"\fEXPERIMENTAL\x10\x02\"\xf8\x02\n" +
	"\x15LoadCodeAssistRequest\x12>\n" +
	"\x18cloudaicompanion_project\x18\x01 \x01(\tH\x00R\x17cloudaicompanionProject\x88\x01\x01\x12Q\n" +
	"\bmetadata\x18\x02 \x01(\v25.google.internal.cloud.code.v1internal.ClientMetadataR\bmetadata\x12Z\n" +
	"\x04mode\x18\x03 \x01(\x0e2A.google.internal.cloud.code.v1internal.LoadCodeAssistRequest.ModeH\x01R\x04mode\x88\x01\x01\"J\n" +
	"\x04Mode\x12\x14\n" +
	"\x10MODE_UNSPECIFIED\x10\x00\x12\x1a\n" +
	"\x16FULL_ELIGIBILITY_CHECK\x10\x01\x12\x10\n" +
	"\fHEALTH_CHECK\x10\x02B\x1b\n" +
	"\x19_cloudaicompanion_projectB\a\n" +
	"\x05_mode\"\xad\x06\n" +
	"\x0eIneligibleTier\x12p\n" +
	"\vreason_code\x18\x01 \x01(\x0e2O.google.internal.cloud.code.v1internal.IneligibleTier.IneligibleTierReasonCodesR\n" +
	"reasonCode\x12%\n" +
	"\x0ereason_message\x18\x02 \x01(\tR\rreasonMessage\x12\x17\n" +
	"\atier_id\x18\x03 \x01(\tR\x06tierId\x12\x1b\n" +
	"\ttier_name\x18\x04 \x01(\tR\btierName\x128\n" +
	"\x18validation_error_message\x18\x05 \x01(\tR\x16validationErrorMessage\x127\n" +
	"\x18validation_url_link_text\x18\x06 \x01(\tR\x15validationUrlLinkText\x12%\n" +
	"\x0evalidation_url\x18\a \x01(\tR\rvalidationUrl\x12D\n" +
	"\x1fvalidation_learn_more_link_text\x18\b \x01(\tR\x1bvalidationLearnMoreLinkText\x129\n" +
	"\x19validation_learn_more_url\x18\t \x01(\tR\x16validationLearnMoreUrl\"\xb0\x02\n" +
	"\x19IneligibleTierReasonCodes\x12\v\n" +
	"\aUNKNOWN\x10\x00\x12\x16\n" +
	"\x12INELIGIBLE_ACCOUNT\x10\x01\x12\x14\n" +
	"\x10UNKNOWN_LOCATION\x10\x02\x12\x18\n" +
	"\x14UNSUPPORTED_LOCATION\x10\x03\x12\x16\n" +
	"\x12RESTRICTED_NETWORK\x10\x04\x12\x12\n" +
	"\x0eRESTRICTED_AGE\x10\x05\x12\x14\n" +
	"\x10NON_USER_ACCOUNT\x10\x06\x12\x0f\n" +
	"\vDASHER_USER\x10\a\x12\x0e\n" +
	"\n" +
	"BYOID_USER\x10\b\x12\x1a\n" +
	"\x16RESTRICTED_DASHER_USER\x10\t\x12\x17\n" +
	"\x13VALIDATION_REQUIRED\x10\n" +
	"\x12&\n" +
	"\"GOOGLE_TOS_NOT_SUPPORTED_BY_CLIENT\x10\v\"\xe4\a\n" +
	"\x0eClientMetadata\x12X\n" +
	"\bide_type\x18\x01 \x01(\x0e2=.google.internal.cloud.code.v1internal.ClientMetadata.IdeTypeR\aideType\x12\x1f\n" +
	"\vide_version\x18\x02 \x01(\tR\n" +
	"ideVersion\x12%\n" +
	"\x0eplugin_version\x18\x03 \x01(\tR\rpluginVersion\x12Z\n" +
	"\bplatform\x18\x04 \x01(\x0e2>.google.internal.cloud.code.v1internal.ClientMetadata.PlatformR\bplatform\x12%\n" +
	"\x0eupdate_channel\x18\x05 \x01(\tR\rupdateChannel\x12!\n" +
	"\fduet_project\x18\x06 \x01(\tR\vduetProject\x12a\n" +
	"\vplugin_type\x18\a \x01(\x0e2@.google.internal.cloud.code.v1internal.ClientMetadata.PluginTypeR\n" +
	"pluginType\x12\x19\n" +
	"\bide_name\x18\b \x01(\tR\aideName\"\x90\x02\n" +
	"\aIdeType\x12\x13\n" +
	"\x0fIDE_UNSPECIFIED\x10\x00\x12\n" +
	"\n" +
	"\x06VSCODE\x10\x01\x12\f\n" +
	"\bINTELLIJ\x10\x02\x12\x1c\n" +
	"\x18VSCODE_CLOUD_WORKSTATION\x10\x03\x12\x1e\n" +
	"\x1aINTELLIJ_CLOUD_WORKSTATION\x10\x04\x12\x0f\n" +
	"\vCLOUD_SHELL\x10\x05\x12\t\n" +
	"\x05CIDER\x10\x06\x12\r\n" +
	"\tCLOUD_RUN\x10\a\x12\x12\n" +
	"\x0eANDROID_STUDIO\x10\b\x12\x0f\n" +
	"\vANTIGRAVITY\x10\t\x12\n" +
	"\n" +
	"\x06JETSKI\x10\n" +
	"\x12\t\n" +
	"\x05COLAB\x10\v\x12\f\n" +
	"\bFIREBASE\x10\f\x12\x13\n" +
	"\x0fCHROME_DEVTOOLS\x10\r\x12\x0e\n" +
	"\n" +
	"GEMINI_CLI\x10\x0e\"}\n" +
	"\bPlatform\x12\x18\n" +
	"\x14PLATFORM_UNSPECIFIED\x10\x00\x12\x10\n" +
	"\fDARWIN_AMD64\x10\x01\x12\x10\n" +
	"\fDARWIN_ARM64\x10\x02\x12\x0f\n" +
	"\vLINUX_AMD64\x10\x03\x12\x0f\n" +
	"\vLINUX_ARM64\x10\x04\x12\x11\n" +
	"\rWINDOWS_AMD64\x10\x05\"z\n" +
	"\n" +
	"PluginType\x12\x16\n" +
	"\x12PLUGIN_UNSPECIFIED\x10\x00\x12\x0e\n" +
	"\n" +
	"CLOUD_CODE\x10\x01\x12\n" +
	"\n" +
	"\x06GEMINI\x10\x02\x12\x15\n" +
	"\x11AIPLUGIN_INTELLIJ\x10\x03\x12\x13\n" +
	"\x0fAIPLUGIN_STUDIO\x10\x04\x12\f\n" +
	"\bPANTHEON\x10\x06\"T\n" +
	"\aProject\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12%\n" +
	"\x0eproject_number\x18\x03 \x01(\x03R\rprojectNumber\"\xc2\x02\n" +
	"\x11OnboardUserStatus\x12d\n" +
	"\vstatus_code\x18\x01 \x01(\x0e2C.google.internal.cloud.code.v1internal.OnboardUserStatus.StatusCodeR\n" +
	"statusCode\x12'\n" +
	"\x0fdisplay_message\x18\x02 \x01(\tR\x0edisplayMessage\x127\n" +
	"\thelp_link\x18\x03 \x01(\v2\x15.google.rpc.Help.LinkH\x00R\bhelpLink\x88\x01\x01\x12#\n" +
	"\rmessage_title\x18\x04 \x01(\tR\fmessageTitle\"2\n" +
	"\n" +
	"StatusCode\x12\v\n" +
	"\aDEFAULT\x10\x00\x12\n" +
	"\n" +
	"\x06NOTICE\x10\x01\x12\v\n" +
	"\aWARNING\x10\x02B\f\n" +
	"\n" +
	"_help_link\"\xcd\a\n" +
	"\x16LoadCodeAssistResponse\x12R\n" +
	"\fcurrent_tier\x18\x01 \x01(\v2/.google.internal.cloud.code.v1internal.UserTierR\vcurrentTier\x12T\n" +
	"\rallowed_tiers\x18\x02 \x03(\v2/.google.internal.cloud.code.v1internal.UserTierR\fallowedTiers\x12>\n" +
	"\x18cloudaicompanion_project\x18\x03 \x01(\tH\x00R\x17cloudaicompanionProject\x88\x01\x01\x12Q\n" +
	"\x18project_validation_error\x18\x04 \x01(\v2\x12.google.rpc.StatusH\x01R\x16projectValidationError\x88\x01\x01\x12`\n" +
	"\x10ineligible_tiers\x18\x05 \x03(\v25.google.internal.cloud.code.v1internal.IneligibleTierR\x0fineligibleTiers\x12$\n" +
	"\vgcp_managed\x18\x06 \x01(\bH\x02R\n" +
	"gcpManaged\x88\x01\x01\x12;\n" +
	"\x17manage_subscription_uri\x18\a \x01(\tH\x03R\x15manageSubscriptionUri\x88\x01\x01\x12c\n" +
	"\x0frelease_channel\x18\b \x01(\v25.google.internal.cloud.code.v1internal.ReleaseChannelH\x04R\x0ereleaseChannel\x88\x01\x01\x12=\n" +
	"\x18upgrade_subscription_uri\x18\t \x01(\tH\x05R\x16upgradeSubscriptionUri\x88\x01\x01\x12\x1c\n" +
	"\ag1_tier\x18\v \x01(\tH\x06R\x06g1Tier\x88\x01\x01\x12L\n" +
	"\tpaid_tier\x18\f \x01(\v2/.google.internal.cloud.code.v1internal.UserTierR\bpaidTierB\x1b\n" +
	"\x19_cloudaicompanion_projectB\x1b\n" +
	"\x19_project_validation_errorB\x0e\n" +
	"\f_gcp_managedB\x1a\n" +
	"\x18_manage_subscription_uriB\x12\n" +
	"\x10_release_channelB\x1b\n" +
	"\x19_upgrade_subscription_uriB\n" +
	"\n" +
	"\b_g1_tier\"\x97\t\n" +
	"\bUserTier\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12 \n" +
	"\vdescription\x18\x03 \x01(\tR\vdescription\x12Q\n" +
	"%user_defined_cloudaicompanion_project\x18\x04 \x01(\bR\"userDefinedCloudaicompanionProject\x12d\n" +
	"\x0eprivacy_notice\x18\x05 \x01(\v2=.google.internal.cloud.code.v1internal.UserTier.PrivacyNoticeR\rprivacyNotice\x12\x1d\n" +
	"\n" +
	"is_default\x18\x06 \x01(\bR\tisDefault\x12=\n" +
	"\x18upgrade_subscription_uri\x18\a \x01(\tH\x00R\x16upgradeSubscriptionUri\x88\x01\x01\x12?\n" +
	"\x19upgrade_subscription_text\x18\b \x01(\tH\x01R\x17upgradeSubscriptionText\x88\x01\x01\x12|\n" +
	"\x19upgrade_subscription_type\x18\t \x01(\x0e2;.google.internal.cloud.code.v1internal.UserTier.UpgradeTypeH\x02R\x17upgradeSubscriptionType\x88\x01\x01\x123\n" +
	"\x13upgrade_button_text\x18\v \x01(\tH\x03R\x11upgradeButtonText\x88\x01\x01\x127\n" +
	"\x15client_experience_tag\x18\f \x01(\tH\x04R\x13clientExperienceTag\x88\x01\x01\x12 \n" +
	"\fuses_gcp_tos\x18\r \x01(\bR\n" +
	"usesGcpTos\x12[\n" +
	"\x11available_credits\x18\x0e \x03(\v2..google.internal.cloud.code.v1internal.CreditsR\x10availableCredits\x1a\x89\x01\n" +
	"\rPrivacyNotice\x12\x1f\n" +
	"\vshow_notice\x18\x01 \x01(\bR\n" +
	"showNotice\x12$\n" +
	"\vnotice_text\x18\x02 \x01(\tH\x00R\n" +
	"noticeText\x88\x01\x01\x12!\n" +
	"\fminor_notice\x18\x04 \x01(\bR\vminorNoticeB\x0e\n" +
	"\f_notice_text\"k\n" +
	"\vUpgradeType\x12\x1c\n" +
	"\x18UPGRADE_TYPE_UNSPECIFIED\x10\x00\x12\a\n" +
	"\x03GDP\x10\x01\x12\x0e\n" +
	"\n" +
	"GOOGLE_ONE\x10\x02\x12\x0e\n" +
	"\n" +
	"GDP_HELIUM\x10\x03\x12\x15\n" +
	"\x11GOOGLE_ONE_HELIUM\x10\x04B\x1b\n" +
	"\x19_upgrade_subscription_uriB\x1c\n" +
	"\x1a_upgrade_subscription_textB\x1c\n" +
	"\x1a_upgrade_subscription_typeB\x16\n" +
	"\x14_upgrade_button_textB\x18\n" +
	"\x16_client_experience_tag\"\x9a\x05\n" +
	"\x11AiDevToolsSetting\x120\n" +
	"\x14strict_mode_disabled\x18\x01 \x01(\bR\x12strictModeDisabled\x12R\n" +
	"\vmcp_setting\x18\x02 \x01(\v21.google.internal.cloud.code.v1internal.McpSettingR\n" +
	"mcpSetting\x12e\n" +
	"\x12turbo_mode_setting\x18\x03 \x01(\v27.google.internal.cloud.code.v1internal.TurboModeSettingR\x10turboModeSetting\x12^\n" +
	"\x0fbrowser_setting\x18\x04 \x01(\v25.google.internal.cloud.code.v1internal.BrowserSettingR\x0ebrowserSetting\x12t\n" +
	"\x17preview_feature_setting\x18\x05 \x01(\v2<.google.internal.cloud.code.v1internal.PreviewFeatureSettingR\x15previewFeatureSetting\x12X\n" +
	"\ragent_setting\x18\x06 \x01(\v23.google.internal.cloud.code.v1internal.AgentSettingR\fagentSetting\x12h\n" +
	"\x13cli_feature_setting\x18\a \x01(\v28.google.internal.cloud.code.v1internal.CliFeatureSettingR\x11cliFeatureSetting\"?\n" +
	"\x10RecitationPolicy\x12+\n" +
	"\x11disable_citations\x18\x01 \x01(\bR\x10disableCitations\"\x8e\x01\n" +
	"\n" +
	"McpSetting\x12\x1f\n" +
	"\vmcp_enabled\x18\x01 \x01(\bR\n" +
	"mcpEnabled\x127\n" +
	"\x18override_mcp_config_json\x18\x02 \x01(\tR\x15overrideMcpConfigJson\x12&\n" +
	"\x0fmcp_config_json\x18\x03 \x01(\tR\rmcpConfigJson\"\x9a\x01\n" +
	"\x10TurboModeSetting\x12E\n" +
	"\x1fterminal_auto_execution_enabled\x18\x01 \x01(\bR\x1cterminalAutoExecutionEnabled\x12?\n" +
	"\x1cbrowser_js_execution_enabled\x18\x02 \x01(\bR\x19browserJsExecutionEnabled\"\x8d\x01\n" +
	"\x0eBrowserSetting\x12'\n" +
	"\x0fbrowser_enabled\x18\x01 \x01(\bR\x0ebrowserEnabled\x12)\n" +
	"\x10allowed_websites\x18\x02 \x03(\tR\x0fallowedWebsites\x12'\n" +
	"\x0fdenied_websites\x18\x03 \x03(\tR\x0edeniedWebsites\"M\n" +
	"\x15PreviewFeatureSetting\x124\n" +
	"\x16preview_models_enabled\x18\x01 \x01(\bR\x14previewModelsEnabled\"<\n" +
	"\fAgentSetting\x12,\n" +
	"\x12agy_allowed_models\x18\x01 \x03(\tR\x10agyAllowedModels\"\x98\x02\n" +
	"\x11CliFeatureSetting\x12y\n" +
	"\x12extensions_setting\x18\x01 \x01(\v2J.google.internal.cloud.code.v1internal.CliFeatureSetting.ExtensionsSettingR\x11extensionsSetting\x12D\n" +
	"\x1eunmanaged_capabilities_enabled\x18\x02 \x01(\bR\x1cunmanagedCapabilitiesEnabled\x1aB\n" +
	"\x11ExtensionsSetting\x12-\n" +
	"\x12extensions_enabled\x18\x01 \x01(\bR\x11extensionsEnabled\"5\n" +
	"\x19FetchAdminControlsRequest\x12\x18\n" +
	"\aproject\x18\x01 \x01(\tR\aproject\"\xba\t\n" +
	"\x1aFetchAdminControlsResponse\x12+\n" +
	"\x11disable_telemetry\x18\x01 \x01(\bR\x10disableTelemetry\x12)\n" +
	"\x10disable_feedback\x18\x02 \x01(\bR\x0fdisableFeedback\x12d\n" +
	"\x11recitation_policy\x18\x03 \x01(\v27.google.internal.cloud.code.v1internal.RecitationPolicyR\x10recitationPolicy\x12v\n" +
	"\x0egrounding_type\x18\x04 \x01(\x0e2O.google.internal.cloud.code.v1internal.FetchAdminControlsResponse.GroundingTypeR\rgroundingType\x12.\n" +
	"\x13secure_mode_enabled\x18\x05 \x01(\bR\x11secureModeEnabled\x12R\n" +
	"\vmcp_setting\x18\x06 \x01(\v21.google.internal.cloud.code.v1internal.McpSettingR\n" +
	"mcpSetting\x12e\n" +
	"\x12turbo_mode_setting\x18\a \x01(\v27.google.internal.cloud.code.v1internal.TurboModeSettingR\x10turboModeSetting\x12^\n" +
	"\x0fbrowser_setting\x18\b \x01(\v25.google.internal.cloud.code.v1internal.BrowserSettingR\x0ebrowserSetting\x12t\n" +
	"\x17preview_feature_setting\x18\t \x01(\v2<.google.internal.cloud.code.v1internal.PreviewFeatureSettingR\x15previewFeatureSetting\x12X\n" +
	"\ragent_setting\x18\n" +
	" \x01(\v23.google.internal.cloud.code.v1internal.AgentSettingR\fagentSetting\x12h\n" +
	"\x13cli_feature_setting\x18\v \x01(\v28.google.internal.cloud.code.v1internal.CliFeatureSettingR\x11cliFeatureSetting\x120\n" +
	"\x14strict_mode_disabled\x18\f \x01(\bR\x12strictModeDisabled\x12:\n" +
	"\x19admin_controls_applicable\x18\r \x01(\bR\x17adminControlsApplicable\"s\n" +
	"\rGroundingType\x12\x1e\n" +
	"\x1aGROUNDING_TYPE_UNSPECIFIED\x10\x00\x12 \n" +
	"\x1cGROUNDING_WITH_GOOGLE_SEARCH\x10\x01\x12 \n" +
	"\x1cWEB_GROUNDING_FOR_ENTERPRISE\x10\x02BCZAgithub.com/router-for-me/CLIProxyAPI/v6/internal/proto/v1internalb\x06proto3"

var (
	file_google_internal_cloud_code_v1internal_onboarding_proto_rawDescOnce sync.Once
	file_google_internal_cloud_code_v1internal_onboarding_proto_rawDescData []byte
)

func file_google_internal_cloud_code_v1internal_onboarding_proto_rawDescGZIP() []byte {
	file_google_internal_cloud_code_v1internal_onboarding_proto_rawDescOnce.Do(func() {
		file_google_internal_cloud_code_v1internal_onboarding_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_google_internal_cloud_code_v1internal_onboarding_proto_rawDesc), len(file_google_internal_cloud_code_v1internal_onboarding_proto_rawDesc)))
	})
	return file_google_internal_cloud_code_v1internal_onboarding_proto_rawDescData
}

var file_google_internal_cloud_code_v1internal_onboarding_proto_enumTypes = make([]protoimpl.EnumInfo, 9)
var file_google_internal_cloud_code_v1internal_onboarding_proto_msgTypes = make([]protoimpl.MessageInfo, 22)
var file_google_internal_cloud_code_v1internal_onboarding_proto_goTypes = []any{
	(ReleaseChannel_ChannelType)(0),               // 0: google.internal.cloud.code.v1internal.ReleaseChannel.ChannelType
	(LoadCodeAssistRequest_Mode)(0),               // 1: google.internal.cloud.code.v1internal.LoadCodeAssistRequest.Mode
	(IneligibleTier_IneligibleTierReasonCodes)(0), // 2: google.internal.cloud.code.v1internal.IneligibleTier.IneligibleTierReasonCodes
	(ClientMetadata_IdeType)(0),                   // 3: google.internal.cloud.code.v1internal.ClientMetadata.IdeType
	(ClientMetadata_Platform)(0),                  // 4: google.internal.cloud.code.v1internal.ClientMetadata.Platform
	(ClientMetadata_PluginType)(0),                // 5: google.internal.cloud.code.v1internal.ClientMetadata.PluginType
	(OnboardUserStatus_StatusCode)(0),             // 6: google.internal.cloud.code.v1internal.OnboardUserStatus.StatusCode
	(UserTier_UpgradeType)(0),                     // 7: google.internal.cloud.code.v1internal.UserTier.UpgradeType
	(FetchAdminControlsResponse_GroundingType)(0), // 8: google.internal.cloud.code.v1internal.FetchAdminControlsResponse.GroundingType
	(*OnboardUserRequest)(nil),                    // 9: google.internal.cloud.code.v1internal.OnboardUserRequest
	(*OnboardUserResponse)(nil),                   // 10: google.internal.cloud.code.v1internal.OnboardUserResponse
	(*ReleaseChannel)(nil),                        // 11: google.internal.cloud.code.v1internal.ReleaseChannel
	(*LoadCodeAssistRequest)(nil),                 // 12: google.internal.cloud.code.v1internal.LoadCodeAssistRequest
	(*IneligibleTier)(nil),                        // 13: google.internal.cloud.code.v1internal.IneligibleTier
	(*ClientMetadata)(nil),                        // 14: google.internal.cloud.code.v1internal.ClientMetadata
	(*Project)(nil),                               // 15: google.internal.cloud.code.v1internal.Project
	(*OnboardUserStatus)(nil),                     // 16: google.internal.cloud.code.v1internal.OnboardUserStatus
	(*LoadCodeAssistResponse)(nil),                // 17: google.internal.cloud.code.v1internal.LoadCodeAssistResponse
	(*UserTier)(nil),                              // 18: google.internal.cloud.code.v1internal.UserTier
	(*AiDevToolsSetting)(nil),                     // 19: google.internal.cloud.code.v1internal.AiDevToolsSetting
	(*RecitationPolicy)(nil),                      // 20: google.internal.cloud.code.v1internal.RecitationPolicy
	(*McpSetting)(nil),                            // 21: google.internal.cloud.code.v1internal.McpSetting
	(*TurboModeSetting)(nil),                      // 22: google.internal.cloud.code.v1internal.TurboModeSetting
	(*BrowserSetting)(nil),                        // 23: google.internal.cloud.code.v1internal.BrowserSetting
	(*PreviewFeatureSetting)(nil),                 // 24: google.internal.cloud.code.v1internal.PreviewFeatureSetting
	(*AgentSetting)(nil),                          // 25: google.internal.cloud.code.v1internal.AgentSetting
	(*CliFeatureSetting)(nil),                     // 26: google.internal.cloud.code.v1internal.CliFeatureSetting
	(*FetchAdminControlsRequest)(nil),             // 27: google.internal.cloud.code.v1internal.FetchAdminControlsRequest
	(*FetchAdminControlsResponse)(nil),            // 28: google.internal.cloud.code.v1internal.FetchAdminControlsResponse
	(*UserTier_PrivacyNotice)(nil),                // 29: google.internal.cloud.code.v1internal.UserTier.PrivacyNotice
	(*CliFeatureSetting_ExtensionsSetting)(nil),   // 30: google.internal.cloud.code.v1internal.CliFeatureSetting.ExtensionsSetting
	(*errdetails.Help_Link)(nil),                  // 31: google.rpc.Help.Link
	(*status.Status)(nil),                         // 32: google.rpc.Status
	(*Credits)(nil),                               // 33: google.internal.cloud.code.v1internal.Credits
}
var file_google_internal_cloud_code_v1internal_onboarding_proto_depIdxs = []int32{
	14, // 0: google.internal.cloud.code.v1internal.OnboardUserRequest.metadata:type_name -> google.internal.cloud.code.v1internal.ClientMetadata
	15, // 1: google.internal.cloud.code.v1internal.OnboardUserResponse.cloudaicompanion_project:type_name -> google.internal.cloud.code.v1internal.Project
	16, // 2: google.internal.cloud.code.v1internal.OnboardUserResponse.status:type_name -> google.internal.cloud.code.v1internal.OnboardUserStatus
	11, // 3: google.internal.cloud.code.v1internal.OnboardUserResponse.release_channel:type_name -> google.internal.cloud.code.v1internal.ReleaseChannel
	0,  // 4: google.internal.cloud.code.v1internal.ReleaseChannel.type:type_name -> google.internal.cloud.code.v1internal.ReleaseChannel.ChannelType
	14, // 5: google.internal.cloud.code.v1internal.LoadCodeAssistRequest.metadata:type_name -> google.internal.cloud.code.v1internal.ClientMetadata
	1,  // 6: google.internal.cloud.code.v1internal.LoadCodeAssistRequest.mode:type_name -> google.internal.cloud.code.v1internal.LoadCodeAssistRequest.Mode
	2,  // 7: google.internal.cloud.code.v1internal.IneligibleTier.reason_code:type_name -> google.internal.cloud.code.v1internal.IneligibleTier.IneligibleTierReasonCodes
	3,  // 8: google.internal.cloud.code.v1internal.ClientMetadata.ide_type:type_name -> google.internal.cloud.code.v1internal.ClientMetadata.IdeType
	4,  // 9: google.internal.cloud.code.v1internal.ClientMetadata.platform:type_name -> google.internal.cloud.code.v1internal.ClientMetadata.Platform
	5,  // 10: google.internal.cloud.code.v1internal.ClientMetadata.plugin_type:type_name -> google.internal.cloud.code.v1internal.ClientMetadata.PluginType
	6,  // 11: google.internal.cloud.code.v1internal.OnboardUserStatus.status_code:type_name -> google.internal.cloud.code.v1internal.OnboardUserStatus.StatusCode
	31, // 12: google.internal.cloud.code.v1internal.OnboardUserStatus.help_link:type_name -> google.rpc.Help.Link
	18, // 13: google.internal.cloud.code.v1internal.LoadCodeAssistResponse.current_tier:type_name -> google.internal.cloud.code.v1internal.UserTier
	18, // 14: google.internal.cloud.code.v1internal.LoadCodeAssistResponse.allowed_tiers:type_name -> google.internal.cloud.code.v1internal.UserTier
	32, // 15: google.internal.cloud.code.v1internal.LoadCodeAssistResponse.project_validation_error:type_name -> google.rpc.Status
	13, // 16: google.internal.cloud.code.v1internal.LoadCodeAssistResponse.ineligible_tiers:type_name -> google.internal.cloud.code.v1internal.IneligibleTier
	11, // 17: google.internal.cloud.code.v1internal.LoadCodeAssistResponse.release_channel:type_name -> google.internal.cloud.code.v1internal.ReleaseChannel
	18, // 18: google.internal.cloud.code.v1internal.LoadCodeAssistResponse.paid_tier:type_name -> google.internal.cloud.code.v1internal.UserTier
	29, // 19: google.internal.cloud.code.v1internal.UserTier.privacy_notice:type_name -> google.internal.cloud.code.v1internal.UserTier.PrivacyNotice
	7,  // 20: google.internal.cloud.code.v1internal.UserTier.upgrade_subscription_type:type_name -> google.internal.cloud.code.v1internal.UserTier.UpgradeType
	33, // 21: google.internal.cloud.code.v1internal.UserTier.available_credits:type_name -> google.internal.cloud.code.v1internal.Credits
	21, // 22: google.internal.cloud.code.v1internal.AiDevToolsSetting.mcp_setting:type_name -> google.internal.cloud.code.v1internal.McpSetting
	22, // 23: google.internal.cloud.code.v1internal.AiDevToolsSetting.turbo_mode_setting:type_name -> google.internal.cloud.code.v1internal.TurboModeSetting
	23, // 24: google.internal.cloud.code.v1internal.AiDevToolsSetting.browser_setting:type_name -> google.internal.cloud.code.v1internal.BrowserSetting
	24, // 25: google.internal.cloud.code.v1internal.AiDevToolsSetting.preview_feature_setting:type_name -> google.internal.cloud.code.v1internal.PreviewFeatureSetting
	25, // 26: google.internal.cloud.code.v1internal.AiDevToolsSetting.agent_setting:type_name -> google.internal.cloud.code.v1internal.AgentSetting
	26, // 27: google.internal.cloud.code.v1internal.AiDevToolsSetting.cli_feature_setting:type_name -> google.internal.cloud.code.v1internal.CliFeatureSetting
	30, // 28: google.internal.cloud.code.v1internal.CliFeatureSetting.extensions_setting:type_name -> google.internal.cloud.code.v1internal.CliFeatureSetting.ExtensionsSetting
	20, // 29: google.internal.cloud.code.v1internal.FetchAdminControlsResponse.recitation_policy:type_name -> google.internal.cloud.code.v1internal.RecitationPolicy
	8,  // 30: google.internal.cloud.code.v1internal.FetchAdminControlsResponse.grounding_type:type_name -> google.internal.cloud.code.v1internal.FetchAdminControlsResponse.GroundingType
	21, // 31: google.internal.cloud.code.v1internal.FetchAdminControlsResponse.mcp_setting:type_name -> google.internal.cloud.code.v1internal.McpSetting
	22, // 32: google.internal.cloud.code.v1internal.FetchAdminControlsResponse.turbo_mode_setting:type_name -> google.internal.cloud.code.v1internal.TurboModeSetting
	23, // 33: google.internal.cloud.code.v1internal.FetchAdminControlsResponse.browser_setting:type_name -> google.internal.cloud.code.v1internal.BrowserSetting
	24, // 34: google.internal.cloud.code.v1internal.FetchAdminControlsResponse.preview_feature_setting:type_name -> google.internal.cloud.code.v1internal.PreviewFeatureSetting
	25, // 35: google.internal.cloud.code.v1internal.FetchAdminControlsResponse.agent_setting:type_name -> google.internal.cloud.code.v1internal.AgentSetting
	26, // 36: google.internal.cloud.code.v1internal.FetchAdminControlsResponse.cli_feature_setting:type_name -> google.internal.cloud.code.v1internal.CliFeatureSetting
	37, // [37:37] is the sub-list for method output_type
	37, // [37:37] is the sub-list for method input_type
	37, // [37:37] is the sub-list for extension type_name
	37, // [37:37] is the sub-list for extension extendee
	0,  // [0:37] is the sub-list for field type_name
}

func init() { file_google_internal_cloud_code_v1internal_onboarding_proto_init() }
func file_google_internal_cloud_code_v1internal_onboarding_proto_init() {
	if File_google_internal_cloud_code_v1internal_onboarding_proto != nil {
		return
	}
	file_google_internal_cloud_code_v1internal_credits_proto_init()
	file_google_internal_cloud_code_v1internal_onboarding_proto_msgTypes[0].OneofWrappers = []any{}
	file_google_internal_cloud_code_v1internal_onboarding_proto_msgTypes[1].OneofWrappers = []any{}
	file_google_internal_cloud_code_v1internal_onboarding_proto_msgTypes[3].OneofWrappers = []any{}
	file_google_internal_cloud_code_v1internal_onboarding_proto_msgTypes[7].OneofWrappers = []any{}
	file_google_internal_cloud_code_v1internal_onboarding_proto_msgTypes[8].OneofWrappers = []any{}
	file_google_internal_cloud_code_v1internal_onboarding_proto_msgTypes[9].OneofWrappers = []any{}
	file_google_internal_cloud_code_v1internal_onboarding_proto_msgTypes[20].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_google_internal_cloud_code_v1internal_onboarding_proto_rawDesc), len(file_google_internal_cloud_code_v1internal_onboarding_proto_rawDesc)),
			NumEnums:      9,
			NumMessages:   22,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_google_internal_cloud_code_v1internal_onboarding_proto_goTypes,
		DependencyIndexes: file_google_internal_cloud_code_v1internal_onboarding_proto_depIdxs,
		EnumInfos:         file_google_internal_cloud_code_v1internal_onboarding_proto_enumTypes,
		MessageInfos:      file_google_internal_cloud_code_v1internal_onboarding_proto_msgTypes,
	}.Build()
	File_google_internal_cloud_code_v1internal_onboarding_proto = out.File
	file_google_internal_cloud_code_v1internal_onboarding_proto_goTypes = nil
	file_google_internal_cloud_code_v1internal_onboarding_proto_depIdxs = nil
}
