// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v4.25.1
// source: google/internal/cloud/code/v1internal/remote_context.proto

package v1internal

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type RemoteContext_RagState int32

const (
	RemoteContext_RAG_STATE_UNSPECIFIED RemoteContext_RagState = 0
	RemoteContext_RAG_DISABLED          RemoteContext_RagState = 1
	RemoteContext_RAG_FOUND             RemoteContext_RagState = 2
	RemoteContext_RAG_NOT_FOUND         RemoteContext_RagState = 3
	RemoteContext_RAG_ERROR             RemoteContext_RagState = 4
)

// Enum value maps for RemoteContext_RagState.
var (
	RemoteContext_RagState_name = map[int32]string{
		0: "RAG_STATE_UNSPECIFIED",
		1: "RAG_DISABLED",
		2: "RAG_FOUND",
		3: "RAG_NOT_FOUND",
		4: "RAG_ERROR",
	}
	RemoteContext_RagState_value = map[string]int32{
		"RAG_STATE_UNSPECIFIED": 0,
		"RAG_DISABLED":          1,
		"RAG_FOUND":             2,
		"RAG_NOT_FOUND":         3,
		"RAG_ERROR":             4,
	}
)

func (x RemoteContext_RagState) Enum() *RemoteContext_RagState {
	p := new(RemoteContext_RagState)
	*p = x
	return p
}

func (x RemoteContext_RagState) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (RemoteContext_RagState) Descriptor() protoreflect.EnumDescriptor {
	return file_google_internal_cloud_code_v1internal_remote_context_proto_enumTypes[0].Descriptor()
}

func (RemoteContext_RagState) Type() protoreflect.EnumType {
	return &file_google_internal_cloud_code_v1internal_remote_context_proto_enumTypes[0]
}

func (x RemoteContext_RagState) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use RemoteContext_RagState.Descriptor instead.
func (RemoteContext_RagState) EnumDescriptor() ([]byte, []int) {
	return file_google_internal_cloud_code_v1internal_remote_context_proto_rawDescGZIP(), []int{0, 0}
}

type RemoteSnippet_SnippetType int32

const (
	RemoteSnippet_UNKNOWN RemoteSnippet_SnippetType = 0
	RemoteSnippet_CODE    RemoteSnippet_SnippetType = 1
	RemoteSnippet_SUMMARY RemoteSnippet_SnippetType = 2
)

// Enum value maps for RemoteSnippet_SnippetType.
var (
	RemoteSnippet_SnippetType_name = map[int32]string{
		0: "UNKNOWN",
		1: "CODE",
		2: "SUMMARY",
	}
	RemoteSnippet_SnippetType_value = map[string]int32{
		"UNKNOWN": 0,
		"CODE":    1,
		"SUMMARY": 2,
	}
)

func (x RemoteSnippet_SnippetType) Enum() *RemoteSnippet_SnippetType {
	p := new(RemoteSnippet_SnippetType)
	*p = x
	return p
}

func (x RemoteSnippet_SnippetType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (RemoteSnippet_SnippetType) Descriptor() protoreflect.EnumDescriptor {
	return file_google_internal_cloud_code_v1internal_remote_context_proto_enumTypes[1].Descriptor()
}

func (RemoteSnippet_SnippetType) Type() protoreflect.EnumType {
	return &file_google_internal_cloud_code_v1internal_remote_context_proto_enumTypes[1]
}

func (x RemoteSnippet_SnippetType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use RemoteSnippet_SnippetType.Descriptor instead.
func (RemoteSnippet_SnippetType) EnumDescriptor() ([]byte, []int) {
	return file_google_internal_cloud_code_v1internal_remote_context_proto_rawDescGZIP(), []int{1, 0}
}

type RemoteContext struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	RagState       RemoteContext_RagState `protobuf:"varint,1,opt,name=rag_state,json=ragState,proto3,enum=google.internal.cloud.code.v1internal.RemoteContext_RagState" json:"rag_state,omitempty"`
	RemoteSnippets []*RemoteSnippet       `protobuf:"bytes,2,rep,name=remote_snippets,json=remoteSnippets,proto3" json:"remote_snippets,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *RemoteContext) Reset() {
	*x = RemoteContext{}
	mi := &file_google_internal_cloud_code_v1internal_remote_context_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RemoteContext) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RemoteContext) ProtoMessage() {}

func (x *RemoteContext) ProtoReflect() protoreflect.Message {
	mi := &file_google_internal_cloud_code_v1internal_remote_context_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RemoteContext.ProtoReflect.Descriptor instead.
func (*RemoteContext) Descriptor() ([]byte, []int) {
	return file_google_internal_cloud_code_v1internal_remote_context_proto_rawDescGZIP(), []int{0}
}

func (x *RemoteContext) GetRagState() RemoteContext_RagState {
	if x != nil {
		return x.RagState
	}
	return RemoteContext_RAG_STATE_UNSPECIFIED
}

func (x *RemoteContext) GetRemoteSnippets() []*RemoteSnippet {
	if x != nil {
		return x.RemoteSnippets
	}
	return nil
}

type RemoteSnippet struct {
	state         protoimpl.MessageState    `protogen:"open.v1"`
	Type          RemoteSnippet_SnippetType `protobuf:"varint,1,opt,name=type,proto3,enum=google.internal.cloud.code.v1internal.RemoteSnippet_SnippetType" json:"type,omitempty"`
	Content       string                    `protobuf:"bytes,2,opt,name=content,proto3" json:"content,omitempty"`
	FileUrl       string                    `protobuf:"bytes,3,opt,name=file_url,json=fileUrl,proto3" json:"file_url,omitempty"`
	FilePath      string                    `protobuf:"bytes,4,opt,name=file_path,json=filePath,proto3" json:"file_path,omitempty"`
	RepoUrl       string                    `protobuf:"bytes,5,opt,name=repo_url,json=repoUrl,proto3" json:"repo_url,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RemoteSnippet) Reset() {
	*x = RemoteSnippet{}
	mi := &file_google_internal_cloud_code_v1internal_remote_context_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RemoteSnippet) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RemoteSnippet) ProtoMessage() {}

func (x *RemoteSnippet) ProtoReflect() protoreflect.Message {
	mi := &file_google_internal_cloud_code_v1internal_remote_context_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RemoteSnippet.ProtoReflect.Descriptor instead.
func (*RemoteSnippet) Descriptor() ([]byte, []int) {
	return file_google_internal_cloud_code_v1internal_remote_context_proto_rawDescGZIP(), []int{1}
}

func (x *RemoteSnippet) GetType() RemoteSnippet_SnippetType {
	if x != nil {
		return x.Type
	}
	return RemoteSnippet_UNKNOWN
}

func (x *RemoteSnippet) GetContent() string {
	if x != nil {
		return x.Content
	}
	return ""
}

func (x *RemoteSnippet) GetFileUrl() string {
	if x != nil {
		return x.FileUrl
	}
	return ""
}

func (x *RemoteSnippet) GetFilePath() string {
	if x != nil {
		return x.FilePath
	}
	return ""
}

func (x *RemoteSnippet) GetRepoUrl() string {
	if x != nil {
		return x.RepoUrl
	}
	return ""
}

var File_google_internal_cloud_code_v1internal_remote_context_proto protoreflect.FileDescriptor

const file_google_internal_cloud_code_v1internal_remote_context_proto_rawDesc = "" +
	"\n" +
	":google/internal/cloud/code/v1internal/remote_context.proto\x12%google.internal.cloud.code.v1internal\"\xb4\x02\n" +
	"\rRemoteContext\x12Z\n" +
	"\trag_state\x18\x01 \x01(\x0e2=.google.internal.cloud.code.v1internal.RemoteContext.RagStateR\bragState\x12]\n" +
	"\x0fremote_snippets\x18\x02 \x03(\v24.google.internal.cloud.code.v1internal.RemoteSnippetR\x0eremoteSnippets\"h\n" +
	"\bRagState\x12\x19\n" +
	"\x15RAG_STATE_UNSPECIFIED\x10\x00\x12\x10\n" +
	"\fRAG_DISABLED\x10\x01\x12\r\n" +
	"\tRAG_FOUND\x10\x02\x12\x11\n" +
	"\rRAG_NOT_FOUND\x10\x03\x12\r\n" +
	"\tRAG_ERROR\x10\x04\"\x85\x02\n" +
	"\rRemoteSnippet\x12T\n" +
	"\x04type\x18\x01 \x01(\x0e2@.google.internal.cloud.code.v1internal.RemoteSnippet.SnippetTypeR\x04type\x12\x18\n" +
	"\acontent\x18\x02 \x01(\tR\acontent\x12\x19\n" +
	"\bfile_url\x18\x03 \x01(\tR\afileUrl\x12\x1b\n" +
	"\tfile_path\x18\x04 \x01(\tR\bfilePath\x12\x19\n" +
	"\brepo_url\x18\x05 \x01(\tR\arepoUrl\"1\n" +
	"\vSnippetType\x12\v\n" +
	"\aUNKNOWN\x10\x00\x12\b\n" +
	"\x04CODE\x10\x01\x12\v\n" +
	"\aSUMMARY\x10\x02BCZAgithub.com/router-for-me/CLIProxyAPI/v6/internal/proto/v1internalb\x06proto3"

var (
	file_google_internal_cloud_code_v1internal_remote_context_proto_rawDescOnce sync.Once
	file_google_internal_cloud_code_v1internal_remote_context_proto_rawDescData []byte
)

func file_google_internal_cloud_code_v1internal_remote_context_proto_rawDescGZIP() []byte {
	file_google_internal_cloud_code_v1internal_remote_context_proto_rawDescOnce.Do(func() {
		file_google_internal_cloud_code_v1internal_remote_context_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_google_internal_cloud_code_v1internal_remote_context_proto_rawDesc), len(file_google_internal_cloud_code_v1internal_remote_context_proto_rawDesc)))
	})
	return file_google_internal_cloud_code_v1internal_remote_context_proto_rawDescData
}

var file_google_internal_cloud_code_v1internal_remote_context_proto_enumTypes = make([]protoimpl.EnumInfo, 2)
var file_google_internal_cloud_code_v1internal_remote_context_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_google_internal_cloud_code_v1internal_remote_context_proto_goTypes = []any{
	(RemoteContext_RagState)(0),    // 0: google.internal.cloud.code.v1internal.RemoteContext.RagState
	(RemoteSnippet_SnippetType)(0), // 1: google.internal.cloud.code.v1internal.RemoteSnippet.SnippetType
	(*RemoteContext)(nil),          // 2: google.internal.cloud.code.v1internal.RemoteContext
	(*RemoteSnippet)(nil),          // 3: google.internal.cloud.code.v1internal.RemoteSnippet
}
var file_google_internal_cloud_code_v1internal_remote_context_proto_depIdxs = []int32{
	0, // 0: google.internal.cloud.code.v1internal.RemoteContext.rag_state:type_name -> google.internal.cloud.code.v1internal.RemoteContext.RagState
	3, // 1: google.internal.cloud.code.v1internal.RemoteContext.remote_snippets:type_name -> google.internal.cloud.code.v1internal.RemoteSnippet
	1, // 2: google.internal.cloud.code.v1internal.RemoteSnippet.type:type_name -> google.internal.cloud.code.v1internal.RemoteSnippet.SnippetType
	3, // [3:3] is the sub-list for method output_type
	3, // [3:3] is the sub-list for method input_type
	3, // [3:3] is the sub-list for extension type_name
	3, // [3:3] is the sub-list for extension extendee
	0, // [0:3] is the sub-list for field type_name
}

func init() { file_google_internal_cloud_code_v1internal_remote_context_proto_init() }
func file_google_internal_cloud_code_v1internal_remote_context_proto_init() {
	if File_google_internal_cloud_code_v1internal_remote_context_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_google_internal_cloud_code_v1internal_remote_context_proto_rawDesc), len(file_google_internal_cloud_code_v1internal_remote_context_proto_rawDesc)),
			NumEnums:      2,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_google_internal_cloud_code_v1internal_remote_context_proto_goTypes,
		DependencyIndexes: file_google_internal_cloud_code_v1internal_remote_context_proto_depIdxs,
		EnumInfos:         file_google_internal_cloud_code_v1internal_remote_context_proto_enumTypes,
		MessageInfos:      file_google_internal_cloud_code_v1internal_remote_context_proto_msgTypes,
	}.Build()
	File_google_internal_cloud_code_v1internal_remote_context_proto = out.File
	file_google_internal_cloud_code_v1internal_remote_context_proto_goTypes = nil
	file_google_internal_cloud_code_v1internal_remote_context_proto_depIdxs = nil
}
