// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v4.25.1
// source: third_party/jetski/codeium_common_pb/codeium_common.proto

package codeium

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Model int32

const (
	Model_MODEL_UNSPECIFIED Model = 0
)

// Enum value maps for Model.
var (
	Model_name = map[int32]string{
		0: "MODEL_UNSPECIFIED",
	}
	Model_value = map[string]int32{
		"MODEL_UNSPECIFIED": 0,
	}
)

func (x Model) Enum() *Model {
	p := new(Model)
	*p = x
	return p
}

func (x Model) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Model) Descriptor() protoreflect.EnumDescriptor {
	return file_third_party_jetski_codeium_common_pb_codeium_common_proto_enumTypes[0].Descriptor()
}

func (Model) Type() protoreflect.EnumType {
	return &file_third_party_jetski_codeium_common_pb_codeium_common_proto_enumTypes[0]
}

func (x Model) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use Model.Descriptor instead.
func (Model) EnumDescriptor() ([]byte, []int) {
	return file_third_party_jetski_codeium_common_pb_codeium_common_proto_rawDescGZIP(), []int{0}
}

type APIProvider int32

const (
	APIProvider_API_PROVIDER_UNSPECIFIED APIProvider = 0
)

// Enum value maps for APIProvider.
var (
	APIProvider_name = map[int32]string{
		0: "API_PROVIDER_UNSPECIFIED",
	}
	APIProvider_value = map[string]int32{
		"API_PROVIDER_UNSPECIFIED": 0,
	}
)

func (x APIProvider) Enum() *APIProvider {
	p := new(APIProvider)
	*p = x
	return p
}

func (x APIProvider) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (APIProvider) Descriptor() protoreflect.EnumDescriptor {
	return file_third_party_jetski_codeium_common_pb_codeium_common_proto_enumTypes[1].Descriptor()
}

func (APIProvider) Type() protoreflect.EnumType {
	return &file_third_party_jetski_codeium_common_pb_codeium_common_proto_enumTypes[1]
}

func (x APIProvider) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use APIProvider.Descriptor instead.
func (APIProvider) EnumDescriptor() ([]byte, []int) {
	return file_third_party_jetski_codeium_common_pb_codeium_common_proto_rawDescGZIP(), []int{1}
}

type ModelProvider int32

const (
	ModelProvider_MODEL_PROVIDER_UNSPECIFIED ModelProvider = 0
)

// Enum value maps for ModelProvider.
var (
	ModelProvider_name = map[int32]string{
		0: "MODEL_PROVIDER_UNSPECIFIED",
	}
	ModelProvider_value = map[string]int32{
		"MODEL_PROVIDER_UNSPECIFIED": 0,
	}
)

func (x ModelProvider) Enum() *ModelProvider {
	p := new(ModelProvider)
	*p = x
	return p
}

func (x ModelProvider) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (ModelProvider) Descriptor() protoreflect.EnumDescriptor {
	return file_third_party_jetski_codeium_common_pb_codeium_common_proto_enumTypes[2].Descriptor()
}

func (ModelProvider) Type() protoreflect.EnumType {
	return &file_third_party_jetski_codeium_common_pb_codeium_common_proto_enumTypes[2]
}

func (x ModelProvider) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use ModelProvider.Descriptor instead.
func (ModelProvider) EnumDescriptor() ([]byte, []int) {
	return file_third_party_jetski_codeium_common_pb_codeium_common_proto_rawDescGZIP(), []int{2}
}

type PromptTemplaterType int32

const (
	PromptTemplaterType_PROMPT_TEMPLATER_TYPE_UNSPECIFIED PromptTemplaterType = 0
)

// Enum value maps for PromptTemplaterType.
var (
	PromptTemplaterType_name = map[int32]string{
		0: "PROMPT_TEMPLATER_TYPE_UNSPECIFIED",
	}
	PromptTemplaterType_value = map[string]int32{
		"PROMPT_TEMPLATER_TYPE_UNSPECIFIED": 0,
	}
)

func (x PromptTemplaterType) Enum() *PromptTemplaterType {
	p := new(PromptTemplaterType)
	*p = x
	return p
}

func (x PromptTemplaterType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (PromptTemplaterType) Descriptor() protoreflect.EnumDescriptor {
	return file_third_party_jetski_codeium_common_pb_codeium_common_proto_enumTypes[3].Descriptor()
}

func (PromptTemplaterType) Type() protoreflect.EnumType {
	return &file_third_party_jetski_codeium_common_pb_codeium_common_proto_enumTypes[3]
}

func (x PromptTemplaterType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use PromptTemplaterType.Descriptor instead.
func (PromptTemplaterType) EnumDescriptor() ([]byte, []int) {
	return file_third_party_jetski_codeium_common_pb_codeium_common_proto_rawDescGZIP(), []int{3}
}

type ToolFormatterType int32

const (
	ToolFormatterType_TOOL_FORMATTER_TYPE_UNSPECIFIED ToolFormatterType = 0
)

// Enum value maps for ToolFormatterType.
var (
	ToolFormatterType_name = map[int32]string{
		0: "TOOL_FORMATTER_TYPE_UNSPECIFIED",
	}
	ToolFormatterType_value = map[string]int32{
		"TOOL_FORMATTER_TYPE_UNSPECIFIED": 0,
	}
)

func (x ToolFormatterType) Enum() *ToolFormatterType {
	p := new(ToolFormatterType)
	*p = x
	return p
}

func (x ToolFormatterType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (ToolFormatterType) Descriptor() protoreflect.EnumDescriptor {
	return file_third_party_jetski_codeium_common_pb_codeium_common_proto_enumTypes[4].Descriptor()
}

func (ToolFormatterType) Type() protoreflect.EnumType {
	return &file_third_party_jetski_codeium_common_pb_codeium_common_proto_enumTypes[4]
}

func (x ToolFormatterType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use ToolFormatterType.Descriptor instead.
func (ToolFormatterType) EnumDescriptor() ([]byte, []int) {
	return file_third_party_jetski_codeium_common_pb_codeium_common_proto_rawDescGZIP(), []int{4}
}

var File_third_party_jetski_codeium_common_pb_codeium_common_proto protoreflect.FileDescriptor

const file_third_party_jetski_codeium_common_pb_codeium_common_proto_rawDesc = "" +
	"\n" +
	"9third_party/jetski/codeium_common_pb/codeium_common.proto\x12\x15exa.codeium_common_pb*\x1e\n" +
	"\x05Model\x12\x15\n" +
	"\x11MODEL_UNSPECIFIED\x10\x00*+\n" +
	"\vAPIProvider\x12\x1c\n" +
	"\x18API_PROVIDER_UNSPECIFIED\x10\x00*/\n" +
	"\rModelProvider\x12\x1e\n" +
	"\x1aMODEL_PROVIDER_UNSPECIFIED\x10\x00*<\n" +
	"\x13PromptTemplaterType\x12%\n" +
	"!PROMPT_TEMPLATER_TYPE_UNSPECIFIED\x10\x00*8\n" +
	"\x11ToolFormatterType\x12#\n" +
	"\x1fTOOL_FORMATTER_TYPE_UNSPECIFIED\x10\x00BFZDgithub.com/router-for-me/CLIProxyAPI/v6/internal/proto/stubs/codeiumb\x06proto3"

var (
	file_third_party_jetski_codeium_common_pb_codeium_common_proto_rawDescOnce sync.Once
	file_third_party_jetski_codeium_common_pb_codeium_common_proto_rawDescData []byte
)

func file_third_party_jetski_codeium_common_pb_codeium_common_proto_rawDescGZIP() []byte {
	file_third_party_jetski_codeium_common_pb_codeium_common_proto_rawDescOnce.Do(func() {
		file_third_party_jetski_codeium_common_pb_codeium_common_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_third_party_jetski_codeium_common_pb_codeium_common_proto_rawDesc), len(file_third_party_jetski_codeium_common_pb_codeium_common_proto_rawDesc)))
	})
	return file_third_party_jetski_codeium_common_pb_codeium_common_proto_rawDescData
}

var file_third_party_jetski_codeium_common_pb_codeium_common_proto_enumTypes = make([]protoimpl.EnumInfo, 5)
var file_third_party_jetski_codeium_common_pb_codeium_common_proto_goTypes = []any{
	(Model)(0),               // 0: exa.codeium_common_pb.Model
	(APIProvider)(0),         // 1: exa.codeium_common_pb.APIProvider
	(ModelProvider)(0),       // 2: exa.codeium_common_pb.ModelProvider
	(PromptTemplaterType)(0), // 3: exa.codeium_common_pb.PromptTemplaterType
	(ToolFormatterType)(0),   // 4: exa.codeium_common_pb.ToolFormatterType
}
var file_third_party_jetski_codeium_common_pb_codeium_common_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_third_party_jetski_codeium_common_pb_codeium_common_proto_init() }
func file_third_party_jetski_codeium_common_pb_codeium_common_proto_init() {
	if File_third_party_jetski_codeium_common_pb_codeium_common_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_third_party_jetski_codeium_common_pb_codeium_common_proto_rawDesc), len(file_third_party_jetski_codeium_common_pb_codeium_common_proto_rawDesc)),
			NumEnums:      5,
			NumMessages:   0,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_third_party_jetski_codeium_common_pb_codeium_common_proto_goTypes,
		DependencyIndexes: file_third_party_jetski_codeium_common_pb_codeium_common_proto_depIdxs,
		EnumInfos:         file_third_party_jetski_codeium_common_pb_codeium_common_proto_enumTypes,
	}.Build()
	File_third_party_jetski_codeium_common_pb_codeium_common_proto = out.File
	file_third_party_jetski_codeium_common_pb_codeium_common_proto_goTypes = nil
	file_third_party_jetski_codeium_common_pb_codeium_common_proto_depIdxs = nil
}
