// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v4.25.1
// source: google/cloud/aiplatform/master/tool.proto

package aiplatform

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	structpb "google.golang.org/protobuf/types/known/structpb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type FunctionDeclaration struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Description   string                 `protobuf:"bytes,2,opt,name=description,proto3" json:"description,omitempty"`
	Parameters    *structpb.Struct       `protobuf:"bytes,3,opt,name=parameters,proto3" json:"parameters,omitempty"`
	Response      *structpb.Struct       `protobuf:"bytes,4,opt,name=response,proto3" json:"response,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FunctionDeclaration) Reset() {
	*x = FunctionDeclaration{}
	mi := &file_google_cloud_aiplatform_master_tool_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FunctionDeclaration) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FunctionDeclaration) ProtoMessage() {}

func (x *FunctionDeclaration) ProtoReflect() protoreflect.Message {
	mi := &file_google_cloud_aiplatform_master_tool_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FunctionDeclaration.ProtoReflect.Descriptor instead.
func (*FunctionDeclaration) Descriptor() ([]byte, []int) {
	return file_google_cloud_aiplatform_master_tool_proto_rawDescGZIP(), []int{0}
}

func (x *FunctionDeclaration) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *FunctionDeclaration) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *FunctionDeclaration) GetParameters() *structpb.Struct {
	if x != nil {
		return x.Parameters
	}
	return nil
}

func (x *FunctionDeclaration) GetResponse() *structpb.Struct {
	if x != nil {
		return x.Response
	}
	return nil
}

type FunctionCall struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Args          *structpb.Struct       `protobuf:"bytes,2,opt,name=args,proto3" json:"args,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FunctionCall) Reset() {
	*x = FunctionCall{}
	mi := &file_google_cloud_aiplatform_master_tool_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FunctionCall) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FunctionCall) ProtoMessage() {}

func (x *FunctionCall) ProtoReflect() protoreflect.Message {
	mi := &file_google_cloud_aiplatform_master_tool_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FunctionCall.ProtoReflect.Descriptor instead.
func (*FunctionCall) Descriptor() ([]byte, []int) {
	return file_google_cloud_aiplatform_master_tool_proto_rawDescGZIP(), []int{1}
}

func (x *FunctionCall) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *FunctionCall) GetArgs() *structpb.Struct {
	if x != nil {
		return x.Args
	}
	return nil
}

type FunctionResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Response      *structpb.Struct       `protobuf:"bytes,2,opt,name=response,proto3" json:"response,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FunctionResponse) Reset() {
	*x = FunctionResponse{}
	mi := &file_google_cloud_aiplatform_master_tool_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FunctionResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FunctionResponse) ProtoMessage() {}

func (x *FunctionResponse) ProtoReflect() protoreflect.Message {
	mi := &file_google_cloud_aiplatform_master_tool_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FunctionResponse.ProtoReflect.Descriptor instead.
func (*FunctionResponse) Descriptor() ([]byte, []int) {
	return file_google_cloud_aiplatform_master_tool_proto_rawDescGZIP(), []int{2}
}

func (x *FunctionResponse) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *FunctionResponse) GetResponse() *structpb.Struct {
	if x != nil {
		return x.Response
	}
	return nil
}

type GenerateContentRequest struct {
	state             protoimpl.MessageState `protogen:"open.v1"`
	Model             string                 `protobuf:"bytes,1,opt,name=model,proto3" json:"model,omitempty"`
	Contents          []*Content             `protobuf:"bytes,2,rep,name=contents,proto3" json:"contents,omitempty"`
	SystemInstruction *Content               `protobuf:"bytes,6,opt,name=system_instruction,json=systemInstruction,proto3" json:"system_instruction,omitempty"`
	Tools             []*Tool                `protobuf:"bytes,5,rep,name=tools,proto3" json:"tools,omitempty"`
	ToolConfig        *ToolConfig            `protobuf:"bytes,7,opt,name=tool_config,json=toolConfig,proto3" json:"tool_config,omitempty"`
	GenerationConfig  *GenerationConfig      `protobuf:"bytes,4,opt,name=generation_config,json=generationConfig,proto3" json:"generation_config,omitempty"`
	SafetySettings    []*SafetySetting       `protobuf:"bytes,3,rep,name=safety_settings,json=safetySettings,proto3" json:"safety_settings,omitempty"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *GenerateContentRequest) Reset() {
	*x = GenerateContentRequest{}
	mi := &file_google_cloud_aiplatform_master_tool_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GenerateContentRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GenerateContentRequest) ProtoMessage() {}

func (x *GenerateContentRequest) ProtoReflect() protoreflect.Message {
	mi := &file_google_cloud_aiplatform_master_tool_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GenerateContentRequest.ProtoReflect.Descriptor instead.
func (*GenerateContentRequest) Descriptor() ([]byte, []int) {
	return file_google_cloud_aiplatform_master_tool_proto_rawDescGZIP(), []int{3}
}

func (x *GenerateContentRequest) GetModel() string {
	if x != nil {
		return x.Model
	}
	return ""
}

func (x *GenerateContentRequest) GetContents() []*Content {
	if x != nil {
		return x.Contents
	}
	return nil
}

func (x *GenerateContentRequest) GetSystemInstruction() *Content {
	if x != nil {
		return x.SystemInstruction
	}
	return nil
}

func (x *GenerateContentRequest) GetTools() []*Tool {
	if x != nil {
		return x.Tools
	}
	return nil
}

func (x *GenerateContentRequest) GetToolConfig() *ToolConfig {
	if x != nil {
		return x.ToolConfig
	}
	return nil
}

func (x *GenerateContentRequest) GetGenerationConfig() *GenerationConfig {
	if x != nil {
		return x.GenerationConfig
	}
	return nil
}

func (x *GenerateContentRequest) GetSafetySettings() []*SafetySetting {
	if x != nil {
		return x.SafetySettings
	}
	return nil
}

type GenerateContentResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Candidates    []*Candidate           `protobuf:"bytes,1,rep,name=candidates,proto3" json:"candidates,omitempty"`
	UsageMetadata *UsageMetadata         `protobuf:"bytes,2,opt,name=usage_metadata,json=usageMetadata,proto3" json:"usage_metadata,omitempty"`
	ModelVersion  string                 `protobuf:"bytes,3,opt,name=model_version,json=modelVersion,proto3" json:"model_version,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GenerateContentResponse) Reset() {
	*x = GenerateContentResponse{}
	mi := &file_google_cloud_aiplatform_master_tool_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GenerateContentResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GenerateContentResponse) ProtoMessage() {}

func (x *GenerateContentResponse) ProtoReflect() protoreflect.Message {
	mi := &file_google_cloud_aiplatform_master_tool_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GenerateContentResponse.ProtoReflect.Descriptor instead.
func (*GenerateContentResponse) Descriptor() ([]byte, []int) {
	return file_google_cloud_aiplatform_master_tool_proto_rawDescGZIP(), []int{4}
}

func (x *GenerateContentResponse) GetCandidates() []*Candidate {
	if x != nil {
		return x.Candidates
	}
	return nil
}

func (x *GenerateContentResponse) GetUsageMetadata() *UsageMetadata {
	if x != nil {
		return x.UsageMetadata
	}
	return nil
}

func (x *GenerateContentResponse) GetModelVersion() string {
	if x != nil {
		return x.ModelVersion
	}
	return ""
}

type Content struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Role          string                 `protobuf:"bytes,1,opt,name=role,proto3" json:"role,omitempty"`
	Parts         []*Part                `protobuf:"bytes,2,rep,name=parts,proto3" json:"parts,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Content) Reset() {
	*x = Content{}
	mi := &file_google_cloud_aiplatform_master_tool_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Content) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Content) ProtoMessage() {}

func (x *Content) ProtoReflect() protoreflect.Message {
	mi := &file_google_cloud_aiplatform_master_tool_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Content.ProtoReflect.Descriptor instead.
func (*Content) Descriptor() ([]byte, []int) {
	return file_google_cloud_aiplatform_master_tool_proto_rawDescGZIP(), []int{5}
}

func (x *Content) GetRole() string {
	if x != nil {
		return x.Role
	}
	return ""
}

func (x *Content) GetParts() []*Part {
	if x != nil {
		return x.Parts
	}
	return nil
}

type Part struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to Data:
	//
	//	*Part_Text
	//	*Part_FunctionCall
	//	*Part_FunctionResponse
	//	*Part_InlineData
	Data          isPart_Data `protobuf_oneof:"data"`
	Thought       *bool       `protobuf:"varint,10,opt,name=thought,proto3,oneof" json:"thought,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Part) Reset() {
	*x = Part{}
	mi := &file_google_cloud_aiplatform_master_tool_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Part) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Part) ProtoMessage() {}

func (x *Part) ProtoReflect() protoreflect.Message {
	mi := &file_google_cloud_aiplatform_master_tool_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Part.ProtoReflect.Descriptor instead.
func (*Part) Descriptor() ([]byte, []int) {
	return file_google_cloud_aiplatform_master_tool_proto_rawDescGZIP(), []int{6}
}

func (x *Part) GetData() isPart_Data {
	if x != nil {
		return x.Data
	}
	return nil
}

func (x *Part) GetText() string {
	if x != nil {
		if x, ok := x.Data.(*Part_Text); ok {
			return x.Text
		}
	}
	return ""
}

func (x *Part) GetFunctionCall() *FunctionCall {
	if x != nil {
		if x, ok := x.Data.(*Part_FunctionCall); ok {
			return x.FunctionCall
		}
	}
	return nil
}

func (x *Part) GetFunctionResponse() *FunctionResponse {
	if x != nil {
		if x, ok := x.Data.(*Part_FunctionResponse); ok {
			return x.FunctionResponse
		}
	}
	return nil
}

func (x *Part) GetInlineData() *Blob {
	if x != nil {
		if x, ok := x.Data.(*Part_InlineData); ok {
			return x.InlineData
		}
	}
	return nil
}

func (x *Part) GetThought() bool {
	if x != nil && x.Thought != nil {
		return *x.Thought
	}
	return false
}

type isPart_Data interface {
	isPart_Data()
}

type Part_Text struct {
	Text string `protobuf:"bytes,1,opt,name=text,proto3,oneof"`
}

type Part_FunctionCall struct {
	FunctionCall *FunctionCall `protobuf:"bytes,3,opt,name=function_call,json=functionCall,proto3,oneof"`
}

type Part_FunctionResponse struct {
	FunctionResponse *FunctionResponse `protobuf:"bytes,4,opt,name=function_response,json=functionResponse,proto3,oneof"`
}

type Part_InlineData struct {
	InlineData *Blob `protobuf:"bytes,2,opt,name=inline_data,json=inlineData,proto3,oneof"`
}

func (*Part_Text) isPart_Data() {}

func (*Part_FunctionCall) isPart_Data() {}

func (*Part_FunctionResponse) isPart_Data() {}

func (*Part_InlineData) isPart_Data() {}

type Blob struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	MimeType      string                 `protobuf:"bytes,1,opt,name=mime_type,json=mimeType,proto3" json:"mime_type,omitempty"`
	Data          []byte                 `protobuf:"bytes,2,opt,name=data,proto3" json:"data,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Blob) Reset() {
	*x = Blob{}
	mi := &file_google_cloud_aiplatform_master_tool_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Blob) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Blob) ProtoMessage() {}

func (x *Blob) ProtoReflect() protoreflect.Message {
	mi := &file_google_cloud_aiplatform_master_tool_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Blob.ProtoReflect.Descriptor instead.
func (*Blob) Descriptor() ([]byte, []int) {
	return file_google_cloud_aiplatform_master_tool_proto_rawDescGZIP(), []int{7}
}

func (x *Blob) GetMimeType() string {
	if x != nil {
		return x.MimeType
	}
	return ""
}

func (x *Blob) GetData() []byte {
	if x != nil {
		return x.Data
	}
	return nil
}

type Candidate struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Content       *Content               `protobuf:"bytes,1,opt,name=content,proto3" json:"content,omitempty"`
	FinishReason  string                 `protobuf:"bytes,2,opt,name=finish_reason,json=finishReason,proto3" json:"finish_reason,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Candidate) Reset() {
	*x = Candidate{}
	mi := &file_google_cloud_aiplatform_master_tool_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Candidate) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Candidate) ProtoMessage() {}

func (x *Candidate) ProtoReflect() protoreflect.Message {
	mi := &file_google_cloud_aiplatform_master_tool_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Candidate.ProtoReflect.Descriptor instead.
func (*Candidate) Descriptor() ([]byte, []int) {
	return file_google_cloud_aiplatform_master_tool_proto_rawDescGZIP(), []int{8}
}

func (x *Candidate) GetContent() *Content {
	if x != nil {
		return x.Content
	}
	return nil
}

func (x *Candidate) GetFinishReason() string {
	if x != nil {
		return x.FinishReason
	}
	return ""
}

type UsageMetadata struct {
	state                protoimpl.MessageState `protogen:"open.v1"`
	PromptTokenCount     int32                  `protobuf:"varint,1,opt,name=prompt_token_count,json=promptTokenCount,proto3" json:"prompt_token_count,omitempty"`
	CandidatesTokenCount int32                  `protobuf:"varint,2,opt,name=candidates_token_count,json=candidatesTokenCount,proto3" json:"candidates_token_count,omitempty"`
	TotalTokenCount      int32                  `protobuf:"varint,3,opt,name=total_token_count,json=totalTokenCount,proto3" json:"total_token_count,omitempty"`
	unknownFields        protoimpl.UnknownFields
	sizeCache            protoimpl.SizeCache
}

func (x *UsageMetadata) Reset() {
	*x = UsageMetadata{}
	mi := &file_google_cloud_aiplatform_master_tool_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UsageMetadata) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UsageMetadata) ProtoMessage() {}

func (x *UsageMetadata) ProtoReflect() protoreflect.Message {
	mi := &file_google_cloud_aiplatform_master_tool_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UsageMetadata.ProtoReflect.Descriptor instead.
func (*UsageMetadata) Descriptor() ([]byte, []int) {
	return file_google_cloud_aiplatform_master_tool_proto_rawDescGZIP(), []int{9}
}

func (x *UsageMetadata) GetPromptTokenCount() int32 {
	if x != nil {
		return x.PromptTokenCount
	}
	return 0
}

func (x *UsageMetadata) GetCandidatesTokenCount() int32 {
	if x != nil {
		return x.CandidatesTokenCount
	}
	return 0
}

func (x *UsageMetadata) GetTotalTokenCount() int32 {
	if x != nil {
		return x.TotalTokenCount
	}
	return 0
}

type Tool struct {
	state                protoimpl.MessageState `protogen:"open.v1"`
	FunctionDeclarations []*FunctionDeclaration `protobuf:"bytes,1,rep,name=function_declarations,json=functionDeclarations,proto3" json:"function_declarations,omitempty"`
	unknownFields        protoimpl.UnknownFields
	sizeCache            protoimpl.SizeCache
}

func (x *Tool) Reset() {
	*x = Tool{}
	mi := &file_google_cloud_aiplatform_master_tool_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Tool) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Tool) ProtoMessage() {}

func (x *Tool) ProtoReflect() protoreflect.Message {
	mi := &file_google_cloud_aiplatform_master_tool_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Tool.ProtoReflect.Descriptor instead.
func (*Tool) Descriptor() ([]byte, []int) {
	return file_google_cloud_aiplatform_master_tool_proto_rawDescGZIP(), []int{10}
}

func (x *Tool) GetFunctionDeclarations() []*FunctionDeclaration {
	if x != nil {
		return x.FunctionDeclarations
	}
	return nil
}

type ToolConfig struct {
	state                 protoimpl.MessageState `protogen:"open.v1"`
	FunctionCallingConfig *FunctionCallingConfig `protobuf:"bytes,1,opt,name=function_calling_config,json=functionCallingConfig,proto3" json:"function_calling_config,omitempty"`
	unknownFields         protoimpl.UnknownFields
	sizeCache             protoimpl.SizeCache
}

func (x *ToolConfig) Reset() {
	*x = ToolConfig{}
	mi := &file_google_cloud_aiplatform_master_tool_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ToolConfig) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ToolConfig) ProtoMessage() {}

func (x *ToolConfig) ProtoReflect() protoreflect.Message {
	mi := &file_google_cloud_aiplatform_master_tool_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ToolConfig.ProtoReflect.Descriptor instead.
func (*ToolConfig) Descriptor() ([]byte, []int) {
	return file_google_cloud_aiplatform_master_tool_proto_rawDescGZIP(), []int{11}
}

func (x *ToolConfig) GetFunctionCallingConfig() *FunctionCallingConfig {
	if x != nil {
		return x.FunctionCallingConfig
	}
	return nil
}

type FunctionCallingConfig struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Mode          string                 `protobuf:"bytes,1,opt,name=mode,proto3" json:"mode,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FunctionCallingConfig) Reset() {
	*x = FunctionCallingConfig{}
	mi := &file_google_cloud_aiplatform_master_tool_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FunctionCallingConfig) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FunctionCallingConfig) ProtoMessage() {}

func (x *FunctionCallingConfig) ProtoReflect() protoreflect.Message {
	mi := &file_google_cloud_aiplatform_master_tool_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FunctionCallingConfig.ProtoReflect.Descriptor instead.
func (*FunctionCallingConfig) Descriptor() ([]byte, []int) {
	return file_google_cloud_aiplatform_master_tool_proto_rawDescGZIP(), []int{12}
}

func (x *FunctionCallingConfig) GetMode() string {
	if x != nil {
		return x.Mode
	}
	return ""
}

type GenerationConfig struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	Temperature     *float32               `protobuf:"fixed32,1,opt,name=temperature,proto3,oneof" json:"temperature,omitempty"`
	TopP            *float32               `protobuf:"fixed32,2,opt,name=top_p,json=topP,proto3,oneof" json:"top_p,omitempty"`
	TopK            *int32                 `protobuf:"varint,3,opt,name=top_k,json=topK,proto3,oneof" json:"top_k,omitempty"`
	MaxOutputTokens *int32                 `protobuf:"varint,5,opt,name=max_output_tokens,json=maxOutputTokens,proto3,oneof" json:"max_output_tokens,omitempty"`
	StopSequences   []string               `protobuf:"bytes,6,rep,name=stop_sequences,json=stopSequences,proto3" json:"stop_sequences,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *GenerationConfig) Reset() {
	*x = GenerationConfig{}
	mi := &file_google_cloud_aiplatform_master_tool_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GenerationConfig) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GenerationConfig) ProtoMessage() {}

func (x *GenerationConfig) ProtoReflect() protoreflect.Message {
	mi := &file_google_cloud_aiplatform_master_tool_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GenerationConfig.ProtoReflect.Descriptor instead.
func (*GenerationConfig) Descriptor() ([]byte, []int) {
	return file_google_cloud_aiplatform_master_tool_proto_rawDescGZIP(), []int{13}
}

func (x *GenerationConfig) GetTemperature() float32 {
	if x != nil && x.Temperature != nil {
		return *x.Temperature
	}
	return 0
}

func (x *GenerationConfig) GetTopP() float32 {
	if x != nil && x.TopP != nil {
		return *x.TopP
	}
	return 0
}

func (x *GenerationConfig) GetTopK() int32 {
	if x != nil && x.TopK != nil {
		return *x.TopK
	}
	return 0
}

func (x *GenerationConfig) GetMaxOutputTokens() int32 {
	if x != nil && x.MaxOutputTokens != nil {
		return *x.MaxOutputTokens
	}
	return 0
}

func (x *GenerationConfig) GetStopSequences() []string {
	if x != nil {
		return x.StopSequences
	}
	return nil
}

type SafetySetting struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Category      string                 `protobuf:"bytes,1,opt,name=category,proto3" json:"category,omitempty"`
	Threshold     string                 `protobuf:"bytes,2,opt,name=threshold,proto3" json:"threshold,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SafetySetting) Reset() {
	*x = SafetySetting{}
	mi := &file_google_cloud_aiplatform_master_tool_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SafetySetting) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SafetySetting) ProtoMessage() {}

func (x *SafetySetting) ProtoReflect() protoreflect.Message {
	mi := &file_google_cloud_aiplatform_master_tool_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SafetySetting.ProtoReflect.Descriptor instead.
func (*SafetySetting) Descriptor() ([]byte, []int) {
	return file_google_cloud_aiplatform_master_tool_proto_rawDescGZIP(), []int{14}
}

func (x *SafetySetting) GetCategory() string {
	if x != nil {
		return x.Category
	}
	return ""
}

func (x *SafetySetting) GetThreshold() string {
	if x != nil {
		return x.Threshold
	}
	return ""
}

type CountTokensRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Model         string                 `protobuf:"bytes,1,opt,name=model,proto3" json:"model,omitempty"`
	Contents      []*Content             `protobuf:"bytes,2,rep,name=contents,proto3" json:"contents,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CountTokensRequest) Reset() {
	*x = CountTokensRequest{}
	mi := &file_google_cloud_aiplatform_master_tool_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CountTokensRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CountTokensRequest) ProtoMessage() {}

func (x *CountTokensRequest) ProtoReflect() protoreflect.Message {
	mi := &file_google_cloud_aiplatform_master_tool_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CountTokensRequest.ProtoReflect.Descriptor instead.
func (*CountTokensRequest) Descriptor() ([]byte, []int) {
	return file_google_cloud_aiplatform_master_tool_proto_rawDescGZIP(), []int{15}
}

func (x *CountTokensRequest) GetModel() string {
	if x != nil {
		return x.Model
	}
	return ""
}

func (x *CountTokensRequest) GetContents() []*Content {
	if x != nil {
		return x.Contents
	}
	return nil
}

type CountTokensResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TotalTokens   int32                  `protobuf:"varint,1,opt,name=total_tokens,json=totalTokens,proto3" json:"total_tokens,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CountTokensResponse) Reset() {
	*x = CountTokensResponse{}
	mi := &file_google_cloud_aiplatform_master_tool_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CountTokensResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CountTokensResponse) ProtoMessage() {}

func (x *CountTokensResponse) ProtoReflect() protoreflect.Message {
	mi := &file_google_cloud_aiplatform_master_tool_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CountTokensResponse.ProtoReflect.Descriptor instead.
func (*CountTokensResponse) Descriptor() ([]byte, []int) {
	return file_google_cloud_aiplatform_master_tool_proto_rawDescGZIP(), []int{16}
}

func (x *CountTokensResponse) GetTotalTokens() int32 {
	if x != nil {
		return x.TotalTokens
	}
	return 0
}

var File_google_cloud_aiplatform_master_tool_proto protoreflect.FileDescriptor

const file_google_cloud_aiplatform_master_tool_proto_rawDesc = "" +
	"\n" +
	")google/cloud/aiplatform/master/tool.proto\x12\x1egoogle.cloud.aiplatform.master\x1a\x1cgoogle/protobuf/struct.proto\"\xb9\x01\n" +
	"\x13FunctionDeclaration\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12 \n" +
	"\vdescription\x18\x02 \x01(\tR\vdescription\x127\n" +
	"\n" +
	"parameters\x18\x03 \x01(\v2\x17.google.protobuf.StructR\n" +
	"parameters\x123\n" +
	"\bresponse\x18\x04 \x01(\v2\x17.google.protobuf.StructR\bresponse\"O\n" +
	"\fFunctionCall\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12+\n" +
	"\x04args\x18\x02 \x01(\v2\x17.google.protobuf.StructR\x04args\"[\n" +
	"\x10FunctionResponse\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x123\n" +
	"\bresponse\x18\x02 \x01(\v2\x17.google.protobuf.StructR\bresponse\"\x8b\x04\n" +
	"\x16GenerateContentRequest\x12\x14\n" +
	"\x05model\x18\x01 \x01(\tR\x05model\x12C\n" +
	"\bcontents\x18\x02 \x03(\v2'.google.cloud.aiplatform.master.ContentR\bcontents\x12V\n" +
	"\x12system_instruction\x18\x06 \x01(\v2'.google.cloud.aiplatform.master.ContentR\x11systemInstruction\x12:\n" +
	"\x05tools\x18\x05 \x03(\v2$.google.cloud.aiplatform.master.ToolR\x05tools\x12K\n" +
	"\vtool_config\x18\a \x01(\v2*.google.cloud.aiplatform.master.ToolConfigR\n" +
	"toolConfig\x12]\n" +
	"\x11generation_config\x18\x04 \x01(\v20.google.cloud.aiplatform.master.GenerationConfigR\x10generationConfig\x12V\n" +
	"\x0fsafety_settings\x18\x03 \x03(\v2-.google.cloud.aiplatform.master.SafetySettingR\x0esafetySettings\"\xdf\x01\n" +
	"\x17GenerateContentResponse\x12I\n" +
	"\n" +
	"candidates\x18\x01 \x03(\v2).google.cloud.aiplatform.master.CandidateR\n" +
	"candidates\x12T\n" +
	"\x0eusage_metadata\x18\x02 \x01(\v2-.google.cloud.aiplatform.master.UsageMetadataR\rusageMetadata\x12#\n" +
	"\rmodel_version\x18\x03 \x01(\tR\fmodelVersion\"Y\n" +
	"\aContent\x12\x12\n" +
	"\x04role\x18\x01 \x01(\tR\x04role\x12:\n" +
	"\x05parts\x18\x02 \x03(\v2$.google.cloud.aiplatform.master.PartR\x05parts\"\xce\x02\n" +
	"\x04Part\x12\x14\n" +
	"\x04text\x18\x01 \x01(\tH\x00R\x04text\x12S\n" +
	"\rfunction_call\x18\x03 \x01(\v2,.google.cloud.aiplatform.master.FunctionCallH\x00R\ffunctionCall\x12_\n" +
	"\x11function_response\x18\x04 \x01(\v20.google.cloud.aiplatform.master.FunctionResponseH\x00R\x10functionResponse\x12G\n" +
	"\vinline_data\x18\x02 \x01(\v2$.google.cloud.aiplatform.master.BlobH\x00R\n" +
	"inlineData\x12\x1d\n" +
	"\athought\x18\n" +
	" \x01(\bH\x01R\athought\x88\x01\x01B\x06\n" +
	"\x04dataB\n" +
	"\n" +
	"\b_thought\"7\n" +
	"\x04Blob\x12\x1b\n" +
	"\tmime_type\x18\x01 \x01(\tR\bmimeType\x12\x12\n" +
	"\x04data\x18\x02 \x01(\fR\x04data\"s\n" +
	"\tCandidate\x12A\n" +
	"\acontent\x18\x01 \x01(\v2'.google.cloud.aiplatform.master.ContentR\acontent\x12#\n" +
	"\rfinish_reason\x18\x02 \x01(\tR\ffinishReason\"\x9f\x01\n" +
	"\rUsageMetadata\x12,\n" +
	"\x12prompt_token_count\x18\x01 \x01(\x05R\x10promptTokenCount\x124\n" +
	"\x16candidates_token_count\x18\x02 \x01(\x05R\x14candidatesTokenCount\x12*\n" +
	"\x11total_token_count\x18\x03 \x01(\x05R\x0ftotalTokenCount\"p\n" +
	"\x04Tool\x12h\n" +
	"\x15function_declarations\x18\x01 \x03(\v23.google.cloud.aiplatform.master.FunctionDeclarationR\x14functionDeclarations\"{\n" +
	"\n" +
	"ToolConfig\x12m\n" +
	"\x17function_calling_config\x18\x01 \x01(\v25.google.cloud.aiplatform.master.FunctionCallingConfigR\x15functionCallingConfig\"+\n" +
	"\x15FunctionCallingConfig\x12\x12\n" +
	"\x04mode\x18\x01 \x01(\tR\x04mode\"\xff\x01\n" +
	"\x10GenerationConfig\x12%\n" +
	"\vtemperature\x18\x01 \x01(\x02H\x00R\vtemperature\x88\x01\x01\x12\x18\n" +
	"\x05top_p\x18\x02 \x01(\x02H\x01R\x04topP\x88\x01\x01\x12\x18\n" +
	"\x05top_k\x18\x03 \x01(\x05H\x02R\x04topK\x88\x01\x01\x12/\n" +
	"\x11max_output_tokens\x18\x05 \x01(\x05H\x03R\x0fmaxOutputTokens\x88\x01\x01\x12%\n" +
	"\x0estop_sequences\x18\x06 \x03(\tR\rstopSequencesB\x0e\n" +
	"\f_temperatureB\b\n" +
	"\x06_top_pB\b\n" +
	"\x06_top_kB\x14\n" +
	"\x12_max_output_tokens\"I\n" +
	"\rSafetySetting\x12\x1a\n" +
	"\bcategory\x18\x01 \x01(\tR\bcategory\x12\x1c\n" +
	"\tthreshold\x18\x02 \x01(\tR\tthreshold\"o\n" +
	"\x12CountTokensRequest\x12\x14\n" +
	"\x05model\x18\x01 \x01(\tR\x05model\x12C\n" +
	"\bcontents\x18\x02 \x03(\v2'.google.cloud.aiplatform.master.ContentR\bcontents\"8\n" +
	"\x13CountTokensResponse\x12!\n" +
	"\ftotal_tokens\x18\x01 \x01(\x05R\vtotalTokensBCZAgithub.com/router-for-me/CLIProxyAPI/v6/internal/proto/aiplatformb\x06proto3"

var (
	file_google_cloud_aiplatform_master_tool_proto_rawDescOnce sync.Once
	file_google_cloud_aiplatform_master_tool_proto_rawDescData []byte
)

func file_google_cloud_aiplatform_master_tool_proto_rawDescGZIP() []byte {
	file_google_cloud_aiplatform_master_tool_proto_rawDescOnce.Do(func() {
		file_google_cloud_aiplatform_master_tool_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_google_cloud_aiplatform_master_tool_proto_rawDesc), len(file_google_cloud_aiplatform_master_tool_proto_rawDesc)))
	})
	return file_google_cloud_aiplatform_master_tool_proto_rawDescData
}

var file_google_cloud_aiplatform_master_tool_proto_msgTypes = make([]protoimpl.MessageInfo, 17)
var file_google_cloud_aiplatform_master_tool_proto_goTypes = []any{
	(*FunctionDeclaration)(nil),     // 0: google.cloud.aiplatform.master.FunctionDeclaration
	(*FunctionCall)(nil),            // 1: google.cloud.aiplatform.master.FunctionCall
	(*FunctionResponse)(nil),        // 2: google.cloud.aiplatform.master.FunctionResponse
	(*GenerateContentRequest)(nil),  // 3: google.cloud.aiplatform.master.GenerateContentRequest
	(*GenerateContentResponse)(nil), // 4: google.cloud.aiplatform.master.GenerateContentResponse
	(*Content)(nil),                 // 5: google.cloud.aiplatform.master.Content
	(*Part)(nil),                    // 6: google.cloud.aiplatform.master.Part
	(*Blob)(nil),                    // 7: google.cloud.aiplatform.master.Blob
	(*Candidate)(nil),               // 8: google.cloud.aiplatform.master.Candidate
	(*UsageMetadata)(nil),           // 9: google.cloud.aiplatform.master.UsageMetadata
	(*Tool)(nil),                    // 10: google.cloud.aiplatform.master.Tool
	(*ToolConfig)(nil),              // 11: google.cloud.aiplatform.master.ToolConfig
	(*FunctionCallingConfig)(nil),   // 12: google.cloud.aiplatform.master.FunctionCallingConfig
	(*GenerationConfig)(nil),        // 13: google.cloud.aiplatform.master.GenerationConfig
	(*SafetySetting)(nil),           // 14: google.cloud.aiplatform.master.SafetySetting
	(*CountTokensRequest)(nil),      // 15: google.cloud.aiplatform.master.CountTokensRequest
	(*CountTokensResponse)(nil),     // 16: google.cloud.aiplatform.master.CountTokensResponse
	(*structpb.Struct)(nil),         // 17: google.protobuf.Struct
}
var file_google_cloud_aiplatform_master_tool_proto_depIdxs = []int32{
	17, // 0: google.cloud.aiplatform.master.FunctionDeclaration.parameters:type_name -> google.protobuf.Struct
	17, // 1: google.cloud.aiplatform.master.FunctionDeclaration.response:type_name -> google.protobuf.Struct
	17, // 2: google.cloud.aiplatform.master.FunctionCall.args:type_name -> google.protobuf.Struct
	17, // 3: google.cloud.aiplatform.master.FunctionResponse.response:type_name -> google.protobuf.Struct
	5,  // 4: google.cloud.aiplatform.master.GenerateContentRequest.contents:type_name -> google.cloud.aiplatform.master.Content
	5,  // 5: google.cloud.aiplatform.master.GenerateContentRequest.system_instruction:type_name -> google.cloud.aiplatform.master.Content
	10, // 6: google.cloud.aiplatform.master.GenerateContentRequest.tools:type_name -> google.cloud.aiplatform.master.Tool
	11, // 7: google.cloud.aiplatform.master.GenerateContentRequest.tool_config:type_name -> google.cloud.aiplatform.master.ToolConfig
	13, // 8: google.cloud.aiplatform.master.GenerateContentRequest.generation_config:type_name -> google.cloud.aiplatform.master.GenerationConfig
	14, // 9: google.cloud.aiplatform.master.GenerateContentRequest.safety_settings:type_name -> google.cloud.aiplatform.master.SafetySetting
	8,  // 10: google.cloud.aiplatform.master.GenerateContentResponse.candidates:type_name -> google.cloud.aiplatform.master.Candidate
	9,  // 11: google.cloud.aiplatform.master.GenerateContentResponse.usage_metadata:type_name -> google.cloud.aiplatform.master.UsageMetadata
	6,  // 12: google.cloud.aiplatform.master.Content.parts:type_name -> google.cloud.aiplatform.master.Part
	1,  // 13: google.cloud.aiplatform.master.Part.function_call:type_name -> google.cloud.aiplatform.master.FunctionCall
	2,  // 14: google.cloud.aiplatform.master.Part.function_response:type_name -> google.cloud.aiplatform.master.FunctionResponse
	7,  // 15: google.cloud.aiplatform.master.Part.inline_data:type_name -> google.cloud.aiplatform.master.Blob
	5,  // 16: google.cloud.aiplatform.master.Candidate.content:type_name -> google.cloud.aiplatform.master.Content
	0,  // 17: google.cloud.aiplatform.master.Tool.function_declarations:type_name -> google.cloud.aiplatform.master.FunctionDeclaration
	12, // 18: google.cloud.aiplatform.master.ToolConfig.function_calling_config:type_name -> google.cloud.aiplatform.master.FunctionCallingConfig
	5,  // 19: google.cloud.aiplatform.master.CountTokensRequest.contents:type_name -> google.cloud.aiplatform.master.Content
	20, // [20:20] is the sub-list for method output_type
	20, // [20:20] is the sub-list for method input_type
	20, // [20:20] is the sub-list for extension type_name
	20, // [20:20] is the sub-list for extension extendee
	0,  // [0:20] is the sub-list for field type_name
}

func init() { file_google_cloud_aiplatform_master_tool_proto_init() }
func file_google_cloud_aiplatform_master_tool_proto_init() {
	if File_google_cloud_aiplatform_master_tool_proto != nil {
		return
	}
	file_google_cloud_aiplatform_master_tool_proto_msgTypes[6].OneofWrappers = []any{
		(*Part_Text)(nil),
		(*Part_FunctionCall)(nil),
		(*Part_FunctionResponse)(nil),
		(*Part_InlineData)(nil),
	}
	file_google_cloud_aiplatform_master_tool_proto_msgTypes[13].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_google_cloud_aiplatform_master_tool_proto_rawDesc), len(file_google_cloud_aiplatform_master_tool_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   17,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_google_cloud_aiplatform_master_tool_proto_goTypes,
		DependencyIndexes: file_google_cloud_aiplatform_master_tool_proto_depIdxs,
		MessageInfos:      file_google_cloud_aiplatform_master_tool_proto_msgTypes,
	}.Build()
	File_google_cloud_aiplatform_master_tool_proto = out.File
	file_google_cloud_aiplatform_master_tool_proto_goTypes = nil
	file_google_cloud_aiplatform_master_tool_proto_depIdxs = nil
}
