// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v4.25.1
// source: logs/proto/learning/smartchoices/feedback_id.proto

package smartchoices

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type FeedbackId struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            []byte                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FeedbackId) Reset() {
	*x = FeedbackId{}
	mi := &file_logs_proto_learning_smartchoices_feedback_id_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FeedbackId) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FeedbackId) ProtoMessage() {}

func (x *FeedbackId) ProtoReflect() protoreflect.Message {
	mi := &file_logs_proto_learning_smartchoices_feedback_id_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FeedbackId.ProtoReflect.Descriptor instead.
func (*FeedbackId) Descriptor() ([]byte, []int) {
	return file_logs_proto_learning_smartchoices_feedback_id_proto_rawDescGZIP(), []int{0}
}

func (x *FeedbackId) GetId() []byte {
	if x != nil {
		return x.Id
	}
	return nil
}

var File_logs_proto_learning_smartchoices_feedback_id_proto protoreflect.FileDescriptor

const file_logs_proto_learning_smartchoices_feedback_id_proto_rawDesc = "" +
	"\n" +
	"2logs/proto/learning/smartchoices/feedback_id.proto\x12\fsmartchoices\"\x1c\n" +
	"\n" +
	"FeedbackId\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\fR\x02idBKZIgithub.com/router-for-me/CLIProxyAPI/v6/internal/proto/stubs/smartchoicesb\x06proto3"

var (
	file_logs_proto_learning_smartchoices_feedback_id_proto_rawDescOnce sync.Once
	file_logs_proto_learning_smartchoices_feedback_id_proto_rawDescData []byte
)

func file_logs_proto_learning_smartchoices_feedback_id_proto_rawDescGZIP() []byte {
	file_logs_proto_learning_smartchoices_feedback_id_proto_rawDescOnce.Do(func() {
		file_logs_proto_learning_smartchoices_feedback_id_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_logs_proto_learning_smartchoices_feedback_id_proto_rawDesc), len(file_logs_proto_learning_smartchoices_feedback_id_proto_rawDesc)))
	})
	return file_logs_proto_learning_smartchoices_feedback_id_proto_rawDescData
}

var file_logs_proto_learning_smartchoices_feedback_id_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_logs_proto_learning_smartchoices_feedback_id_proto_goTypes = []any{
	(*FeedbackId)(nil), // 0: smartchoices.FeedbackId
}
var file_logs_proto_learning_smartchoices_feedback_id_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_logs_proto_learning_smartchoices_feedback_id_proto_init() }
func file_logs_proto_learning_smartchoices_feedback_id_proto_init() {
	if File_logs_proto_learning_smartchoices_feedback_id_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_logs_proto_learning_smartchoices_feedback_id_proto_rawDesc), len(file_logs_proto_learning_smartchoices_feedback_id_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_logs_proto_learning_smartchoices_feedback_id_proto_goTypes,
		DependencyIndexes: file_logs_proto_learning_smartchoices_feedback_id_proto_depIdxs,
		MessageInfos:      file_logs_proto_learning_smartchoices_feedback_id_proto_msgTypes,
	}.Build()
	File_logs_proto_learning_smartchoices_feedback_id_proto = out.File
	file_logs_proto_learning_smartchoices_feedback_id_proto_goTypes = nil
	file_logs_proto_learning_smartchoices_feedback_id_proto_depIdxs = nil
}
